### ISSUE TITLE
Does PLV8 support JIT compile like standard JS V8 engine?

### ISSUE THREAD

**Issue by loraxman** [plv8/plv8js#316]
Does PLV8 support JIT compile like standard JS V8 engine? I was wondering if my stored procedures are actually compiled at some point like a Node app.

**Comment by JerrySievert** [comment]
plv8 uses v8 as its javascript engine.  exact features of the engine are specific to the version of v8 that is in use:

* 2.3 - 6.4
* 2.1 - 5.8
* 2.0 - 5.4
* 1.5 - 4.10
* 1.4 - 3.14

plv8 version numbers go up as the underlying engine version numbers go up, and thus the specific features of v8 are according to what v8 has implemented.
