### ISSUE TITLE
Web Assembly: thoughts?

### ISSUE THREAD

**Issue by benjie** [plv8/plv8js#317]
Hey; fantastic project ❤️

Wasn't sure where to reach out and couldn't find any other issues asking so: is there a plan to add Web Assembly support to PL/v8?

**Comment by JerrySievert** [comment]
the amount web assembly support is dependent on which version of plv8 (and thus v8) that you are using.

`emscripten` doesn't target plv8 directly, but you can add your own wrapper and function exports as needed.

give this a try:

```
DO $$
  var memory = new WebAssembly.Memory({initial:10, maximum:100});
  memory.grow(1);
  var b = new Uint32Array(memory.buffer)[0] = 42;
  plv8.elog(NOTICE, JSON.stringify(b));
$$ LANGUAGE plv8;
```

**Comment by JerrySievert** [comment]
just to follow up, I think the issue you will run into is blocking long enough for the promise to be resolved during the compile/instantiate.

**Comment by benjie** [comment]
Interesting, I don’t have a particular use case in mind right now but it’s always great to know what’s possible. I look forward to having a little play, thanks for the guidance 🙏

**Comment by ppKrauss** [comment]
Two suggestions from geoprocessing community, where a lot of C++ libs are useful for online and PostgreSQL-embedded Javascript.

* Most simple: Geohash from [libgeohash](https://github.com/simplegeo/libgeohash) to WebAssembly,  and compare it with [node-geohash-cpp](https://github.com/gnagel/node-geohash-cpp) and [PostGIS's Geohash](https://postgis.net/docs/ST_GeomFromGeoHash.html).

* More useful but complex, to build a WebAssembly lib and good benchmark: the library of [S2 geometry](https://github.com/google/s2geometry) (C++ canonical distribution) or [Uber H3](https://github.com/uber/h3) (C code). <br/>The PostGIS community need it (can help PLV8 community), as a better option to Geohash. See:  *"support for S2 Geometry cells, and have a look at making a fast ST_Intersects GIN index on geography using them"*, at [PostGIS3 proposal](https://trac.osgeo.org/postgis/wiki/PostGIS3).  To compare (benchmark of plV8+WebAssembly) can use [this  s2-postgis](https://github.com/AfieldTrails/s2-postgis) implementation.

PS: for all there are good benchmark and useful bigdata from OpenStreetMap (see *planet* dumps).
