### ISSUE TITLE
[Q] asynchrous javascript function call  IN PLV8 PROCEDURE

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#327]
CREATE OR REPLACE FUNCTION tnt_ex_async_parallel(
	OUT jval json)
    RETURNS json
    LANGUAGE 'plv8'
    COST 100
    IMMUTABLE 
AS $BODY$
let val;
_async.parallel([   //  <========     https://github.com/caolan/async // imported as _async
    function(callback) {
        callback(null, 'one');
    },
    function(callback) {
        callback(null, 'two');
    }
],
// optional callback
function(err, results) {
    // results is now equal to ['one', 'two']
    val = results;
});
return val;
$BODY$;

/*
select * from tnt_ex_async_parallel();
*/

On mytest,
plv8 function not support asynchrous function call.
(not parallel only series)

Does plv8 support asynchrous function call?
If yes, can you  show examples?

Sorry for poor english
and thank you for great library!

**Comment by JerrySievert** [comment]
plv8 supports asynchronous functions in the way that v8 supports them.  but, plv8 calls outside of your stored procedure (using methods exposed in the `plv8` namespace) are strictly synchronous.  plv8 does not expose any asynchronous calls directly.

is there something specific you are trying to accomplish?  if so, I can likely point you in a good direction.

**Comment by hellower** [comment]
Thank you for reply.
If I have any questions, I will open it again.
