### ISSUE TITLE
plv8 version upgrade script problem

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#331]
I upgraded to 2.3.9 -> 2.3.10 successfully.
(ALTER EXTENSION plv8 UPDATE to 2.3.10)
but  wrong version info displayed.

SQL> select * from plv8_version();
 plv8_version 
--------------
 **2.3.10**
(1 row)
SQL> 
DO $$
plv8.elog(WARNING, 'plv8.version = ' + plv8.version); // Will output the PL/v8 installed as a PostgreSQL `WARNING`.
$$ LANGUAGE plv8;
WARNING:  plv8.version = **2.3.9**
SQL> 

===================================================
I found root of problem.
below three funcions not upgraded .
```

CREATE OR REPLACE FUNCTION pg_catalog.plv8_call_handler(
	)
    RETURNS language_handler
    LANGUAGE 'c'

    COST 1
    VOLATILE 
AS '$libdir/plv8-2.3.9', 'plv8_call_handler'
;


CREATE OR REPLACE FUNCTION pg_catalog.plv8_call_validator(
	oid)
    RETURNS void
    LANGUAGE 'c'

    COST 1
    VOLATILE 
AS '$libdir/plv8-2.3.9', 'plv8_call_validator'
;

CREATE OR REPLACE FUNCTION pg_catalog.plv8_inline_handler(
	internal)
    RETURNS void
    LANGUAGE 'c'

    COST 1
    VOLATILE 
AS '$libdir/plv8-2.3.9', 'plv8_inline_handler'
;
```

======= fixed =================================
cat ./share/extension/plv8--2.3.9--2.3.10.sql
```
CREATE OR REPLACE FUNCTION plv8_version ( )
RETURNS TEXT AS
$$
        return "2.3.10";
$$ LANGUAGE plv8;
```

below must be included.
```
CREATE OR REPLACE FUNCTION plv8_call_handler() RETURNS language_handler
 AS 'MODULE_PATHNAME' LANGUAGE C;
CREATE OR REPLACE FUNCTION plv8_inline_handler(internal) RETURNS void
 AS 'MODULE_PATHNAME' LANGUAGE C;
CREATE OR REPLACE FUNCTION plv8_call_validator(oid) RETURNS void
 AS 'MODULE_PATHNAME' LANGUAGE C;

```is missing...




sorry for poor english.

**Comment by JerrySievert** [comment]
thanks for the bug report, I will get it fixed.

and your English is fine :)
