### ISSUE TITLE
plv8 2.3.11 upgrade error

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#333]
SQL> \dx
                          List of installed extensions
  Name   | Version |   Schema   |                  Description                   
---------+---------+------------+------------------------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 plv8    | 2.3.10  | pg_catalog | PL/JavaScript (v8) trusted procedural language
(3 rows)

SQL> ALTER EXTENSION plv8 UPDATE to '2.3.11';
ERROR:  attempt to redefine parameter "plv8.start_proc"
Time: 2.745 ms
SQL> 

-- manual recreation..

SQL> ```
CREATE OR REPLACE FUNCTION pg_catalog.plv8_call_handler(

    RETURNS language_handler
    LANGUAGE 'c'

    COST 1
    VOLATILE 
AS '$libdir/plv8-2.3.11', 'plv8_call_handler'
;
```
ERROR:  attempt to redefine parameter "plv8.start_proc"
Time: 0.943 ms
SQL>

**Comment by mpietrobo** [comment]
Hi, I've got the same issue while trying to upgrade from 2.3.13 to 2.3.15 and I solved it by writing a small patch that checks whether each new GUC variables is already defined or not.
I've submitted a pull request for both branches master and r3.0alpha.

**Comment by JerrySievert** [comment]
awesome, thanks!  saw your PR and will take a look in not too many hours :)
