### ISSUE TITLE
apt install postgresql-10-plv8 ancient

### ISSUE THREAD

**Issue by erichanson** [plv8/plv8js#334]
Any chance we can get a newer version of plv8 pushed upstream to apt for ubuntu 18.04?  The version they have on there is awful, blocks dropping databases and generally runs amok.  Version from source works much better but takes > 1GB mem to compile, crashing micro servers etc.  Alternately a binary distro would be awesome.

**Comment by JerrySievert** [comment]
sorry, I have no control over what debian/ubuntu distribute.  in the past, they have been against distributing versions of plv8 or node.js that did not work with a shared library version of v8 (which would mean any version of v8 newer than 3.14).  that seems to have changed with node.js, but not with plv8.

if you put in a request with their package maintainers, I'm happy to work with them.

**Comment by erichanson** [comment]
Ok will see what I can do.  Thank you for this incredible library.
