### ISSUE TITLE
Can you provide a docker image that already contains plv8

### ISSUE THREAD

**Issue by aruis** [plv8/plv8js#335]
I think this is a good idea to make it easier for everyone to use plv8, and by reading Dockerfile, they can also learn how to properly compile and install plv8.

**Comment by JerrySievert** [comment]
I believe that @asah  has an image on dockerhub, and has an open (changes requested) PR to include a Dockerfile.

There is also documentation on compiling and installing plv8: https://plv8.github.io/#building

if you want to just read a file that does this, you can take a look at the `.travis.yml` file that builds and tests plv8 on every commit/PR: https://github.com/plv8/plv8/blob/r3.0alpha/.travis.yml#L47

**Comment by aruis** [comment]
I tried to write a Dockerfile and built an image on hub.docker.
You can also check it out for me to see if there is something wrong with writing. Thank you very much.
[Dockerfile](https://github.com/aruis/postgres-dockerfile/blob/plv8/Dockerfile)
[Docker Hub](https://hub.docker.com/r/lovearuis/postgres-plv8)

**Comment by asah** [comment]
nice!

you guys want me to optimize the Dockerfile?  easier than explaining...

**Comment by aruis** [comment]
@asah  The image I packaged is particularly large, I am still looking for a reason, if you can give pointers, I am grateful.  😀

**Comment by pkit** [comment]
@aruis Probably you did not delete ./build/v8 after the build, it's like 3.6 gb

**Comment by aruis** [comment]
You are right, I thought I deleted the cache used by the build command, but because the make command and the rm command are not in the same docker layer, the final docker image is still very large. Now that I have improved the Dockerfile, the final image is at 326M and it looks like it should be satisfactory. thank you, @pkit .
