### ISSUE TITLE
toLocalString() crashes server

### ISSUE THREAD

**Issue by citizenfish** [plv8/plv8js#338]
The toLocaleString() method will crash server.

To recreate:-

```
DO
$$
var a =  new Date(1900, 0, 27030).toLocaleString("en-GB");
$$ LANGUAGE PLV8;
```

PLV8 version  2.1.2
Postgres version 9,.6

**Comment by JerrySievert** [comment]
the 2.1 branch is pretty old at this point, though the version you have is the newest of the 2.1 versions.

I can verify that it works in 3.0, but am wary to start bisecting until I get a little more info to see where the problem might lie.

can you tell me what version of v8 its is using (or if you compiled it yourself) and what os and os version?

**Comment by citizenfish** [comment]
This is an RDS instance in Amazon AWS service. I did not compile it myself and hence am not sure I can ascertain the version of V8?
