### ISSUE TITLE
bad sha1 install from pgxn, version 2.3.11

### ISSUE THREAD

**Issue by HairyRabbit** [plv8/plv8js#347]
Hi, I install plv8 from pgxn:

```sh
$ pgxnclient install plv8
```

download file was not match sha1:

```
DEBUG: running pg_config --libdir
DEBUG: running command: ['/usr/bin/pg_config', '--libdir']
DEBUG: testing if /usr/lib/x86_64-linux-gnu is writable
DEBUG: opening url: http://api.pgxn.org/index.json
DEBUG: opening url: http://api.pgxn.org/dist/plv8.json
INFO: best version: plv8 2.3.11
DEBUG: opening url: http://api.pgxn.org/dist/plv8/2.3.11/META.json
DEBUG: opening url: http://api.pgxn.org/dist/plv8/2.3.11/plv8-2.3.11.zip
INFO: saving /tmp/tmpb3cd25p_/plv8-2.3.11.zip
DEBUG: checking sha1 of '/tmp/tmpb3cd25p_/plv8-2.3.11.zip'
ERROR: file /tmp/tmpb3cd25p_/plv8-2.3.11.zip has sha1 02725e1706eb1ab45b1dc8376ce266174a453ac6 instead of f336c72f3353fb12859c543bcd65e601a2e5d142
ERROR: bad sha1 in downloaded file
```

Any helper ?

plv8: 2.3.11
pgxn: 1.2.1
OS: debian 9

**Comment by JerrySievert** [comment]
the pgxn `sha1` is created and checked by pgxn (I believe at upload of the archive to pgxn itself?) to be checked against by the pgxn client.  unfortunately, it's outside of plv8's hands completely.

you can try downloading the file from the plv8 releases tab: https://github.com/plv8/plv8/releases and compiling manually perhaps?

cc'ing @theory who manages pgxn to see if he has an idea on his side.

**Comment by theory** [comment]
I get f336c72f3353fb12859c543bcd65e601a2e5d142, too, so maybe something’s up with [pgxnclient](/pgxn/pgxnclient)? @dvarrazzo, what do you think?

**Comment by dvarrazzo** [comment]
It works in 1.3, which is still to be released. I can try to release it soon (I wanted to automate the tests into travis but not finding much time to work on it, so I guess I'll just release 1.3...).

```
$ pgxn --version
pgxnclient 1.3.dev0

$ pgxn  install --verbose --sudo -- plv8
DEBUG: running pg_config --libdir
DEBUG: running command: ['/usr/bin/pg_config', '--libdir']
DEBUG: testing if /usr/lib/x86_64-linux-gnu is writable
DEBUG: opening url: https://api.pgxn.org/index.json
DEBUG: opening url: https://api.pgxn.org/dist/plv8.json
INFO: best version: plv8 2.3.11
DEBUG: opening url: https://api.pgxn.org/dist/plv8/2.3.11/META.json
DEBUG: opening url: https://api.pgxn.org/dist/plv8/2.3.11/plv8-2.3.11.zip
INFO: saving /var/tmp/tmpbk0lVu/plv8-2.3.11.zip
DEBUG: checking sha1 of '/var/tmp/tmpbk0lVu/plv8-2.3.11.zip'
INFO: unpacking: /var/tmp/tmpbk0lVu/plv8-2.3.11.zip
DEBUG: saving: /var/tmp/tmpbk0lVu/plv8-2.3.11/.gitignore
DEBUG: saving: /var/tmp/tmpbk0lVu/plv8-2.3.11/.travis.yml
DEBUG: saving: /var/tmp/tmpbk0lVu/plv8-2.3.11/COPYRIGHT
...
```

can you try checking out from `git@github.com:pgxn/pgxnclient.git` master and running a `pip install .` there?

**Comment by HairyRabbit** [comment]
@dvarrazzo  Thanks 

I install pgxn 1.3 from github, but also bad sha1,

```
root@localhost:/pgxnclient# pgxn install plv8 --verbose
DEBUG: running pg_config --libdir
DEBUG: running command: ['/usr/bin/pg_config', '--libdir']
DEBUG: testing if /usr/lib/x86_64-linux-gnu is writable
DEBUG: opening url: https://api.pgxn.org/index.json
DEBUG: opening url: https://api.pgxn.org/dist/plv8.json
INFO: best version: plv8 2.3.11
DEBUG: opening url: https://api.pgxn.org/dist/plv8/2.3.11/META.json
DEBUG: opening url: https://api.pgxn.org/dist/plv8/2.3.11/plv8-2.3.11.zip
INFO: saving /tmp/tmpdni97f5_/plv8-2.3.11.zip
DEBUG: checking sha1 of '/tmp/tmpdni97f5_/plv8-2.3.11.zip'
ERROR: file /tmp/tmpdni97f5_/plv8-2.3.11.zip has sha1 94a89854dbabd29c48731f39135112bfb97e03f5 instead of f336c72f3353fb12859c543bcd65e601a2e5d142
ERROR: bad sha1 in downloaded file

root@localhost:/pgxnclient# pgxn --version
pgxnclient 1.3.dev0

```


Looking forward to the release of the new version.

**Comment by JerrySievert** [comment]
@HairyRabbit is it possible that you are being MitM'd?

```
jerry@build:~$ wget https://github.com/plv8/plv8/archive/v2.3.11.zip
--2019-06-18 03:29:56--  https://github.com/plv8/plv8/archive/v2.3.11.zip
Resolving github.com (github.com)... 192.30.255.113
Connecting to github.com (github.com)|192.30.255.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/plv8/plv8/zip/v2.3.11 [following]
--2019-06-18 03:29:59--  https://codeload.github.com/plv8/plv8/zip/v2.3.11
Resolving codeload.github.com (codeload.github.com)... 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘v2.3.11.zip’

v2.3.11.zip             [            <=>     ]   8.89M  57.8KB/s    in 1m 59s

2019-06-18 03:32:02 (76.3 KB/s) - ‘v2.3.11.zip’ saved [9325487]

jerry@build:~$ sha1sum v2.3.11.zip
f336c72f3353fb12859c543bcd65e601a2e5d142  v2.3.11.zip
```

perhaps try `wget https://github.com/plv8/plv8/archive/v2.3.11.zip` followed by `sha1sum v2.3.11.zip` and verify the `sha1` by hand?  I know that I'm asking you to download manually, but since the `sha1` matches what's in pgxn (as it should, since I'm the one who uploaded it to pgxn from the same source), and @theory and @dvarrazzo are both getting the correct `sha1` then it sounds like something else is happening.

**Comment by HairyRabbit** [comment]
@JerrySievert Yeah, I try to download file with curl and wget, but got different results:

```
root@localhost:/# wget -q https://github.com/plv8/plv8/archive/v2.3.11.zip && sha1sum v2.3.1
1.zip
f336c72f3353fb12859c543bcd65e601a2e5d142  v2.3.11.zip

root@localhost:/# curl -so t1.zip https://github.com/plv8/plv8/archive/v2.3.11.zip && sha1su
m t1.zip
96755f3e995dfdbceafeab29e96c9dbd8497cb4e  t1.zip
```

My server was location on Chicago, IL.

I also test some other servers, the result curl and wget both same as 96755f3e995dfdbceafeab29e96c9dbd8497cb4e

**Comment by JerrySievert** [comment]
you might want to take a look at what you downloaded:

```
jerry@build:~$ curl -so t1.zip https://github.com/plv8/plv8/archive/v2.3.11.zip
jerry@build:~$ cat t1.zip
<html><body>You are being <a href="https://codeload.github.com/plv8/plv8/zip/v2.3.11">redirected</a>.</body></html>
```

I specified `wget` as it was following redirects correctly with default arguments.  If you want to do the same with `curl`, be sure to use the `-L` argument to follow redirects `curl -Lo t1.zip https://github.com/plv8/plv8/archive/v2.3.11.zip`

```
jerry@build:~$ curl -Lso t1.zip https://github.com/plv8/plv8/archive/v2.3.11.zip
jerry@build:~$ sha1sum t1.zip
f336c72f3353fb12859c543bcd65e601a2e5d142  t1.zip
```

it might be worthwhile for you to take a look at whatever file `pgxn` is downloading - in your example:

```
ERROR: file /tmp/tmpdni97f5_/plv8-2.3.11.zip has sha1 94a89854dbabd29c48731f39135112bfb97e03f5 instead of f336c72f3353fb12859c543bcd65e601a2e5d142
```

if I had to guess, I'd think that maybe you have some `CURL` environment variables set that are mucking with `pgxn`.  either way, your `wget` is showing that you are indeed able to get the correct zip file that you can build from when not using `pgxn`.

**Comment by HairyRabbit** [comment]
@JerrySievert Oh sorry my bad, I forget follow redirects. I want to build docker image base on postgres image, add pgxn and plv8.  I will check more details about this.
