### ISSUE TITLE
CENTOS plv8 installation problem 

### ISSUE THREAD

**Issue by chongckw** [plv8/plv8js#355]
Hi, I am trying to install the plv8 on my AWS server 
But i meet this error when i start the make command which say the Wmissing prototypes 
I've install the libcxx and libcxx-devel in version 3.8 

[centos@ip-172-31-16-47 plv8-2.3.8]$ make
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 25.82 MiB ...
remote: Counting objects: 10, done
remote: Finding sources: 100% (10/10)
remote: Total 33772 (delta 23496), reused 33767 (delta 23496)
Receiving objects: 100% (33772/33772), 25.81 MiB | 17.27 MiB/s, done.
Resolving deltas: 100% (23496/23496), done.
cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; cd build/config ; git cherry-pick 4287a0d364541583a50cc9146251460d489a ; cd ../.. ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=tru_use_external_startup_data=false v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8./home/centos/plv8-2.3.8/build/_gclient_v8_nCdrCn' in '/home/centos/plv8-2.3.8/build'
1>Cloning into '/home/centos/plv8-2.3.8/build/_gclient_v8_nCdrCn'...
1>remote: Sending approximately 524.16 MiB ...
1>remote: Counting objects: 7717, done
1>remote: Finding sources: 100% (57/57)
1>remote: Total 693419 (delta 575740), reused 693386 (delta 575740)
1>Receiving objects: 100% (693419/693419), 523.55 MiB | 23.22 MiB/s, done.
1>Resolving deltas: 100% (575740/575740), done.
1>Syncing projects:   0% ( 0/ 2)
[0:02:04] Still working on:
[0:02:04]   v8
Syncing projects: 100% (27/27), done.

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buools/linux64/clang-format.sha1' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 7.413382 second(s)
Running hooks:  30% ( 8/26) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-teststs.tar.gz.sha1' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 224 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 6.355212 second(s)
Running hooks:  42% (11/26) sysroot_x86
________ running '/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/home/centos/plv8-2.3.8/build'
Installing Debian sid i386 root image: /home/centos/plv8-2.3.8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/9e6279438ece6fb42b5333ca90d5e9d0c188a403/dn_sid_i386_sysroot.tar.xz
Running hooks:  50% (13/26) sysroot_x64
________ running '/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/home/centos/plv8-2.3.8/build'
Installing Debian sid amd64 root image: /home/centos/plv8-2.3.8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/e7c53f04bd88d29d075bfd1f62b073aeb69cbe09/dn_sid_amd64_sysroot.tar.xz
Running hooks:  69% (18/26) binutils
________ running '/bin/python v8/third_party/binutils/download.py' in '/home/centos/plv8-2.3.8/build'
0> Downloading /home/centos/plv8-2.3.8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 6.592933 second(s)
Downloading /home/centos/plv8-2.3.8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/centos/plv8-2.3.8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  73% (19/26) clang
________ running '/bin/python v8/tools/clang/scripts/update.py' in '/home/centos/plv8-2.3.8/build'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-365097-f7e52fbd-8.tgz .......... D
Running hooks: 100% (26/26), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was a5fd60e... Calls to {console} require an access check for the provided arguments
HEAD is now at d481eda... Version 6.4.388.40
Syncing projects: 100% (23/23), done.

WARNING: 'v8/third_party/googletest/src' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/perfetto' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/protobuf' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/depot_tools' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/test/wasm-js/data' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

________ running '/bin/python v8/gypfiles/landmines.py' in '/home/centos/plv8-2.3.8/build'
Clobbering due to:
--- old_landmines       Thu Aug  8 08:11:43 2019
+++ new_landmines       Thu Aug  8 08:12:55 2019
@@ -18,18 +17,0 @@
-Clobber to possibly resolve build failure on Misc V8 Linux gcc.
-Builders switching from make to ninja will clobber on this.
-Need to clobber everything due to an IDL change in r154579 (blink)
-Need to clobber everything due to gen file moves in r175513 (Blink)
-Clobber to get rid of obselete test plugin after r248358
-Clobber to rebuild GN files for V8
-Clobber to get rid of stale generated mojom.h files
-Need to clobber everything due to build_nexe change in nacl r13424
-[chromium-dev] PSA: clobber build needed for IDR_INSPECTOR_* compil...
-blink_resources.grd changed: crbug.com/400860
-ninja dependency cycle: crbug.com/408192
-Clobber to fix missing NaCl gyp dependencies (crbug.com/427427).
-Another clobber for missing NaCl gyp deps (crbug.com/427427).
-Clobber to fix GN not picking up increased ID range (crbug.com/444902)
-Remove NaCl toolchains from the output dir (crbug.com/456902)
-CLobber all to fix GN breakage (crbug.com/736215)
-The Great Blink mv for source files (crbug.com/768828)
-Clobber to workaround buggy .ninja_deps cycle (crbug.com/934404)

________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buools/linux64/clang-format.sha1' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/buildtools/linux64/clang-format...
Downloading 1 files took 6.248808 second(s)
Running hooks:  39% ( 9/23) luci-go_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/lucilinux64' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/tools/luci-go/linux64/isolate...
Downloading 1 files took 6.419074 second(s)
Running hooks:  52% (12/23) gn_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/l64/gn.sha1' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/buildtools/linux64/gn...
Downloading 1 files took 6.251932 second(s)
Running hooks:  56% (13/23) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-teststs.tar.gz.sha1' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Removed v8/test/wasm-spec-tests/tests...
0> Extracting 65 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 6.231934 second(s)
Running hooks:  60% (14/23) closure_compiler
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspecbuild/closure-compiler.tar.gz.sha1' in '/home/centos/plv8-2.3.8/build'
0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
Downloading 1 files took 6.747523 second(s)
Running hooks:  65% (15/23) sysroot
________ running '/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/home/centos/plv8-2.3.8ld'
Installing Debian Stretch amd64 root image: /home/centos/plv8-2.3.8/build/v8/build/linux/debian_stretch_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/dn_stretch_amd64_sysroot.tar.xz
Installing Debian Stretch i386 root image: /home/centos/plv8-2.3.8/build/v8/build/linux/debian_stretch_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/dn_stretch_i386_sysroot.tar.xz
Hook '/bin/python v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 10.76 secs
Running hooks:  82% (19/23) binutils
________ running '/bin/python v8/third_party/binutils/download.py' in '/home/centos/plv8-2.3.8/build'
0> Downloading /home/centos/plv8-2.3.8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
Downloading 1 files took 6.939714 second(s)
Downloading /home/centos/plv8-2.3.8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/centos/plv8-2.3.8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Running hooks:  86% (20/23) clang
________ running '/bin/python v8/tools/clang/scripts/update.py' in '/home/centos/plv8-2.3.8/build'
Updating Clang to 318667-1...
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-318667-1.tgz .......... Done.
Creating directory /home/centos/plv8-2.3.8/build/v8/third_party/llvm-build/Release+Asserts
clang 318667-1 unpacked
Running hooks:  95% (22/23) regyp_if_needed
________ running '/bin/python v8/gypfiles/gyp_v8 --running-as-hook' in '/home/centos/plv8-2.3.8/build'
GYP is now disabled by default in runhooks.

If you really want to run this, either run
`python gypfiles/gyp_v8` explicitly by hand
or set the environment variable GYP_CHROMIUM_NO_ACTION=0.
Running hooks: 100% (23/23), done.
[detached HEAD 6004975] [ios] Various build fixes for Xcode 10.
 Author: Justin Cohen <justincohen@google.com>
 2 files changed, 36 insertions(+), 11 deletions(-)
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
[1/1] Regenerating ninja files
[665/665] LINK ./d8
mkdir -p upgrade
./generate_upgrade.sh 2.3.8
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plv8 - > plv8--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plcoffee - > plcoffee--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plls - > plls--2.3.8.sql
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.3.8"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_type.o plv8_type.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_func.o plv8_func.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_param.o plv8_param.cc
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
(od -txC -v coffee-script.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
echo "0x00};" >>coffee-script.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o coffee-script.o coffee-script.cc
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
echo "0x00};" >>livescript.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -std=c++11 -I. -I. -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o livescript.o livescript.cc
g++ -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -shared -o plv8-2.3.8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/lib64 -Wl,-z,relro   -Wl,--as-needed  -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -Lbuild/v8/out.gn/x64.release/obj -lrt -std=c++11 -lc++
[centos@ip-172-31-16-47 plv8-2.3.8]$

**Comment by JerrySievert** [comment]
can you help me find which part of this is producing an error?

both v8 and plv8 appear to be building successfully in your log output.

**Comment by chongckw** [comment]
I though the Wmissing-Prototypes is the error.

When i do the installcheck all the test result shows failed.

And the regression.diffs show cannot find the plv8

centos@ip-172-31-16-47 plv8-2.3.8]$ make installcheck
/usr/lib64/pgsql/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=. --psqldir='/usr/bin'   --dbname=contrib_regression init-extension plv8 plv8-errors inline json startup_pre startup varparam json_conv window guc es6 arraybuffer composites currentresource startup_perms bytea dialect
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test init-extension           ... FAILED
test plv8                     ... FAILED
test plv8-errors              ... FAILED
test inline                   ... FAILED
test json                     ... FAILED
test startup_pre              ... FAILED
test startup                  ... FAILED
test varparam                 ... FAILED
test json_conv                ... FAILED
test window                   ... FAILED
test guc                      ... FAILED
test es6                      ... FAILED
test arraybuffer              ... FAILED
test composites               ... FAILED
test currentresource          ... FAILED
test startup_perms            ... FAILED
test bytea                    ... FAILED
test dialect                  ... FAILED

========================
 18 of 18 tests failed.
========================



On 8 Aug 2019, at 10:39 PM, Jerry Sievert <notifications@github.com<mailto:notifications@github.com>> wrote:


can you help me find which part of this is producing an error?

both v8 and plv8 appear to be building successfully in your log output.

**Comment by JerrySievert** [comment]
I didn't see any actual error messages in what you posted, and what appears to be a full build:

```
[665/665] LINK ./d8
```

from the v8 build, and:

```
g++ -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fPIC -shared -o plv8-2.3.8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/lib64 -Wl,-z,relro -Wl,--as-needed -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -Lbuild/v8/out.gn/x64.release/obj -lrt -std=c++11 -lc++
```

from the plv8 build.

are you sure that you ran `make install` before running `make installcheck`?  can you provide the output of `regressions.diff` as if there is a reason why `plv8.so` cannot be loaded, it will be listed there.

**Comment by JerrySievert** [comment]
going to close this
