### ISSUE TITLE
Optimizing module importing

### ISSUE THREAD

**Issue by mitar** [plv8/plv8js#359]
I have read online about module importing and from what I can tell most approaches suggest a table where you store modules' code and then inside your function you import/load code from that table. This looks reasonable but I worry about the fact that this means that during every execution of a function, those modules' code will have to be loaded (which does take time).

Would it be possible to add some feature where at function declaration time load those? I was thinking that maybe the easiest way would be to allow that function declaration receives a JavaScript function which is called and which should return the real function to be called later on.

So something like (using the example from documentation):

```sql
CREATE FUNCTION plv8_test(keys TEXT[], vals TEXT[]) RETURNS JSON AS $
    return function (global) {
        var _ = require('underscore');
        return function(keys, vals) {
            return _.object(keys, vals);
        }
    }
$ LANGUAGE plv8 IMMUTABLE STRICT;
```

I know that there is `plv8.start_proc`, but this requires one to set global variables, more like in the browser setting, which is this days not as nice as using modules.

Probably `require` could be made so that it caches things, but that would still mean that inside each session we would have to load once everything. But maybe that is what `start_proc` does as well?

**Comment by JerrySievert** [comment]
> Would it be possible to add some feature where at function declaration time load those? I was thinking that maybe the easiest way would be to allow that function declaration receives a JavaScript function which is called and which should return the real function to be called later on.

this is exactly what `plv8.start_proc` is - at a per context level, which lasts as long as your role's connection to the database.  I'm not sure what else you'd be expecting that is either not global nor essentially an instant load from memory that would require compilation of the module.  you have a choice: load these at function execution from a cache in the context which will already be compiled, or load these from the database (which has the ability to be faster than loading from disk) and compile them on use like node or a browser does.

**Comment by mitar** [comment]
Hm, maybe I am just misunderstanding how `start_proc` interacts when I use `SECURITY DEFINER`? There is no session then?

**Comment by JerrySievert** [comment]
I think that you're not understanding the difference between a v8 context and a postgres memory context.

**Comment by mitar** [comment]
Oh, I see that there is also `SET` argument to `CREATE FUNCTION` which I can use to set `plv8.start_proc`. That means I can do `CREATE FUNCTION ... SET plv8.start_proc TO 'plv8_init'`? Or is this too late?

**Comment by JerrySievert** [comment]
`plv8.start_proc` is a `GUC` and can be set at any time, but it will only execute once for each `v8` context, where a `v8` context is unique to a session/role.

so:

1. user creates connection with their role to the database
2. user executes a `plv8` function
  * `v8` context created
  * `start_proc` executed if defined and role has permission
  * function executed in `v8` context`
3. user executes another `plv8` function
  * function executed in existing `v8` context
4. user changes roles
5. user (with new role) executes a `plv8` function
  * `v8` context created
  * `start_proc` executed if defined and role has permission
  * function executed in new `v8` context
6. user changes back to original role
7. user executes `plv8` function
  * function executes in original `v8` context

`plv8` will execute the `plv8.start_proc` to whatever is set if the role has permission when the `v8` context is created.

a `v8` context, like the postgres backend that it is part of, lasts no longer than the process (or connection).

**Comment by mitar** [comment]
Sure, but if I define function which has `SECURITY DEFINER` set, then the role changes when the function is called, or not? I think I am confused when is a v8 context created for triggers?

**Comment by JerrySievert** [comment]
a `v8` context exists for the role executing the function.  no matter how you get that role set, if `Alice` executes a function, and it is under `Bob's` role, then it is executed in `Bob's` context.

a `v8` context exists for each role that executes javascript code.

**Comment by mitar** [comment]
And `plv8.start_proc` is not reset when roles change?

**Comment by JerrySievert** [comment]
a `plv8.start_proc` **ONLY** executes when a `v8` context is created.  so, as noted above:

1. javascript function is asked to be executed
2. a `v8` context is created if it does not exist in that session for the role that the function would execute under
  * if the context exists, it will *NOT* run the `start_proc` again, like it did when the context ... started
  * if the context does not exists, it will be created, and thus it will run the `start_proc` if the role that the `v8` context is created for has permission to run the `start_proc`

**Comment by mitar** [comment]
I mean, the value of `plv8.start_proc` GUC is not reset when roles change? It is not cleared or something?

**Comment by mitar** [comment]
But thanks. I think I know what to do. In `plv8.start_proc` function I define `require`, and then in `require` I cache loaded modules, so that they are loaded only once. I think node does a similar thing with `require.cache`.

**Comment by JerrySievert** [comment]
it's a `GUC`.  it's a *configuration* variable.  it changes when you specifically `SET` it.
