### ISSUE TITLE
Async operation and promises

### ISSUE THREAD

**Issue by mitar** [plv8/plv8js#360]
I am reading about plv8 and I am really impressed. But using existing JavaScript code these days means that there is generally assumption about async behavior: or through callbacks or through promises. So if the code uses those, I do not see an easy way for it to be used inside plv8?

So I wonder, could plv8 functions be called with `await`? So that if they return a `Promise`, the engine would in async manner wait for that promise to resolve and then use that as the return value of the function?

**Comment by pkit** [comment]
plv8 has no event loop.
therefore any `await` will be executed in a sync manner
although because plv8 is a trusted environment with no access to outside the postgres it will not need any **real** async operations

**Comment by JerrySievert** [comment]
the part that `await` and `async` would help would be for the compilation of `webasm`.

I've considered spending some time on it, but it hasn't been high priority.

**Comment by pkit** [comment]
hmm, dunno
await and async work for me out-of-the-box with new v8 in 3.0alpha
but they are not async in any sense
what's obviously doesn't work is `setTimeout` and friends, for obvious reasons

**Comment by JerrySievert** [comment]
well, yeah, of course those won't work.

to be fair, I haven't tried webasm compilation since 3.0alpha, it might be worth some time.

**Comment by pkit** [comment]
it is pretty easy to create some sort of event loop through a postgres background worker process
I have even done something like it, but using closed source facilities, so cannot open source it for now
I've got real async promises but ACID guarantees go out of the window...

**Comment by JerrySievert** [comment]
I'm sure I could handle it if I put my mind to it, but since I'm not using plv8 daily at the moment, some of the more novel things I would normally be doing have been taking a backseat to projects that can put money in my pockets.

**Comment by mitar** [comment]
For me the fact that async/await simply makes things synchronous is good enough. Just that it is supported and that same code which does use it can run. If this is already the case, maybe just adding documentation explaining that would be enough?
