### ISSUE TITLE
Ability to LISTEN

### ISSUE THREAD

**Issue by claytongulick** [plv8/plv8js#363]
This might be a total non-starter since there's no event loop, currently.

I'm working on a lib that proxies calls between Node and PG. Currently works like a charm invoking plv8 functions from Node and returning the results.

What I'd like to do is also implement a reverse proxy, where Node functions can be invoked from plv8. I was thinking the most straight forward way to do this is to use NOTIFY as a transport.

This is fine for invoking the Node function, but I don't have a way to return a response back from that invoked function, since pg's notification's only really execute on the client.

If plv8 had the ability to raise an event on notification, i.e. plv8.on('notification', () => {...}) I could send back a serialized result to the executing plv8 function from Node.

If this even a thing that's worth considering/possible?

Footnote: here's the initial work on the lib: https://github.com/claytongulick/pgproxy

Thanks!!

**Comment by JerrySievert** [comment]
since there's no event loop, there wouldn't really be a function already executing to receive the notification.

how about just executing a plv8 function instead, with the payload being a JSON representation of the notification?

**Comment by JerrySievert** [comment]
for clarification, since on the node.js side, listening for an event notification is asynchronous, it would end up looking something like this:

plv8_function -> notify -> node.js listener -> receive notification

at that point, since the notification is all or nothing as far as plv8 is concerned (and as far as postgres is concerned), the transaction on that side is already complete, so there's nothing you can really wait for.

node.js -> pg -> select function -> plv8

and that's your loop closing - since it's all asynchronous at that point, you'll likely have something keeping state, or your json can pass a token of some sort around.

make sense?

**Comment by claytongulick** [comment]
Hmm, I'm not sure how that would work, trying to think through it. In this case (which currently works in PGProxy, this is [taken from a passing test](https://github.com/claytongulick/pgproxy/blob/master/test/test_pgproxy.js#L180) ):

```javascript
let functions = {
            reverse_test: (param1, param2) => {
                let result = plv8.execute(`select '${param1}' as param1, '${param2}' as param2`);
                nodeFunction(result);
                return result[0];
            }
        };
       
        let proxy = await PGProxy.create(functions, {
            client: client, 
            schema: 'test',
            expose: {
                nodeFunction: (result) => {
                    let row = result[0];
                    assert.equal(row.param1, 'asdf');
                    assert.equal(row.param2, '1234');                    
                }
            }});
        let row = await proxy.reverse_test('asdf','1234');
        assert.equal(row.param1, 'asdf');
        assert.equal(row.param2, '1234');
```

I'd have to take the reverse_test() function, and slice it up into blocks, and based on params passed in to the wrapper function, I'd execute different blocks, simulating an event loop of sorts. Neat concept, but I can't think of a way to make it work 'normally' in js.

The generated wrapper for the above currently looks like:
```javascript
create or replace function test.pgproxy_reverse_test(params json)
returns json
language 'plv8'
as
$BODY$

function reverseProxy(name, args) {
	let payload = {fn:name, params: args, action: 'call'};
	plv8.execute(`NOTIFY pgproxy, '${JSON.stringify(payload)}'`);
}

function nodeFunction() { return reverseProxy.apply({},['nodeFunction',[...arguments]]); }

let reverse_test = (param1, param2) => {
		let result = plv8.execute(`select '${param1}' as param1, '${param2}' as param2`);
		nodeFunction(result);
		return result[0];
	};
let return_value = reverse_test.apply(plv8, params);
return JSON.stringify(return_value);
$BODY$
```

If I understand your suggestion, it would end up looking something like:

```javascript
create or replace function test.pgproxy_reverse_test(params json)
returns json
language 'plv8'
as
$BODY$

function generateToken() {...}
function reverseProxy(name, args) {
	let payload = {fn:name, params: args, action: 'call', step: params.step};
	plv8.execute(`NOTIFY pgproxy, '${JSON.stringify(payload)}'`);
}

function nodeFunction() { return reverseProxy.apply({},['nodeFunction',arguments]); }

let reverse_test = (param1, param2) => {
		if(params.step = 0) {
			let result = plv8.execute(`select '${param1}' as param1, '${param2}' as param2`);
		}
		if(params.step = 1) {
			let response = nodeFunction(result);
		}
		if(params.step = 2 ) {
			return response;
		}
	};
let return_value = reverse_test.apply(plv8, params);
return JSON.stringify(return_value);
$BODY$
```

Which is an interesting concept, but I'd need some way to persist local variable state etc... across calls, so I'd really need a persistent context (i.e. event loop). You can see the problem with the "response" variable between step 1 block and step 2 block, "response" is out of scope.

Unless there's some mechanism in postgres for a long running proc that I'm not familiar with, I don't see how to make that work. I think, as you said, for now we're limited to a "fire and forget" NOTIFY - unless there was a way in plv8 to push/pop a javascript context, which would totally solve the problem.

I guess I could create a context that gets persisted to the db, and load it and apply it as "this" in the called function, so that the user could do this.someThingToKeepStateWith = 'blah'; and that would be available across repeated calls - and maybe that's a fallback solution. One of the goals of the project is to try to keep everything just POJS, and not have to do anything 'weird', i.e. to look like you're just calling a node function, and it's all just normal js all the way down.

**Comment by pkit** [comment]
> I'd really need a persistent context

It's simple, all plv8 contexts are persistent if you do not kill the connection.
I.e. pg background process is running per connection and it holds the isolate where context of each user runs.
Therefore to return you just remember the pointer to the function globally.
And then retrieve it on the way back.
