### ISSUE TITLE
How to get current user/role?

### ISSUE THREAD

**Issue by speller** [plv8/plv8js#366]
Hello,
I was googling a lot and didn't found any short solution. I need to get the current user/role name in a plv8 procedure or function. But to get this very basic and very simple value I have to run postgres query like that:  `plv8.execute("select current_user as val")[0].val` which, I guess, takes much longer time than accessing a global variable. Is there any possibility to get what I need without calling a postgres query?

**Comment by JerrySievert** [comment]
the current user/role is not exposed at this time.  plv8 technically has access to the `Oid` via `GetUserId()` but to map that to a role name, it too would need to do a query against `pg_roles`, which would be a little bit faster for your use case, but would add execution time to every use of plv8.

can you explain what you're doing with it?  there may be an easier or better way to accomplish what you want.

worst case scenario might be to stash the value somewhere, and use it, maybe even as part of the `plv8.start_proc`

**Comment by pkit** [comment]
> worst case scenario might be to stash the value somewhere, and use it, maybe even as part of the `plv8.start_proc`

It's the best case scenario actually
User role never changes, because contexts are user-based.
Therefore setting it to a global in `plv8.start_proc`
```
current_user = plv8.execute("select current_user as val")[0].val
```
seems pretty efficient

**Comment by speller** [comment]
Thank you for your answers!

@pkit My script can switch roles using `set local role some_user;` to execute commands using permissions of the current client of the GraphQL server. I guess, the `start_proc` will not work as expected in my case.

@JerrySievert I'm using a trigger to assign an ACL list to a new row on INSERT commands. The default ACL template is stored in another table and contains some patterns needed to replace it with some current values. One of the patterns is the current user/role name. The position of the current user rule in the set of rules is dynamic. So I preprocess a default ACL template to the real ACL data in my trigger. As I mentioned above, this operation can be made under any role in the DB. And I'm trying to use JS because my project is JS-driven and I want to maximize the scope of this language for the ease of future support.

**Comment by pkit** [comment]
>  I guess, the start_proc will not work as expected in my case.

AFAIK you're guessing wrong. It will switch context to the user, including correct globals.
More than that, I'm using almost exactly the same mechanism to run arbitrary SQL under the said user (obviously a much more secure one than just a simple role switch).

> I'm using a trigger

It's already pretty slow, another sql query here will not add too much latency.
You can use a prepared query if you want.

**Comment by speller** [comment]
> AFAIK you're guessing wrong. It will switch context to the user, including correct globals.

Yup, seems you are right. But I'm using AWS RDS... ) And as I googled it, it doesn't support setting the `plv8.start_proc` option. Running the following query from under a root user fails:

```
ALTER DATABASE mydatabase SET plv8.start_proc = 'public.plv8_startup'
Error in query (7): ERROR: permission denied to set parameter "plv8.start_proc"
```

**Comment by JerrySievert** [comment]
> I'm using a trigger to assign an ACL list to a new row on INSERT commands. 

ah, I see.  as @pkit noted, changing roles changes context for plv8 as well, making it pretty easy to cache the results across queries:

```
if (plv8.current_user) {
  current_user = plv8.current_user;
} else {
  plv8.current_user = current_user = plv8.execute("select current_user as val")[0].val;
}
```

then the value will be available the next time for the same user.

another option would be to  contain the `current_user` as part of the query that gets the ACLs from your other table, either as a sub select or as part of an `array_agg` call, avoid the query altogether.

**Comment by speller** [comment]
That makes sense, thank you. I will work around using your suggestions.
BTW, it would be nice to have a straight way mapping current query environment data to plv8 without startup procs and other tricks.

**Comment by speller** [comment]
Exposure of the following information: https://www.postgresql.org/docs/11/functions-info.html to a global variable or plv8 special field would be very useful, I think.

**Comment by JerrySievert** [comment]
unfortunately, even plv8 would need to query to get a lot of that information in a clean, API agnostic way.

most of that information is stored in Postgres's table-structure.

**Comment by speller** [comment]
Are there any "environment" variables like the current user name that can be accessed easily? If not, probably, at least, it is possible to add globally accessible functions that will do queries to pg. At least, they will hide those routines and will make JS development in PG more convenient.

**Comment by JerrySievert** [comment]
as mentioned before, plv8 has access to the internal numerically mapped role id via `GetUserId()` which is an internal, not guaranteed to be stable function deep inside postgres itself.

plv8 would need to end up wrapping a call just like:

```
function environment(variable) {
  switch (variable) {
    case 'current_user': {
      return plv8.execute('SELECT current_user AS val')[0].val;
   default:
      return '';
  }
}
```

in order to keep guaranteed compatibility across postgres versions.  which generally is something you'd put in a `start_proc`.

alternately, you can do the same thing by creating your own stored procedure and use `find_function`:

```
CREATE FUNCTION get_env (variable TEXT) RETURNS TEXT AS
$$
  switch (variable) {
    case 'current_user': {
      return plv8.execute('SELECT current_user AS val')[0].val;
   default:
      return '';
  }
$$ LANGUAGE plv8
```

you can even have your function cache, which would cut down the number of queries.

```
DO $$ plv8.elog(NOTICE, plv8.find_function('get_env')('current_user')); $$ LANGUAGE plv8;
```

more information on `find_function` can be found here: https://plv8.github.io/#-code-plv8-find_function-code-

**Comment by pkit** [comment]
@speller 
> But I'm using AWS RDS... 

Then you will not benefit from any new plv8 features anyway.
Essentially you need to create something for existing plv8 versions, because we don't know when/if AWS will upgrade.
The simplest solution would be to execute a startup script "manually" on each new connection to pg.
AFAIR virtually all client libraries have such an option.

**Comment by JerrySievert** [comment]
amazon tends to update minor versions fairly quickly - that said, even if a new feature *were* back ported to a minor version (bug fixes are), then it would be behind a compile-time feature flag.

**Comment by pkit** [comment]
@speller just FYI, there's a neat trick to get current user into any procedure without sacrificing security

```sql
create domain "invoker" as name check (value = current_user);
create function my_func (arg1 text, arg2 text, caller invoker default current_user) returns text as $$
  plv8.elog(NOTICE, `The caller was: ${caller}`);
  return caller;
$$ language plv8;
set role "some_role";
select my_func('a', 'b');
reset role;
```
Because the argument is a domain with check constraint it will not accept any value apart from `current_user` or `NULL` (which will be replaced by `current_user`).
