### ISSUE TITLE
parallel queries can't access plv8 global variable

### ISSUE THREAD

**Issue by tracyhenry** [plv8/plv8js#367]
I defined a function `test` that accesses a global variable`plv8.test.x`

When I run `SELECT test(tbl) from tbl`, everything is fine if the planner uses a sequential scan. However, if the planner uses a parallel scan, there will be an error saying `can't access x of undefined`

I'm guessing it's because parallel workers do not have the same context as the original connection. Is there anyway around this?

**Comment by JerrySievert** [comment]
because parallel queries use a different process altogether, there is no way to share contexts.

you might be able to stash a value in a postgres table, but that's likely suboptimal as well.

**Comment by tracyhenry** [comment]
Thanks for the quick response. Sorry for bothering but there is a related issue that I can't figure out:

`plv8.test.x` is actually a required node module using https://github.com/JerrySievert/plv8-modules

I wanted to store that in a global variable for memoization. But stepping back, if I directly do `require` inside the function, I would get a weird error from Postgres: 

```
FATAL:  RollbackAndReleaseCurrentSubTransaction: unexpected state STARTED
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

My guess is that `require` is not parallel safe (although I declared it to be). I wonder why? The postgres documentation (https://www.postgresql.org/docs/10/parallel-safety.html) does not seem to classify this as parallel unsafe though.

**Comment by JerrySievert** [comment]
if you have a reproducible example that you can share, feel free to open an issue on that repo, and I will see if I can find it and reproduce.

make sure you include which version of plv8 you're using it with.

**Comment by tracyhenry** [comment]
Hi I opened an issue in that repo: https://github.com/JerrySievert/plv8-modules/issues/6

Thanks very much for your time!
