### ISSUE TITLE
question: what's the limit of memory for a plv8 function

### ISSUE THREAD

**Issue by tracyhenry** [plv8/plv8js#374]
Inside a function, I'm storing ~200MB query results into an JS array. It seems like the performance went down as the array got bigger, but the memory usage never went up much. 

I wonder how much memory a plv8 function has, and what Postgres parameter I can tune to make it bigger?

**Comment by JerrySievert** [comment]
a `v8` (and thus `plv8`) process can consume up to about 5gb of memory.

if you're using v3.0alpha, you can see `v8`'s memory usage by executing `plv8.memory_usage()` and inspecting the results.

if you're getting a slowdown, and you're using `plv8.execute()`, likely it is the `SPI` functionality that is slowing things down, as well as the conversion from Postgres to `v8` (this is extremely expensive in `v8`).  if you expand on how you're processing the data, I can likely give you some pointers on how to speed it up.

**Comment by tracyhenry** [comment]
I'm not using plv8.execute().

I'm using `cursor.fetch()` to read in tuples from a table, testing one by one if a tuple satisfies a predicate and store it to a JS array. The selectivity of the predicate is roughly 70%. For a 1.5M-tuple table, the size is 307Mb. So roughly 200 bytes per tuple. 

For the first 300K tuples, speed was ok -- but after that there was apparent slowdown. When it got to 1.3M (and roughly 1M tuples in the array), it got stuck. After a while Postgres crashed.

**Comment by JerrySievert** [comment]
`cursor.fetch()` is using the same SPI mechanisms under the hood.

which version of plv8 are you using specifically, btw?

for each fetched row, memory is likely being held and not released.  you can see exactly how much by checking the size of the process that is executing your plv8 query.

given the number of tuples, I'd suggest that you're approaching the problem a bit backward:

I'd highly recommend inverting your logic, either test your predicate with a direct postgres query, or create a separate plv8 function that tests whether the predicate is satisfied and returns a boolean value or a transformed value.

doing this allows you to have postgres do the heavy lifting that it is designed for (let the database do database work), and allows your function to do the aggregate work.

before:

```
var plan = plv8.prepare('SELECT * FROM tbl WHERE col = $1', [ 'int' ]);
var cursor = plan.cursor([ 1 ]);
var sum = 0, row;
while (row = cursor.fetch()) {
    if (row.data.type == "addme") {
        sum += row.data.num;
    }
}
cursor.close();
plan.free();
```

after:

```
create function test_predicate(data JSONB) returns BOOLEAN AS $$
  return data.type == "addme";
$$ language plv8;
```

```
var plan = plv8.prepare('SELECT * FROM tbl WHERE col = $1 AND test_predicate(data)', [ 'int' ]);
var cursor = plan.cursor([ 1 ]);
var sum = 0, row;
while (row = cursor.fetch()) {
    sum += row.num;
}
cursor.close();
plan.free();
```

that would be a big difference in performance, and allow for you to create an index on the predicate, no matter how complex the test, provided it were immutable.

**Comment by tracyhenry** [comment]
Thanks for the detailed explanation. However I wasn't very clear -- the predicate is not separable, it requires checking other tuples. In this case each row is a rectangle, and I'm using quadtree to produce a set of non-overlapping rectangles.

That's why I'm using a function and have to store everything into a JS array. The process never used more than 1.5G as I saw in `htop`. But things were just slow.

**Comment by tracyhenry** [comment]
and btw I'm using 2.3.11

**Comment by JerrySievert** [comment]
the problem you are describing sounds like a perfect use of postgis for your predicate.

**Comment by tracyhenry** [comment]
Thanks for the suggestion. Since this is only a question and I already got the answer, I'll just close it.
