### ISSUE TITLE
Sytanx Error: Can't install plv8 extension in PostgreSQL 11

### ISSUE THREAD

**Issue by kjibran** [plv8/plv8js#378]
I am on Windows 10 (x64), and running PostgreSQL 11 (x64) server with PostGIS 3.0 at my machine.

Next, I want to install plv8 in the default postgres database. 

I downloaded plv8 from xtuple [here](http://updates.xtuple.com/updates/plv8/win/xtuple_plv8.zip) via GitHub [ticket](https://github.com/plv8/plv8/issues/220). To install plv8, I followed the on-screen instructions (Windows CMD, Run as Admin) in "install_plv8.bat". Then, from SQL Query tool in pgAdmin 4:

`Create Extension plv8;`

and get this error:

```
ERROR:  syntax error in file "path_to_/plv8.control" line 1, near token ""
SQL state: 42601
```
Could you please help to resolve this error?

Note: Strangely, I can't see any extension in pgAdmin 4 Extension dialog box's drop down list.

**Comment by JerrySievert** [comment]
you will have to get support from xtuple on their binary installation, plv8 does not provide binaries.  sorry.

**Comment by lina-bh** [comment]
for anyone finding this and looking for help, the plv8.control file in %path_to_postgres%\share\extension\ is encoded in UTF-16 instead of UTF-8/ASCII in the latest xtuple build. re-encoding it with notepad++ or whatever allows the extension to be installed
