### ISSUE TITLE
CentOS 7 (static) build guidelines

### ISSUE THREAD

**Issue by ikalafat** [plv8/plv8js#383]
Hi Jerry,

This isn't an issue per-se, more a build guideline for building PLv8 using the latest (as of writing) CentOS7 dist. 
(this is probably optional but I did it on my box - `sudo yum install epel-release && sudo yum update`)
1. Install PostgreSQL using instructions from https://www.postgresql.org/download/linux/redhat/ (12.2 as of writing). I have also installed `postgresql12-devel` and `postgresql12-contrib` packages
2. Run following commands (i did one by one)
- `yum install git`
- `yum install gcc   `
- `yum install gcc-c++`
- `yum install clang`
- `yum install llvm5.0`
- `yum install centos-release-scl-rh`
- `yum install llvm-toolset-7-llvm  `
- `yum install devtoolset-7  `
- `yum install llvm-toolset-7-clang`
- `yum install libcxx`
- `yum install libcxx-devel`

3. Download latest build of PLV8 (2.3.14 currently), unpack and enter dir
- `wget https://github.com/plv8/plv8/archive/v2.3.14.tar.gz`
- `tar -xvzf v2.3.14.tar.gz`
- `cd plv8-2.3.14`

4. Run build
- `make PG_CONFIG=/usr/pgsql-12/bin/pg_config`

5. Wait and pray to deity of your preference. (took almost an hour on my end)

6. Install
- `make PG_CONFIG=/usr/pgsql-12/bin/pg_config install`

7. Through pgadmin or psql run following:
- `create extension if not exists plv8;`
- run `DO $$ plv8.elog(NOTICE, plv8.version); $$ LANGUAGE plv8;`

8. If you get 2.3.14 as response, you're done. Otherwise, I suggest crying. 

I hope these guidelines will help someone.

**Comment by JerrySievert** [comment]
some changes to your process that I'd recommend:

> `make static PG_CONFIG=/usr/pgsql-12/bin/pg_config`

should really be:

`make PG_CONFIG=/usr/pgsql-12/bin/pg_config`

the `static` is the default.

and on your `cp` commands, a `make PG_CONFIG=/usr/pgsql-12/bin/pg_config install` is really your best bet, since you're missing the upgrade scripts in there.  that should get your correct installation paths from `pg_config` and place *all* of the files where they need to be.

**Comment by ikalafat** [comment]
Hi Jerry,

Thanks for your feedback, I've adjusted original post to reflect your comments. 

I have a question related to installing on a 2nd machine. 

What would be the best approach for reusing generated files - without need to go through same process of rebuilding the extension? 

To clarify, I'd like to have some pack which I could drop on the additional machine(s) with identical OS and then just run `create extension plv8;`

Thanks again.

**Comment by ikalafat** [comment]
For the time being, I decided to pack whole `plv8-2.3.14` folder and copy it to other machines, with installing all mentioned dependencies (without running make, just make install).

If someone thinks of better way how to pack generated files into simpler-to-reuse pack, let me know.

**Comment by pkit** [comment]
@ikalafat 
```
cd plv8-2.3.14
DESTDIR=/tmp/plv8 make install && (cd /tmp/plv8; tar cvf /tmp/plv8-2.3.14.tar.gz .)
tar tvf /tmp/plv8-2.3.14.tar.gz
```

**Comment by ikalafat** [comment]
@pkit thanks for suggestion, I'll give it a shot during this week and get back to you. Cheers!
