### ISSUE TITLE
syntax error on => 

### ISSUE THREAD

**Issue by philippe-lavoie** [plv8/plv8js#384]
I'm getting a syntax error on >, are arrow functions supported ?

```
CREATE OR REPLACE FUNCTION cookie_to_json (cookie varchar) RETURNS JSON
AS $$
var result = {}
cookie.split(";").map( (c) =>  {
	var kv = c.split('=');
	result[kv[0]] = decodeURI(kv[1])
})
return result;
$$ LANGUAGE plv8;
```

**Comment by JerrySievert** [comment]
it depends completely on which version of plv8 you are using.

old (years) versions of plv8 use old (years) versions of v8, which predate arrow functions, same as old versions of node.
