### ISSUE TITLE
CTRL+C causes segfault or kills another function

### ISSUE THREAD

**Issue by marian2015** [plv8/plv8js#385]
Hi,
I have 2 issues when press CTRL+C.

**1. issue**
CTRL+C do segfault: 

I have function, with has a internal access, and it returns more rows with JSONB data:
```
CREATE OR REPLACE FUNCTION plv8_test(i INT) RETURNS INTEGER AS $$
    var plan = plv8.prepare("SELECT '{}'::JSONB AS args FROM generate_series(1,10)");
    var rows = plan.execute();
    return i;
$$ LANGUAGE plv8;
```

Run more times, press CTRL+C to cancel query. Postgresql causes segfault.
```
postgres=# SELECT COUNT(*) FROM generate_series(0,1000000) i, plv8_test(i);
^CCancel request sent
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 73709.739 ms
```

**2. issue**
I have function, with has a internal access:
```
CREATE OR REPLACE FUNCTION plv8_pg_sleep(sec INT) RETURNS TEXT AS $$
    plv8.execute('SELECT pg_sleep($1)', [ sec ]);
    return "done";
$$ LANGUAGE plv8;
```

Press CTRL+C, function finishes after 10s, next function finishes immediately without press CTRL+C. It prints "ERROR:  null".
```
postgres=# SELECT plv8_pg_sleep(10);
^CCancel request sent
Time: 10021.597 ms (00:10.022)
postgres=# SELECT plv8_pg_sleep(10);
ERROR:  null
CONTEXT:  
Time: 0.980 ms
postgres=# 
```
OS: centos7, x86_64
Postgresql: 9.6.17, 12.2-1
PLV8: 2.3.14

regards,
Marian

**Comment by pkit** [comment]
1. Maybe you never call `plan.free()` and memory leak all the memory? Probably needs to be fixed though...
2. I think you need to implement interrupt yourself here. The ^C is not passed into plv8 as-is.
