### ISSUE TITLE
Better error message instead of "cache lookup failed for type 0"

### ISSUE THREAD

**Issue by cschwaderer** [plv8/plv8js#386]
Today, I've spent a ridiculously long time on a trivial issue: I had refactored a plv8 query and forgotten that I did not use my first parameter anymore. The message I got was `cache lookup failed for type 0`  - which means nothing to me, to be honest.
You can reproduce this error with a silly query like this

```
DO $$
    plv8.execute('SELECT $2 = $2',['foo','bar']);
$$ LANGUAGE plv8;
```

Would it possible to replace this message with something more meaningful like: `Parameter at position 0 in parameter array with value "foo" is not used in the query`?
That could save me and maybe other developers some debugging time.

I am using plv8 2.3.14 on PostgreSQL 12.2

**Comment by JerrySievert** [comment]
unfortunately, that's the error message that plv8 is getting from Postgres itself, and passes it through to you.

that's the same error message that's returned from pl/pgsql and every other program that uses pg's SPI interface.
