### ISSUE TITLE
install in debian 10.3/psql 11.7

### ISSUE THREAD

**Issue by stevesoaeris** [plv8/plv8js#387]
I seem to be able to make 2.3.14 ok in debian 10.3, psql 11.7.
However, once I try to `create extension`, it gives me this error:

ERROR:  could not load library "/usr/lib/postgresql/11/lib/plv8-2.3.14.so": /usr/lib/postgresql/11/lib/plv8-2.3.14.so: undefined symbol: _ZN2v84base12CallOnceImplEPlPFvPvES2_

Is there a specific version of plv8 I should be using?

```
postgres@responder:~/plv8-2.3.14$ python --version
Python 2.7.16
postgres@responder:~/plv8-2.3.14$ git --version
git version 2.20.1
postgres@responder:~/plv8-2.3.14$ g++ --version
g++ (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

postgres@responder:~/plv8-2.3.14$ clang++ --version
clang version 7.0.1-8 (tags/RELEASE_701/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
postgres@responder:~/plv8-2.3.14$ 
```

**Comment by JerrySievert** [comment]
how did you compile plv8, and what os/version are you using?

**Comment by stevesoaeris** [comment]
I simply did `make`, then `make install`.  It is on debian 10.3.

**Comment by JerrySievert** [comment]
can you make sure that you do not have any copies of the v8 library installed via your package manager?

**Comment by stevesoaeris** [comment]
I removed libnode-dev (virtual libv8), then `make clean, make, make install`, with no change.  
I also tried 3.0a, and I get this slightly different message: 
`ERROR:  could not load library "/usr/lib/postgresql/11/lib/plv8-3.0alpha.so": /usr/lib/postgresql/11/lib/plv8-3.0alpha.so: undefined symbol: _ZN2v84base7ieee7543powEdd
` 
I also upgraded apt packages, with no effect.  Any ideas?

**Comment by JerrySievert** [comment]
removing those fixed a large chunk of your problems (v8.h and v8.so were in your paths from those packages).

it looks like there are still a couple of artifacts (likely v8/external-reference.h).  my suggestion is to run a `find / | grep v8` and try to find what's left over in your system.  v8 does not play well with others, let alone different versions of itself.  it is not designed to be a shared library, and distributions trying to shoehorn it into a shared library cause all sorts of issues.

**Comment by JerrySievert** [comment]
note that if you had libnode-dev you likely also have libnode, which provides other shared libraries that are within your ldconfig path.  this just plain will not work with v8.  it *must* be compiled as a static resource to be usable.

**Comment by stevesoaeris** [comment]
ok that did the trick.
Removing libnode-dev, libnode, etc. fixed it.
Thanks for the help!

**Comment by stevesoaeris** [comment]
BTW, removing those libraries breaks the stable apt node package.

**Comment by JerrySievert** [comment]
yes, because node is also not supposed to be linked with a shared v8 object, which is why when you compile node yourself it links with a static built version of v8.  v8 must be embedded, because v8 versions (even minor versions number changes) are not compatible with each other, and versions of v8 that are the exact same version, compiled with different options, are not compatible with each other (as you saw).

the apt maintainers broke that when they separated out v8 into a shared library.
