### ISSUE TITLE
Is plv8 available any other way than building it myself?

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [plv8/plv8js#388]
I'm trying to get this into a docker image with postgres 12, building from the official image. Other extensions work well enough building those in the Dockerfile (pguint). 

However, plv8 is ugly. It will fail with a different error each time (and I'm not sure how or why that's possible) even though I'm using the same branch:

    ADD https://github.com/plv8/plv8/archive/master.tar.gz /usr/local/src/plv8-master.tar.gz

On one occasion it seemed to sap most of the remaining available space on the drive I was building with (a small SSD, but still) though that might be attributable to Docker itself (it'll randomly gobble the last 50gb for indiscernible reasons).

I am aware that some time ago the various linux distros stopped supporting direct install with their package managers, though I haven't been able to piece together exactly why. But does anyone else release this as the plain binary I can just drop into the image?

**Comment by neesonqk** [comment]
https://github.com/neesonqk/postgresql-12.1-plv8-2.3.14

**Comment by pkit** [comment]
Its build is pretty simple though:

```
ARG PG_MAJOR=10
ARG PG_IMAGE_VERSION=10.10
FROM postgres:${PG_IMAGE_VERSION}

ARG BRANCH="r3.0alpha"
ARG GIT_ORG="https://github.com/plv8"

RUN buildDependencies="build-essential \
    ca-certificates \
    curl \
    git \
    postgresql-server-dev-$PG_MAJOR \
    python \
    libc++-dev \
    pkg-config \
    openssh-client \
    libssl-dev" \
  && apt-get update \
  && apt-get install -y --no-install-recommends ${buildDependencies} \
  && mkdir -p /tmp/build \
  && cd /tmp/build \
  && git clone --branch "$BRANCH" "$GIT_ORG/plv8" plv8 \
  && cd plv8 \
  && make static \
  && make install
```
