### ISSUE TITLE
plv8 build fails

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [plv8/plv8js#389]
I'm trying to build this in a docker image (postgres-12). At first I interpreted the errors  that it didn't like the version of python I had installed, so in this final run uninstalled python3 and installed python2.7 hoping that might resolve the issue.

Every failure like this one consumes around 6-7 gigs of space that I don't get to reclaim until doing a docker system prune, which unfortunately causes my computer to hang for 45 minutes while it goes god knows what (small ssd). So I only get a dozen or so attempts before I have to sit it out.

Should I be attempting to install a different release of plv8 (2.3.14)? Are there additional steps that I need to perform first that I'm not doing?

It fails with the following output:

    cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
    Cloning into 'depot_tools'...
    cd build; fetch v8; cd v8; git checkout 6.4.388.40; gclient sync ; cd build/config ; git cherry-pick 4287a0d364541583a50cc91465330251460d489a ; cd ../.. ; tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
    Warning: Running gclient on Python 3. 
    If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
    WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
    Warning: Running gclient on Python 3. 
    If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.

    ________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /usr/local/src/plv8-2.3.14/build/_gclient_v8_82zuadzx' in '/usr/local/src/plv8-2.3.14/build'
    Cloning into '/usr/local/src/plv8-2.3.14/build/_gclient_v8_82zuadzx'...
    remote: Sending approximately 660.60 MiB ...        
    remote: Counting objects: 7660, done        
    remote: Total 746295 (delta 611021), reused 746295 (delta 611021)        
    Receiving objects: 100% (746295/746295), 660.60 MiB | 4.22 MiB/s, done.
    Resolving deltas: 100% (611021/611021), done.
    [0:04:38] Still working on:
    [0:04:38]   v8
    [0:07:12] Still working on:
    [0:07:12]   v8/third_party/icu
    [0:07:22] Still working on:
    [0:07:22]   v8/third_party/icu
    [0:07:32] Still working on:
    [0:07:32]   v8/third_party/icu
    [0:07:38] Still working on:
    [0:07:38]   v8/third_party/icu
    ________ running 'vpython v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/usr/local/src/plv8-2.3.14/build'
    ________ running 'vpython v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/usr/local/src/plv8-2.3.14/build'
    ________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/buildtools/linux64/clang-format...
    Downloading 1 files took 22.205562 second(s)
    Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' took 22.26 secs
    ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
    0> Extracting 473 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
    Downloading 1 files took 9.139632 second(s)
    ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-js/tests.tar.gz.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/test/wasm-js/tests.tar.gz...
    0> Extracting 111 entries from v8/test/wasm-js/tests.tar.gz to v8/test/wasm-js/tests
    Downloading 1 files took 7.532115 second(s)
    ________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/usr/local/src/plv8-2.3.14/build'
    Installing Debian sid i386 root image: /usr/local/src/plv8-2.3.14/build/v8/build/linux/debian_sid_i386-sysroot
    Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/e954fb79fcddf64bc39d721c9a5b652b6da549fa/debian_sid_i386_sysroot.tar.xz
    Hook 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x86' took 49.94 secs
    ________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/usr/local/src/plv8-2.3.14/build'
    Installing Debian sid amd64 root image: /usr/local/src/plv8-2.3.14/build/v8/build/linux/debian_sid_amd64-sysroot
    Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/79a7783607a69b6f439add567eb6fcb48877085c/debian_sid_amd64_sysroot.tar.xz
    Hook 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 18.78 secs
    ________ running 'vpython v8/third_party/binutils/download.py' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading /usr/local/src/plv8-2.3.14/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
    Downloading 1 files took 34.747540 second(s)
    Downloading /usr/local/src/plv8-2.3.14/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
    Extracting /usr/local/src/plv8-2.3.14/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
    Hook 'vpython v8/third_party/binutils/download.py' took 36.69 secs
    ________ running 'vpython v8/tools/clang/scripts/update.py' in '/usr/local/src/plv8-2.3.14/build'
    Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-n345635-5d881dd8-1.tgz .......... Done.
    Hook 'vpython v8/tools/clang/scripts/update.py' took 94.54 secs
    ________ running 'vpython v8/build/util/lastchange.py -o v8/build/util/LASTCHANGE' in '/usr/local/src/plv8-2.3.14/build'
    Warning: Running gclient on Python 3. 
    If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
    Running: gclient root
    Running: gclient config --spec 'solutions = [
      {
        "name": "v8",
        "url": "https://chromium.googlesource.com/v8/v8.git",
        "deps_file": "DEPS",
        "managed": False,
        "custom_deps": {},
      },
    ]
    '
    Running: gclient sync --with_branch_heads
    Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
    Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
    Running: git config diff.ignoreSubmodules all
    Previous HEAD position was ffb4f2b77f [mips][wasm-simd][liftoff] Implement rounding average
    HEAD is now at d481edab15 Version 6.4.388.40

    WARNING: 'v8/third_party/depot_tools' is no longer part of this client.
    It is recommended that you manually remove it or use 'gclient sync -D' next time.

    WARNING: 'v8/third_party/googletest/src' is no longer part of this client.
    It is recommended that you manually remove it or use 'gclient sync -D' next time.

    WARNING: 'v8/third_party/perfetto' is no longer part of this client.
    It is recommended that you manually remove it or use 'gclient sync -D' next time.

    WARNING: 'v8/third_party/protobuf' is no longer part of this client.
    It is recommended that you manually remove it or use 'gclient sync -D' next time.

    WARNING: 'v8/third_party/zlib' is no longer part of this client.
    It is recommended that you manually remove it or use 'gclient sync -D' next time.
    ________ running 'vpython v8/gypfiles/landmines.py' in '/usr/local/src/plv8-2.3.14/build'
    Clobbering due to:
    --- old_landmines   Sun Apr 12 22:49:39 2020
    +++ new_landmines   Sun Apr 12 22:54:33 2020
    @@ -18,18 +17,0 @@
    -Clobber to possibly resolve build failure on Misc V8 Linux gcc.
    -Builders switching from make to ninja will clobber on this.
    -Need to clobber everything due to an IDL change in r154579 (blink)
    -Need to clobber everything due to gen file moves in r175513 (Blink)
    -Clobber to get rid of obselete test plugin after r248358
    -Clobber to rebuild GN files for V8
    -Clobber to get rid of stale generated mojom.h files
    -Need to clobber everything due to build_nexe change in nacl r13424
    -[chromium-dev] PSA: clobber build needed for IDR_INSPECTOR_* compil...
    -blink_resources.grd changed: crbug.com/400860
    -ninja dependency cycle: crbug.com/408192
    -Clobber to fix missing NaCl gyp dependencies (crbug.com/427427).
    -Another clobber for missing NaCl gyp deps (crbug.com/427427).
    -Clobber to fix GN not picking up increased ID range (crbug.com/444902)
    -Remove NaCl toolchains from the output dir (crbug.com/456902)
    -CLobber all to fix GN breakage (crbug.com/736215)
    -The Great Blink mv for source files (crbug.com/768828)
    -Clobber to workaround buggy .ninja_deps cycle (crbug.com/934404)
    ________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/buildtools/linux64/clang-format...
    Downloading 1 files took 26.213156 second(s)
    Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' took 26.27 secs
    ________ running 'vpython v8/tools/gcmole/download_gcmole_tools.py' in '/usr/local/src/plv8-2.3.14/build'
    ________ running 'vpython v8/tools/jsfunfuzz/download_jsfunfuzz.py' in '/usr/local/src/plv8-2.3.14/build'
    ________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/tools/luci-go/linux64/isolate...
    Downloading 1 files took 42.530316 second(s)
    Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-luci -d v8/tools/luci-go/linux64' took 42.57 secs
    ________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/buildtools/linux64/gn...
    Downloading 1 files took 19.006224 second(s)
    Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-gn -s v8/buildtools/linux64/gn.sha1' took 19.06 secs
    ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
    0> Removed v8/test/wasm-spec-tests/tests...
    0> Extracting 65 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
    Downloading 1 files took 6.842934 second(s)
    ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading v8/src/inspector/build/closure-compiler.tar.gz...
    0> Extracting 4 entries from v8/src/inspector/build/closure-compiler.tar.gz to v8/src/inspector/build/closure-compiler
    Downloading 1 files took 26.961896 second(s)
    Hook 'download_from_google_storage --no_resume --no_auth -u --bucket chromium-v8-closure-compiler -s v8/src/inspector/build/closure-compiler.tar.gz.sha1' took 27.00 secs
    ________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/usr/local/src/plv8-2.3.14/build'
    Installing Debian Stretch amd64 root image: /usr/local/src/plv8-2.3.14/build/v8/build/linux/debian_stretch_amd64-sysroot
    Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/debian_stretch_amd64_sysroot.tar.xz
    Installing Debian Stretch i386 root image: /usr/local/src/plv8-2.3.14/build/v8/build/linux/debian_stretch_i386-sysroot
    Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/2202c161310ffde63729f29d27fe7bb24a0bc540/debian_stretch_i386_sysroot.tar.xz
    Hook 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' took 112.18 secs
    ________ running 'vpython v8/third_party/binutils/download.py' in '/usr/local/src/plv8-2.3.14/build'
    0> Downloading /usr/local/src/plv8-2.3.14/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2...
    Downloading 1 files took 7.354074 second(s)
    Downloading /usr/local/src/plv8-2.3.14/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
    Extracting /usr/local/src/plv8-2.3.14/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
    ________ running 'vpython v8/tools/clang/scripts/update.py' in '/usr/local/src/plv8-2.3.14/build'
    Updating Clang to 318667-1...
    Downloading prebuilt clang
    Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-318667-1.tgz .......... Done.
    Creating directory /usr/local/src/plv8-2.3.14/build/v8/third_party/llvm-build/Release+Asserts
    clang 318667-1 unpacked
    Hook 'vpython v8/tools/clang/scripts/update.py' took 18.90 secs
    ________ running 'vpython v8/gypfiles/gyp_v8 --running-as-hook' in '/usr/local/src/plv8-2.3.14/build'
    Updating projects from gyp files...
    Warning: Running gclient on Python 3. 
    If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
    [detached HEAD c41d50d2e] [ios] Various build fixes for Xcode 10.
     Author: Justin Cohen <justincohen@google.com>
     Date: Tue Jun 5 15:30:25 2018 +0000
     2 files changed, 36 insertions(+), 11 deletions(-)

    Hint: You can raise verbosity (-vv) to see the output of failed commands.

    Traceback (most recent call last):
      File "tools/dev/v8gen.py", line 304, in <module>
        sys.exit(gen.main())
      File "tools/dev/v8gen.py", line 298, in main
        return self._options.func()
      File "tools/dev/v8gen.py", line 166, in cmd_gen
        gn_outdir,
      File "tools/dev/v8gen.py", line 208, in _call_cmd
        stderr=subprocess.STDOUT,
      File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
    make: *** [Makefile:35: build/v8] Error 1
    The command '/bin/sh -c tar xvfz plv8-2.3.14.tar.gz && cd plv8-2.3.14                                                                              && apt-get remove -y python3                                                                   && apt-get install -y python2.7                                                                && make                                                                                        && make install' returned a non-zero code: 2

**Comment by JerrySievert** [comment]
did you make sure that you have the rest of the pre-requisites installed before you attempt to build?

https://plv8.github.io/#building

these are v8 requirements, which is a very finicky build.

**Comment by NoMoreNicksLeft** [comment]
Ok, I am apparently missing some things I assumed were in the built-essential package. I will check back if the problem persists.
