### ISSUE TITLE
plv8 3.0 alpha is production ready?

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#390]
Thank you for your great plv8.

What is the main difference between plv8 v2 and v3?
Can I use it in a production environment?

**Comment by JerrySievert** [comment]
there's no reason you can't use it in production.  what had stopped me from going full release on 3.0 was a couple of promised feature PR's that haven't shown up, and making sure that the direct jsonb conversion was solid.

there have been a lot of people trying the direct jsonb conversion from 2.1.x, some that have found bugs that have been fixed and ported forward so I feel comfortable recommending v3.

**Comment by hellower** [comment]
I will use it in a production environment.
If there is a problem, I will report a bug.
Thank you for great software again!
