### ISSUE TITLE
should use git clone --depth 1 if possible

### ISSUE THREAD

**Issue by admilazz** [plv8/plv8js#391]
The build process seems to pull the full history of the chromium tools repository, which is huge and slow. I think you should use --depth 1 to just pull the latest version and not the full history.

**Comment by admilazz** [comment]
I edited the Makefile to use --depth 1 --no-single-branch and it reduced the initial download size by 90%.

Just using --depth 1 (without --no-single-branch) may reduce it further.

EDIT: Unfortunately the bigger clone of v8 happens later.

**Comment by JerrySievert** [comment]
plv8 uses v8's build and configuration systems `gclient` and `v8-gen`, as required by v8 .  it does not do a direct `git clone`.

the only `git clone` is:

```
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
```

which checks out the aforementioned build system.

also, v8 should never be built with the latest version of v8, as the API for v8 changes between releases.

**Comment by admilazz** [comment]
Well I guess it indirectly does a clone of the v8 repository. `... running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git ...`

It would still be good if we could manage to get a --depth 1 argument in there (e.g. by running sed over their build script, if that's possible) because it reduces the initial v8 download from ~660MB to ~28MB with a similar reduction in processing time and might provide similar savings for the 28 subprojects it seems to pull. (I'm not familiar with the structure of their repository.)
