### ISSUE TITLE
Should not require a git identity to build

### ISSUE THREAD

**Issue by admilazz** [plv8/plv8js#392]
I followed the build instructions and it failed with this error:

    *** Please tell me who you are
    Run
    
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    
    to set your account's default identity.

An automated build process shouldn't need a git identity just to download and build some code. If this limitation can't be removed, it should at least be documented.

After setting those values to some dummy name and address, the build then failed immediately with:

    # make
    cat: '/usr/include/postgresql/11/server/pg_config*.h': No such file or directory
    /bin/sh: 1: test: -ge: unexpected operator
    /bin/sh: 1: test: -lt: unexpected operator
    /bin/sh: 1: test: -lt: unexpected operator
    /bin/sh: 1: test: -lt: unexpected operator
    /bin/sh: 1: test: -lt: unexpected operator
    cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
    ninja: Entering directory `out.gn/x64.release'
    ninja: fatal: chdir to 'out.gn/x64.release' - No such file or directory
    make: *** [Makefile:42: v8] Error 1

Seems like it can't resume after failure?

**Comment by JerrySievert** [comment]
the failure you are seeing is that you are missing `pg_config` in your path.

please make sure it's in your path so that postgres extensions can be built correctly.

**Comment by admilazz** [comment]
> the failure you are seeing is that you are missing `pg_config` in your path.
> 
> please make sure it's in your path so that postgres extensions can be built correctly.

It is in my path:

    # pg_config
    BINDIR = /usr/lib/postgresql/11/bin
    DOCDIR = /usr/share/doc/postgresql-doc-11
    HTMLDIR = /usr/share/doc/postgresql-doc-11
    ....

The first time I ran `make` it did a bunch of git-related stuff for 20 or so minutes before failing.

**Comment by JerrySievert** [comment]
are you sure that you have all of the build dependencies?

```
PG_VERSION_NUM := $(shell cat `$(PG_CONFIG) --includedir-server`/pg_config*.h)
```

you can run `pg_config`:

```
pg_config --includedir-server
```

and verify that Postgres's build requirements are met.

for me:

```
bash-3.2$ pg_config --includedir-server
/usr/local/pgsql/include/server
bash-3.2$ ls /usr/local/pgsql/include/server/pg_config*.h
/usr/local/pgsql/include/server/pg_config.h
/usr/local/pgsql/include/server/pg_config_ext.h
/usr/local/pgsql/include/server/pg_config_manual.h
/usr/local/pgsql/include/server/pg_config_os.h
```

**Comment by admilazz** [comment]
I'm not sure I do, although I think it's a but off-topic from requiring a git identity. The documentation says:

> Building PLV8 for MacOS or Linux has some specific requirements:
> 
> Git
> g++ or clang++
> Python 2 (for v8)
> pkg-config (linux only for v8)
> libc++-dev (linux only)
> libc++abi-dev (linux only)

So before trying to build I did `apt-get install git g++ python2 pkg-config libc++-dev libc++abi-dev`. The next step failed because `make` is also required, so I installed that.

I get:

    # pg_config --includedir-server
    /usr/include/postgresql/11/server

but there are no pg_config\*.h files there. Is there some additional dependency like postgres development headers?

**Comment by admilazz** [comment]
I installed postgresql-server-dev-11 and will retry.

**Comment by admilazz** [comment]
It ran for a long time and eventually failed with:

    ../../third_party/llvm-build/Release+Asserts/bin/clang++: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
    [6/665] CXX obj/v8_libbase/ieee754.o
    FAILED: obj/v8_libbase/ieee754.o

I guess libtinfo5 is another dependency? I already had libtinfo version 6, but I installed version 5 and it proceeded, I think.

**Comment by JerrySievert** [comment]
I have no idea which operating system or distribution you are using, so I don't have any insight into which dependencies you are missing for v8 to build, as v8 uses its own dependency management system and installs its own compiler and dependencies.

these are the dependencies that are currently known:

https://plv8.github.io/#building-for-macos-linux

you can try removing the `build` directory, just make sure that you are using the Makefile that ships with plv8, not anything changed as some dependencies may end up missing from v8's checkout and configuration.

**Comment by admilazz** [comment]
This is Debian stable (buster), from the debian:stable-slim Docker image (so it has a rather minimal set of packages), although in this case libtinfo6 was installed, but it seems the build requires the older libtinfo5. I'm just documenting these things in case you want to expand the documentation for the build process.

**Comment by admilazz** [comment]
Now it failed with:

````
...
mkdir -p upgrade
./generate_upgrade.sh 2.3.8
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plv8 - > plv8--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plcoffee - > plcoffee--2.3.8.sql
sed -e 's/@PLV8_VERSION@/2.3.8/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.3.8/g' | g++ -E -P -I. -I./ -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5 -DLANG_plls - > plls--2.3.8.sql
make: *** No rule to make target 'plv8.bc', needed by 'all'.  Stop.
````

I'm not sure what's up with that one, or even where it's coming from. Both of these return nothing:

    find | grep Makefile | xargs grep plv8.bc
    grep -RIF plv8.bc

So presumably that's a generated target... I tried to just build the .so directly via `make plv8.so` and it built. However, `make install` still fails with:

````
# make install
cd build/v8 ; env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release d8
ninja: Entering directory `out.gn/x64.release'
ninja: no work to do.
mkdir -p upgrade
./generate_upgrade.sh 2.3.8
make: *** No rule to make target 'plv8.bc', needed by 'all'.  Stop.
````

Can I just take this .so file and drop it somewhere? It's rather small so presumably it seems some supporting files...

**Comment by JerrySievert** [comment]
the postgres package that you are using requires both the .so file and the .bc file (llvm byte code for jit compiler in postgres itself), and thus all extensions that are to be compiled against your postgres package must generate them.

likely your slimmed down Debian instance is missing part of the llvm suite (llc perhaps?)

**Comment by admilazz** [comment]
> likely your slimmed down Debian instance is missing part of the llvm suite (llc perhaps?)

Thank you for the replies. llvm isn't installed by default but I can install it. (That's probably true of the non-slim Debian stable as well.) Versions 6 and 7 are available. Version 7 is presumably what I will get by default if I just install "llvm". Does the build require a particular version?

**Comment by admilazz** [comment]
Installing LLVM didn't noticeably help, but I found [this comment](https://github.com/plv8/plv8/issues/304#issuecomment-426035141) from you from some years ago. You suggested adding these lines to Makefile.shared:

    %.bc : %.cc
    	$(COMPILE.cxx.bc) $(CCFLAGS) $(CPPFLAGS) -fPIC -c -o $@ $<

The build completed after doing that, and `make install` succeeded as well.

**Comment by JerrySievert** [comment]
are you perhaps not using a recent version of plv8?

**Comment by admilazz** [comment]
> are you perhaps not using a recent version of plv8?

I followed the [build instructions](https://plv8.github.io/#building-for-macos-linux) which included this:

> Downloading the source code is very straightforward:
> ````
> $ wget https://github.com/plv8/plv8/archive/v2.3.8.tar.gz
> $ tar -xvzf v2.3.8.tar.gz
> $ cd plv8-2.3.8
> $ make
> ````

I don't know how old 2.3.8 is, though. :-)  It looks like the GitHub repository has tags going up to 2.3.14...

**Comment by cantoute** [comment]
> Le 22 avr. 2020 à 15:35, admilazz <notifications@github.com> a écrit :
> 
> I'm not sure I do, although I think it's a but off-topic from requiring a git identity.

This is normal git behavior...
It doesn't require an identity as such, git version you have installed complains if you don't have any identity and as it just does a clone to your local machine from a public repo, it doesn't communicate anything about the identity you chose.

an if you are on a *unix* environment git just wants a name

git config --global user.name "Your Name"
Will do just fine.... nothing more is needed... it'll be happy with "Any Name"
Just the day you'll want to use your local account to publish on a git repo, you'll probably want to change this to your real name.
An as was saying earlier, you could put your real name as it isn't communicated anywhere until you would be doing a 'commit' and it would be your signature to a commit, nothing more.
And from where I guess you are about coding, there is some time before you will be editing code and committing it... So on't be paranoid ;)

> This is Debian stable (buster), from the debian:stable-slim Docker image (so it has a rather minimal set of packages), although in this case libtinfo6 was installed, but it seems the build requires the older libtinfo5. I'm just documenting these things in case you want to expand the documentation for the build process.


now, make your life easier, don't try to run this on a docker debian-slim !!
That make every thing real tricky 
Perhaps you want to use virtualbox and install a proper virtual machine an install postgres from the postgres.org apt repo.

good luck

**Comment by admilazz** [comment]
Sure, it's just that setting up those git variables seems to be a "dependency" as well and should perhaps be documented. You can't just install the dependencies listed in the build instructions, run "make", and have it work.

**Comment by pkit** [comment]
It's V8 "dependencies", you cannot rely on them being stable or documented.
A lot of google-owned repos will try to download stuff from internet, change build scripts with scripts from internet and so on.
That's how it is.

**Comment by admilazz** [comment]
Fair 'nuff, although I think the makefile could preconfigure the .git/config file in the downloaded v8 repository with default, repository-local values for user.name and user.email, if that's sufficient. Or, the documentation could be updated to mention this. Or this issue could just be closed. I'm just noting that the steps in the build documentation don't _quite_ work out of the box.

**Comment by admilazz** [comment]
That said, I did note several other (off-topic) deficiencies in this thread:
* The link to the source code in the documentation (https://github.com/plv8/plv8/archive/v2.3.8.tar.gz) is outdated and it does not build.
* libtinfo5 was a required dependency that's not documented.
* postgresql-server-dev-X was a required dependency (perhaps "obvious", but also not documented)
