### ISSUE TITLE
How to use apt  on UBUNTU 20?

### ISSUE THREAD

**Issue by ppKrauss** [plv8/plv8js#394]
I am using PostgreSQL v12, and trying  `sudo apt install postgresql-10-plv8`,  `sudo apt-get install postgresql-9.3-plv8`, etc. all say *"E: Unable to locate package"*.

There are a **updated and reliable** `.deb`? For example `http://archive.ubuntu.com/ubuntu/pool/universe/p/plv8/postgresql-10-plv8_1.4.10.ds-2_amd64.deb`  is reliable?

**Comment by pkit** [comment]
Nope, `1.4.10` is too old.
The newest mainstream version is `2.3.14`

**Comment by JerrySievert** [comment]
debian maintainers made the decision to not support `v8`, and thus not support `plv8`.  you must install from source, as the `plv8` project does not distribute binaries.
