### ISSUE TITLE
Handling of INT8 (Bigint)

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#398]
Hi Jerry,

I run a query that returns a 64 bit integer (bigint) which has 20 digits. The JSON returned from the query is fine.

But how can I assign this value to a variable in JavaScript? Because JavaScript only support a number with not more than 16 digits, the 20 digits number is truncated.

Is there any PLV8 version that handles 64 bit integers like ES6 is doing?

Cheers
James

**Comment by JerrySievert** [comment]
3.0 has BigInt support.  note that it cannot be back ported to older versions due to it not being back ported to older v8 versions.

**Comment by JamesInform** [comment]
Thanks for the quick reponse!

So I will try version r3.0alpha, right?

Is there anything from your point of view that prevents r3.0alpha from being used in production? I mean there is alpha in the name ;)

**Comment by JerrySievert** [comment]
at this point, no.  it just hasn't been released for public consumption.

it was considered alpha with the new JSONB code and the BigInt code.   Both seem to be working we'll in production.

BitInt support was added Dec 9, 2018, if that helps put it into context.

**Comment by JamesInform** [comment]
Jerry,
thank you so much for your repsonse.

Many people and I are grateful that you are so dedicated to this project.

Keep up the good work!

Cheers
James

**Comment by JamesInform** [comment]
Hi Jerry,

I have built PLV8 alpha 3.0 successfully on Mac and Linux.

I am a bit confused about the handling of 64 integers. How is bitint support working?

When I run the following code the integer in still truncated as in old PLV8 version 2s. It is considering both numbers as equals although they are different:

```
do 
$$ 
  var a = 12345789012334578912; 
  var b = 12345789012334578913;
  plv8.elog(NOTICE, a.toString());
  plv8.elog(NOTICE, a==b);
  plv8.elog(NOTICE, plv8.version); 
$$ language plv8;

NOTICE:  12345789012334580000
NOTICE:  true
NOTICE:  3.0alpha
DO

```

Am I doing something wrong?

James

**Comment by JerrySievert** [comment]
it looks like you deleted your `BigInt` question.  does that mean you figured it out, or do you still need help?

for the record, `BigInt` is a different type than `Number`:

```
var a = 1234567890123456789n;
var b = 1234567890123456790n;
```

note the `n` at the end, which denotes it as a `BigInt`.  for more info, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by JamesInform** [comment]
Jerry,

thanks for your Info. Yes, I have already figured it out.

Nevertheless one finale question:
Is it possible to auto convert a number to bigint or a bigint to number? 

I am using int8 for many fields in my database and that means that I have to rewrite my code to handle bigint explicitly.

**Comment by JerrySievert** [comment]
> Is it possible to auto convert a number to bigint or a bigint to number?

well, no.  but that's a javascript thing and not a plv8 thing.  here's a pretty good writeup of `BigInt`: https://v8.dev/features/bigint

here's a note from that page:

One gotcha is that it’s not allowed to mix operations between BigInts and Numbers. This is a good thing, because any implicit coercion could lose information. Consider this example:

```
BigInt(Number.MAX_SAFE_INTEGER) + 2.5;
// → ?? 🤔
```

What should the result be? There is no good answer here. BigInts can’t represent fractions, and Numbers can’t represent BigInts beyond the safe integer limit. For that reason, mixing operations between BigInts and Numbers results in a TypeError exception.

The only exception to this rule are comparison operators such as `===` (as discussed earlier), `<`, and` >=` – because they return booleans, there is no risk of precision loss.

**Comment by JerrySievert** [comment]
> I am using int8 for many fields in my database and that means that I have to rewrite my code to handle bigint explicitly.

and that's the big gotcha.  but as I noted, that's a javascript thing not a plv8 thing.

here's the relevant parts of plv8:

https://github.com/plv8/plv8/blob/r3.0alpha/plv8_type.cc#L145-L146 (conversion from `BigInt` to `INT8`)
https://github.com/plv8/plv8/blob/r3.0alpha/plv8_type.cc#L662-L669 (conversion from `INT8` to `BigInt`)
https://github.com/plv8/plv8/blob/r3.0alpha/plv8_type.cc#L678-L686 (check for `BigInt` for `NUMERIC` and do the correct conversion)

**Comment by JamesInform** [comment]
Hi Jerry,

well sometimes you have to pay an arm and a leg.

But if you really need those extra digits, its worth it!

Btw. if the plv8.execute function had an option where I could choose between returning BigInt for int8 fields or simple Number for int8 fields, then this would be great. 

Because then I could decide based on the situation, if I need BigInt with all the drawbacks or if simple Number is sufficient.

Cheers
James

**Comment by JerrySievert** [comment]
> Btw. if the plv8.execute function had an option where I could choose between returning BigInt for int8 fields or simple Number for int8 fields, then this would be great.

well, you technically have that option already :)

you just need to *cast* in your query:

`plv8.execute('SELECT 1::NUMERIC')` vs `plv8.execute('SELECT 1::INT8')`

see https://github.com/plv8/plv8/blob/r3.0alpha/plv8_type.cc#L943-L945 for how a `NUMERIC` is handled.

**Comment by JamesInform** [comment]
Yep, I also thought about casting inside the sql statements. But I have a lot of statements coming in to a function as a parameter, where I have no idea how the sql looks like.

Would be cool to have such an option (BigInt / Numeric), ideally with a default to the old behaviour (just returning number). 

Then all my code would run out of the box without changes in PLV8 3.0.

How complex, do you think, would such an extension be?

**Comment by JerrySievert** [comment]
complex or not, I think that would open up the possibility for too many issues, both in code and people getting confused and creating actual GitHub issues.  so, I think that I'd pass on that.

you do have one more option, but I don't recommend it as it would end up with code that would only work in your own environment: https://github.com/plv8/plv8/blob/r3.0alpha/plv8_type.cc#L929-L937 - compile with `make BIGINT_GRACEFUL=1` - it's an unsupported option that checks the size of the `INT8` result and only sets it as a `BigInt` if it's larger than `INT32_MAX` or smaller than `INT32_MIN`.
