### ISSUE TITLE
plv8 added support for JSONB?

### ISSUE THREAD

**Issue by ppKrauss** [plv8/plv8js#402]
Hi, it is [an old question here](https://stackoverflow.com/a/25438305/287948), since 2014... some news?

**Comment by JerrySievert** [comment]
Plv8 has supported jsonb for many years now.

**Comment by ppKrauss** [comment]
Hi @JerrySievert , thanks the fast reply and the good news (!). I am not using plv8 at this moment, but updated [the information here](https://stackoverflow.com/a/25438305/287948). Please confirm (there or here) at that  [JSONb can be used since 2015-05-26](https://stackoverflow.com/a/25438305/287948), and was complete for it since 2019-03-23.

**Comment by JerrySievert** [comment]
JSONB support has been active and complete since April 22, 2015.
