### ISSUE TITLE
triggers do not have new/old records available for query

### ISSUE THREAD

**Issue by pkit** [plv8/plv8js#404]
Example:
```
create table t1 (id int, name text);
create table t2 (id int, name text);
create or replace view v1 as select * from t1 union all select * from t2;
create or replace function trg1() returns trigger as $$
  plv8.execute(`insert into t1 select NEW.*`);
  return NEW;
$$ language plv8;
create trigger tr1 instead of insert on v1 for each row execute procedure trg1();
insert into v1 values (1, 'a');
```
Result:
```
ERROR:  missing FROM-clause entry for table "new"
CONTEXT:  trg1() LINE 2: plv8.execute(`insert into t1 select new.*`)
```
Will pass with the following:
```
create or replace function trg1() returns trigger as $$
begin
  insert into t1 select new.*;
  return new;
end
$$ language plpgsql;
```

**Comment by pkit** [comment]
Workaround is:
```
create or replace function trg1() returns trigger as $$
  plv8.execute(`insert into t1 select * from json_populate_record(null::t1, $1)`, [NEW]);
  return NEW;
$$ language plv8;
```

But it looks pretty inefficient, making at least two needless boxing/unboxing trips (record->json, json->record)

**Comment by pkit** [comment]
Ok, looks like plv8 `DoCall()` doesn't call `SPI_register_trigger_data()` when doing the SPI connection from trigger.
Need to fix that, PR incoming, later. :)

**Comment by pkit** [comment]
Ooof, it's not helping, they do some black magic in plpgsql to parse the query in presence of these _named_ records.

**Comment by JerrySievert** [comment]
the tests seem to think that they do:

https://github.com/plv8/plv8/blob/r3.0alpha/sql/plv8.sql#L245-L257

https://github.com/plv8/plv8/blob/r3.0alpha/expected/plv8.out#L437-L473

**Comment by JerrySievert** [comment]
and yeah, named records passing automatically into queries is something I wouldn't be excited about.

**Comment by pkit** [comment]
> and yeah, named records passing automatically into queries is something I wouldn't be excited about.

That's the behavior of plpgsql
Obviously there is no problem using named records in the js context.
But they are not available in the SPI context.
And it looks like plpgsql does some additional effort to get them there...

Anyway, using `insert into t1 select * from json_populate_record(null::t1, $1), [NEW]` instead of `insert into t1 select new.*` seems pretty ugly to me.
