### ISSUE TITLE
QUESTION: what Postgres memory setting does plv8 work within?

### ISSUE THREAD

**Issue by thobrien** [plv8/plv8js#411]
I'm getting a core dump while executing a complex scalar plv8 function that accumulates minimal JS object state while iterating over a large jsonb array, and I wonder if it could be memory related (the core dump indicated corruption of shared memory). Is there a Postgres memory setting I should consider tuning?

Been staring at plv8 and hence palloc code and docs and this is the best tip I've found so far:
SPI_palloc allocates memory in the upper executor context.
https://www.postgresql.org/docs/11/spi-spi-palloc.html

It's worth noting this is a pure function and has no side effects.

Thanks!

**Comment by JerrySievert** [comment]
which version of plv8 are you running, and can you provide an example?

**Comment by thobrien** [comment]
Wow - super fast reply - thanks @JerrySievert!  Let me try to iterate an answer quickly as well.

AWS RDS Postgres 11, docs say plv8 2.3.?? (8?). Is there a way I can check this via psql? 

The function iterates over JavaScript arrays, which per-row are anywhere from 0-15k elements long (mean size of 230), with a probable size of around 1k per event (guessing). It accumulates data that grows with the number of elements and dedupes as it goes using a JS Object/map (nested maps). And then after it reaches the end of the array for that row, it iterates its state and dumps it back to Postgres via a loop over the keys and nested keys into rows that are about 1 KB. 

If needed, I can try to gather some statistics on the final output at smaller sizes to estimate better tomorrow.  Anyways - the simple question is what memory config for postgres constrains the memory from plv8?  work_mem?

When 

And the DB doesn't crash when I ask it to process less rows.

**Comment by JerrySievert** [comment]
yup, older versions of plv8 did a very memory heavy conversion from jsonb - long since improved.  can't help aws move to a modern version.

**Comment by thobrien** [comment]
Gotcha so I should be looking to see if I'm exceeding work_mem then? And meanwhile push the AWS support guys I'm working with to get on with a later version?

**Comment by JerrySievert** [comment]
a later version or to compile with the newer jsonb conversion (I say newer, but I mean 2 years ago).  it's simply a compile time option.

**Comment by thobrien** [comment]
Thanks Jerry. I've got to admit plv8 is pretty sweet! Thanks for the quick turn on my question and all your contributions.

**Comment by thobrien** [comment]
So it looks like I was wrong and AWS is on plv8 2.3.14 for postgres 11 (their docs are out of date) according to SELECT plv8_version(). I checked the code for 2.3.14 here, as well as various commit histories here, and it looks like JSONB_DIRECT_CONVERSION is the flag you mean, and as far as I can tell it was added in 2.3.11 but the flag is not switched on by default right? Is there any reason why not? Thank you!

**Comment by JerrySievert** [comment]
there's always a reason.  in this case, it was an experimental feature that had the possibility of breaking live code - it was released as part of 3.0alpha, and back ported as a feature flag to 2.3 versions.

it's now a solid feature, but since it is a major change, it does not belong in a minor patch version except as a feature flag at compile time.

**Comment by thobrien** [comment]
Yep makes total sense - thank you!

**Comment by thobrien** [comment]
I made a build with `make JSONB_DIRECT_CONVERSION=1` and tested it under a hand-rolled EC2 install of postgress 11, and it worked. I'm following up with AWS team to see if they can move Aurora to use JSONB_DIRECT_CONVERSION, it may be that they reach out to you as well.

Thanks for the guidance!

**Comment by JerrySievert** [comment]
I doubt they'd be willing to make a system wide change like that for reasons I mentioned before, but good luck!

**Comment by thobrien** [comment]
Since I shared this thread with Amazon and they are looking into our case - would you recommend that they switch to using JSONB_DIRECT_CONVERSION on 2.3.15, Jerry?

**Comment by JerrySievert** [comment]
no.  I'd suggest that they follow the upgrade process like they are doing.

**Comment by thobrien** [comment]
Just to clarify does that mean wait for 3.0?

**Comment by JerrySievert** [comment]
or use the 3.0 branch as-is.  direct conversion is not supported in 2.3, if someone else wants to spend the time and money to support it, they can, but I don't have the resources of amazon to do that type of support.

**Comment by thobrien** [comment]
Makes total sense. And I know you're a volunteer army - is there any guidance the team here has on when 3.0 might possibly come? If not, I totally understand.

**Comment by JerrySievert** [comment]
see https://github.com/plv8/plv8/issues/364

**Comment by thobrien** [comment]
Thanks - yeah I read through that long and interesting thread the other night - seems like PRs have slowed since then, so I think my takeaway is that when that gets resolved then 3.0 can move forward.

**Comment by thobrien** [comment]
Thanks a bunch. Glad to be communicating with a great person like yourself.
