### ISSUE TITLE
Building for ARM

### ISSUE THREAD

**Issue by inian** [plv8/plv8js#413]
Hi, I am trying to get plv8 to build on ARM. With some changes, I was able to get v8 to build on ARM. `make` and `make install` seems to work too. But when I enable the extension on database, I get the following error. 

```
Query 1 ERROR: ERROR:  could not load library "/usr/lib/postgresql/12/lib/plv8-3.0alpha.so": /usr/lib/postgresql/12/lib/plv8-3.0alpha.so: undefined symbol: _ZN6icu_638ByteSinkD2Ev
```

Any help on getting this to work would be appreciated! With ARM growing in popularity, having official build instructions for ARM would help a lot.

**Comment by JerrySievert** [comment]
`c++filt` tells me that the undefined symbol is `icu_63::ByteSink::~ByteSink()`

it's possible that you have a different version of icu installed than what v8 is being built with, or you might try disabling icu for the v8 build.  can you expand on which arm platform and which arm os you're using?

**Comment by inian** [comment]
I am trying to build it with a AWS Graviton instance running Ubuntu 18.04.
```
> uname -a
Linux ip-xx 5.4.0-1029-aws #30~18.04.1-Ubuntu SMP Tue Oct 20 11:08:38 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

ICU support is [disabled by default](https://github.com/plv8/plv8/blob/650340187526aaf7160e62973fa930954379214b/Makefile#L22) right?

**Comment by JerrySievert** [comment]
it is disabled by default, but v8 is apparently trying to link it in regardless.

I can set up a pi 3b and try to build, but do not currently have any graviton instances available to me.

**Comment by inian** [comment]
Hey thanks for the tip, I got it working now :) Turns out I hadn't disabled ICU support properly. 

I can submit a patch for making plv8 work on ARM if you are interested, but it pretty brittle. I used [this code](https://github.com/sqreen/PyMiniRacer/blob/4e4d0731a74e6f7a0a55186fb5078ae90b06e19a/build_linux_arm64.sh) here as a starting point to get v8 to compile on ARM.

**Comment by JerrySievert** [comment]
hm. 3b is 32bit.  I can only advise, not attempt the build myself.

**Comment by JerrySievert** [comment]
sure, I'd love to see a PR - there is already some code for detecting arm that could be augmented.
