### ISSUE TITLE
polymorphic function fails when given table type as input param

### ISSUE THREAD

**Issue by kavi-saralweb** [plv8/plv8js#433]
Please consider the two functions below, one written with plv8 and the other with plpgsql. The plv8 function seems to ignore the table_type argument passed by casting null::<tablename>. The parameter is seen as a plain js null in the function.

Is there an alternative way to pass a table type to plv8 functions using anyelement ?

repro code snippet below
-----------------------------------

create table test_table(id int, name text);
insert into test_table (id, name) values (1, 'one');
insert into test_table (id, name) values (2, 'two');

create or replace function test_polyfunc_plpgsql (tbl anyelement) returns setof anyelement AS
$func$
begin
return query execute 'select * from ' || pg_typeof(tbl);
end
$func$  LANGUAGE plpgsql;

create or replace function test_polyfunc_plv8 (tbl anyelement) returns setof anyelement as
$$
  /* debug messages */
  plv8.elog(NOTICE, 'in param table: ', tbl);
  var ttype = plv8.execute('select pg_typeof($1) as ttype', [tbl])[0].ttype;
  plv8.elog(NOTICE, 'tname = ', ttype);

  /* actual equivalent command */
  var cmd  =  'select * from pg_typeof($1)';
  var result = plv8.execute (cmd, [tbl]);
  plv8.elog(NOTICE, JSON.stringify(result));
  return result;
$$
language "plv8";

-- works
select * from test_polyfunc_plpgsql(null::test_table);

-- fails
select * from test_polyfunc_plv8(null::test_table);

**Comment by kavi-saralweb** [comment]
plv8_version 
--------------
 3.0alpha

**Comment by kavi-saralweb** [comment]
psql (PostgreSQL) 13.2

**Comment by JerrySievert** [comment]
plv8 converts to javascript types, it does not include any additional metadata.

so, when passing in null, it converts it to javascript native null, and when passing in an actual table, it will convert it to an object.  but, null is "special" in javascript and plv8 will not overwrite core javascript functionality.

I'd be interested to see if this works in any other pl other than plpgsql (my testing so far shows it will not, since plpgsql is the only extension that deals directly with Postgres types without converting them to a local language representation.

**Comment by kavi-saralweb** [comment]
ok thx; will do some checking on other language extensions and see how things work out.

I wonder if just making the type information (metadata) available to the plv8 code is possible. That would unblock at least this scenario. No doubt the type information is of no use to js code since it doesn't support anything other than a plain null, but the type information is quite valuable when used within SQL strings composed by the plv8 code.

**Comment by JerrySievert** [comment]
anything is possible, given enough effort, but it would be what would appear to be very little gain for quite a lot of work.

I will note that the reason why it took me so long to respond was that I was spinning up vm's with postgres and multiple language extensions to see if it was something that was addressed in any other extension.

**Comment by kavi-saralweb** [comment]
all right then, thx for confirming and explaining the issue. Even that helps a lot!
