### ISSUE TITLE
Is it possible to disable automap for the date type into js Date?

### ISSUE THREAD

**Issue by neemah** [plv8/plv8js#435]
The reason is pg date is just 'YYYY-MM-DD', and the js date has time and zone along with a date. So basically conversion creates an additional task for a developer:
1. convert a value back to date
2. be sure TZ is treated correctly on the plv8 side and in application

The current workaround:
1. cast date to varchar in queries (which is obviously ugly)
2. alter column type to char(10) (which is not so ugly, but still)

Any thought on the subject?

p.s.: Great project, love it!

**Comment by JerrySievert** [comment]
the only way to override is to use casting, like you noted:

```
SELECT TO_CHAR(NOW(), 'YYYY-MM-DD')
```

or

```
SELECT DATE_TRUNC('day', NOW())::VARCHAR
```

(for instance).

once you're in a javascript date object, you do have access to all sorts of conversions:

```
CREATE FUNCTION date_test(d DATE) RETURNS VOID AS
$$
  plv8.elog(NOTICE, d, d.toDateString(), d.toLocaleDateString());
$$ LANGUAGE plv8;
```

where you can use the getUTC functions, which should handle conversion for you.  remember, when using Postgres's `DATE` type, you do not have access to any timezone information.

or perhaps there is something I'm missing?  tell me what you're trying to accomplish in the end, and maybe I can provide you a better solution.

**Comment by JerrySievert** [comment]
closing - feel free to open back up if you have more questions
