### ISSUE TITLE
v3.0.0 fails to build for ARM instances

### ISSUE THREAD

**Issue by dragarcia** [plv8/plv8js#444]
### Instance used
- AWS r6g.2xlarge
- Ubuntu 20.04 LTS

### Replication
1. Ensure PostgreSQL is installed beforehand.
2. `apt install build-essential ca-certificates curl git-core gpp cpp pkg-config apt-transport-https cmake libc++-dev libc++abi-dev libc++1 libglib2.0-dev libtinfo5 libc++abi1 ninja-build python`
3. `git clone https://github.com/plv8/plv8.git`
4. `cd plv8 && git checkout v3.0.0` 
5. `make`
6. `make install`

Step 6) `make` eventually returns an error `clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'`
![image](https://user-images.githubusercontent.com/26374889/121529418-f6a13b00-ca2e-11eb-9f3b-69367ccd87c9.png)

### Analysis
[Changes made to the Makefile](https://github.com/plv8/plv8/commit/977712aa6751c83738f92f82438607e903927e88#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) in this [commit](https://github.com/plv8/plv8/commit/977712aa6751c83738f92f82438607e903927e88) could have most likely affected the build configuration for ARM instances. Building on the [commit beforehand](https://github.com/plv8/plv8/commit/3656177d384e3e02b74faa8e2931600f3690ab59) works as expected.

### Temporary Solution
Reverted back to 3.0.alpha for the time being by building from a [commit prior to the above commit](https://github.com/plv8/plv8/commit/3656177d384e3e02b74faa8e2931600f3690ab59). This worked as per normal.

**Comment by JerrySievert** [comment]
hm. I have it building on 64bit arm right now.

but, I have a few more 64bit arm devices that I'm connecting at the end of the week, which I will test and get added to CI.

but, yes, that commit included changing the version of v8, which has its own compatibility issue - it should have just continued fine on all arm platforms, but I'll try to figure out why it's failing on that one.  chances are it's a compiler update that will fix it if it's due to the update.

**Comment by JerrySievert** [comment]
would you be willing to give https://github.com/jerrysievert/plv8/tree/v3.0.1 a try and see if that solves your problems?

I updated clang and added a `werror=false` directive.  if this fixes you, then I'll merge.  will also have an aarch64 version out as soon as I can.

**Comment by dragarcia** [comment]
Just tried https://github.com/jerrysievert/plv8/tree/v3.0.1 with the same configuration and steps as mentioned above. Another error popped up unfortunately. Here's the entire log:

![image](https://user-images.githubusercontent.com/26374889/124062029-98caa680-da62-11eb-8ab7-9b962d50b853.png)
![image](https://user-images.githubusercontent.com/26374889/124062073-ad0ea380-da62-11eb-8424-d7f6320fa961.png)

Not sure but it might have failed at:
```
________ running 'cipd ensure -log-level error -root /home/ubuntu/plv8/build -ensure-file /tmp/tmpgh7vnii9.ensure' in '.'
Errors:
  failed to resolve infra/tools/luci/isolate/linux-arm64@git_revision:ede472114f4e51eaa068cd84cadcf470773f19ef (line 7): no such tag
  failed to resolve infra/tools/luci/isolated/linux-arm64@git_revision:ede472114f4e51eaa068cd84cadcf470773f19ef (line 8): no such tag
  failed to resolve infra/tools/luci/swarming/linux-arm64@git_revision:ede472114f4e51eaa068cd84cadcf470773f19ef (line 9): no such tag
Error: Command 'cipd ensure -log-level error -root /home/ubuntu/plv8/build -ensure-file /tmp/tmpgh7vnii9.ensure' returned non-zero exit status 1
Errors:
  failed to resolve infra/tools/luci/isolate/linux-arm64@git_revision:ede472114f4e51eaa068cd84cadcf470773f19ef (line 7): no such tag
  failed to resolve infra/tools/luci/isolated/linux-arm64@git_revision:ede472114f4e51eaa068cd84cadcf470773f19ef (line 8): no such tag
  failed to resolve infra/tools/luci/swarming/linux-arm64@git_revision:ede472114f4e51eaa068cd84cadcf470773f19ef (line 9): no such tag

Subprocess failed with return code 1.
```

**Comment by AntonioAngelino** [comment]
Hi there,

Do you have any news about the Apple Silicon compatibility?

**Comment by JerrySievert** [comment]
I have an m1, what I haven't had is the time I need.  once I gather the time, it should be solved.

but, as usual, PR's are welcome.

**Comment by maparent** [comment]
https://github.com/plv8/plv8/issues/460#issuecomment-949606354 may be relevant here as well.

**Comment by PanchoutNathan** [comment]
Hey @JerrySievert  ! 

I have the exact same problem trying to put PLV8 on a docker postgres. I have a Mac M1 Pro. Either an ARM64.

Any updates ? Solution ? Temporary solution ? Thx in advance !

**Comment by JerrySievert** [comment]
I've been working on an updated version which replaces v8's build system (or at least the configuration and downloading of things before the build).

unfortunately, this takes time, which I've been short on.  I have it building cleanly on 2 architectures, but only one platform so far.

I hope to find more time this weekend.

**Comment by PanchoutNathan** [comment]
Thx a lot @JerrySievert ! And thank you for the short response time! It's nice ;) 

I wish you good luck !! Can you ping this ticket when it's ready? Thx !

**Comment by JerrySievert** [comment]
you're welcome to try https://github.com/JerrySievert/plv8 and check out the `v3.1` branch.  I still have some work to do before a release, but locally I have it compiling for:

* macOS - Catalina through Monterey, x64 and aarch64
* ubuntu - x64 and aarch64

note the toolchain requirements, they're in the readme.

build time on macOS should be faster - I built v8 around 40 times over the weekend.

**Comment by PanchoutNathan** [comment]
Thx @JerrySievert, i try this week for sur ! 

Little question : from which version of postgres is v3 compatible?

**Comment by JerrySievert** [comment]
> Little question : from which version of postgres is v3 compatible?

same as all of the others, 9.6+

there were no significant changes from 13 to 14 to need any plv8 changes for compatibility, and plv8 has checks for versions and code branches when there are breaking changes.

**Comment by dragarcia** [comment]
> you're welcome to try https://github.com/JerrySievert/plv8 and check out the `v3.1` branch. I still have some work to do before a release, but locally I have it compiling for:
> 
> * macOS - Catalina through Monterey, x64 and aarch64
> * ubuntu - x64 and aarch64
> 
> note the toolchain requirements, they're in the readme.
> 
> build time on macOS should be faster - I built v8 around 40 times over the weekend.

![image](https://user-images.githubusercontent.com/26374889/141405573-bc46bf30-426b-4796-bd66-84339fde5cf9.png)

Happy to report that this version works on the following instance:
- AWS r6g.2xlarge
- Ubuntu 20.04 LTS
- Postgres 14

Just to confirm, do we still need to do `make & make install`? Running `make` beforehand caused `make install` to complain with the following:
```shell
make -f Makefiles/Makefile.linux
make[1]: Entering directory '/tmp/plv8'
Setting up build directory
Downloading LLVM
Downloading gn source
fatal: destination path 'build/gn' already exists and is not an empty directory.
make[1]: *** [Makefiles/Makefile.linux:25: v8] Error 128
make[1]: Leaving directory '/tmp/plv8'
make: *** [Makefile:58: v8] Error 2
```
Instead, running `make install` was sufficient.


As such, these were the steps done to get things running on the above configuration:
1. Ensure PostgreSQL is installed beforehand.
2. `apt install build-essential ca-certificates curl git-core gpp cpp pkg-config apt-transport-https cmake libc++-dev libc++abi-dev libc++1 libglib2.0-dev libtinfo5 libc++abi1 ninja-build python3 clang-11`
3. `git clone https://github.com/JerrySievert/plv8`
4. `cd plv8 && git checkout v3.1` 
5. ~~`make`~~
6. `make install`

Thanks @JerrySievert!

**Comment by JerrySievert** [comment]
glad to hear that!  thanks for the report!

I'm still in process of rewriting the Makefile, and have one test failing that I need to fix.  I'm hoping to get some time in this weekend, but can't promise anything.

once this issue, and building for windows with msvc are fixed, I will release 3.1.

**Comment by alexeyfadeev** [comment]
@dragarcia look at [our docker images with Postgres/PLV8](https://hub.docker.com/r/sibedge/postgres-plv8)
Last versions support arm64 arch.
There are links to Dockerfiles in image overview.

**Comment by kevinmccarthy** [comment]
> @dragarcia look at [our docker images with Postgres/PLV8](https://hub.docker.com/r/sibedge/postgres-plv8) Last versions support arm64 arch. There are links to Dockerfiles in image overview.

I got a segfault on that docker image running a PLv8 upsert. Happy to provide a debug if you let me know what you would like to see. 

`2022-12-12 20:47:42.148 UTC [1] LOG:  server process (PID 1410) was terminated by signal 11: Segmentation fault`

**Comment by alexeyfadeev** [comment]
@kevinmccarthy , please write us to this email: [plv8@sibedge.com](mailto:plv8@sibedge.com)
