### ISSUE TITLE
git clone source compile error (debian10/ubuntu20/centos7)

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#445]
debian10 
plv8 3.0 compile good 
plv8 clone error occurred!

CONTAINER$ git clone https://github.com/plv8/plv8.git
Cloning into 'plv8'...
remote: Enumerating objects: 2301, done.
remote: Counting objects: 100% (204/204), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 2301 (delta 119), reused 112 (delta 60), pack-reused 2097
Receiving objects: 100% (2301/2301), 9.66 MiB | 1.63 MiB/s, done.
Resolving deltas: 100% (1518/1518), done.
(postgres@tnt-factory:/usr/postgres/src)

CONTAINER$ cd plv8/
(postgres@tnt-factory:/usr/postgres/src/plv8)
CONTAINER$ make EXECUTION_TIMEOUT=1 JSONB_DIRECT_CONVERSION=1;make install
mkdir -p build
cd build \
&& git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 39.43 MiB ...
remote: Total 43948 (delta 29669), reused 43948 (delta 29669)
Receiving objects: 100% (43948/43948), 39.27 MiB | 29.46 MiB/s, done.
Resolving deltas: 100% (29669/29669), done.
cd build \
&& fetch v8 \
&& cd v8 \
&& git checkout 8.8.278.14 \
&& gclient sync \
&& git apply ../../patches/*.patch \
&& tools/dev/v8gen.py x64.release -- use_custom_libcxx=false v8_monolithic=true v8_use_external_startup_data=false is_component_build=false is_debug=true v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /usr/postgres/src/plv8/build/_gclient_v8_csvv1wni' in '/usr/postgres/src/plv8/build'
Cloning into '/usr/postgres/src/plv8/build/_gclient_v8_csvv1wni'...
remote: Sending approximately 642.13 MiB ...
remote: Counting objects: 7709, done
remote: Finding sources: 100% (49/49)
remote: Total 857728 (delta 726158), reused 857716 (delta 726158)
Receiving objects: 100% (857728/857728), 642.22 MiB | 31.74 MiB/s, done.
Resolving deltas: 100% (726158/726158), done.

[0:01:50] Still working on:
[0:01:50]   v8
1>Syncing projects:   0% ( 0/ 2) 
[0:01:54] Still working on:
[0:01:54]   v8
Syncing projects: 100% (30/30), done.                                                
Hook 'vpython third_party/depot_tools/update_depot_tools_toggle.py --disable' took 10.21 secs
Running hooks:  21% ( 6/28) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' in '/usr/postgres/src/plv8/build/v8'
0> Downloading buildtools/linux64/clang-format@904e70f14e6e2681c58ca944659afe1c482fa9a9...
Downloading 1 files took 15.360914 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' took 15.43 secs
Running hooks:  32% ( 9/28) wasm_spec_tests   
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' in '/usr/postgres/src/plv8/build/v8'
0> Downloading test/wasm-spec-tests/tests.tar.gz@0339bc2856edf7b048ad47da426dc6622f092043...
0> Extracting 382 entries from test/wasm-spec-tests/tests.tar.gz to test/wasm-spec-tests/tests
Downloading 1 files took 10.082249 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' took 10.15 secs
Running hooks:  35% (10/28) wasm_js        
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-js/tests.tar.gz.sha1' in '/usr/postgres/src/plv8/build/v8'
0> Downloading test/wasm-js/tests.tar.gz@d9c96f6f2ee2f557cd19483190b9d8743783c97e...
0> Extracting 113 entries from test/wasm-js/tests.tar.gz to test/wasm-js/tests
Downloading 1 files took 9.518164 second(s)
Running hooks:  46% (13/28) sysroot_x86  
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/usr/postgres/src/plv8/build/v8'
Installing Debian sid i386 root image: /usr/postgres/src/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/d53a049af5961f2f121ee4e149918097c193f8ed/debian_sid_i386_sysroot.tar.xz
Running hooks:  50% (14/28) sysroot_x64
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/usr/postgres/src/plv8/build/v8'
Installing Debian sid amd64 root image: /usr/postgres/src/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/43a87bbebccad99325fdcf34166295b121ee15c7/debian_sid_amd64_sysroot.tar.xz
Running hooks:  71% (20/28) clang               
________ running 'vpython tools/clang/scripts/update.py' in '/usr/postgres/src/plv8/build/v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-13-init-14086-ge1b8fde1-1.tgz .......... Done.
Running hooks: 100% (28/28), done.                        
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Previous HEAD position was 63b673b57f [test] Disable fast API tests with stress_snapshot
HEAD is now at e71858f7a0 Version 8.8.278.14
Syncing projects: 100% (28/28), done.                                                

WARNING: 'v8/third_party/google_benchmark/src' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/logdog/logdog' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.
Running hooks:  18% ( 5/27) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' in '/usr/postgres/src/plv8/build/v8'
0> Downloading buildtools/linux64/clang-format@1baf0089e895c989a311b6a38ed94d0e8be4c0a7...
Downloading 1 files took 8.615255 second(s)
Running hooks:  29% ( 8/27) wasm_spec_tests   
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' in '/usr/postgres/src/plv8/build/v8'
0> Downloading test/wasm-spec-tests/tests.tar.gz@a58223f93f7c7489abd950f322f970caac3c2cad...
0> Removed test/wasm-spec-tests/tests...
0> Extracting 461 entries from test/wasm-spec-tests/tests.tar.gz to test/wasm-spec-tests/tests
Downloading 1 files took 9.278633 second(s)
Running hooks:  33% ( 9/27) wasm_js        
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-js/tests.tar.gz.sha1' in '/usr/postgres/src/plv8/build/v8'
0> Downloading test/wasm-js/tests.tar.gz@331d0b45c9b1fe5872b5b27a7eff2c889cecb495...
0> Removed test/wasm-js/tests...
0> Extracting 144 entries from test/wasm-js/tests.tar.gz to test/wasm-js/tests
Downloading 1 files took 8.609692 second(s)
Running hooks:  44% (12/27) sysroot_x86  
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/usr/postgres/src/plv8/build/v8'
Installing Debian sid i386 root image: /usr/postgres/src/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/d967bcef40477dbc39acef141ff22bf73f3e7cdb/debian_sid_i386_sysroot.tar.xz
Running hooks:  48% (13/27) sysroot_x64
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/usr/postgres/src/plv8/build/v8'
Installing Debian sid amd64 root image: /usr/postgres/src/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/5f64b417e1018dcf8fcc81dc2714e0f264b9b911/debian_sid_amd64_sysroot.tar.xz
Running hooks:  66% (18/27) binutils            
________ running 'vpython third_party/binutils/download.py' in '/usr/postgres/src/plv8/build/v8'
Downloading /usr/postgres/src/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
0> Downloading /usr/postgres/src/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2@69bedb1192a03126687f75cb6cf1717758a1a59f...
Downloading 1 files took 9.141559 second(s)
Extracting /usr/postgres/src/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Hook 'vpython third_party/binutils/download.py' took 10.86 secs
Running hooks:  70% (19/27) clang   
________ running 'vpython tools/clang/scripts/update.py' in '/usr/postgres/src/plv8/build/v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz .......... Done.
Running hooks: 100% (27/27), done.                        
error: can't open patch '../../patches/*.patch': No such file or directory
make: *** [Makefile:112: build/v8] Error 128
cd build/v8 \
&& env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release v8_monolith
ninja: Entering directory `out.gn/x64.release'
ninja: fatal: chdir to 'out.gn/x64.release' - No such file or directory
make: *** [Makefile:126: v8] Error 1

**Comment by JerrySievert** [comment]
can you verify your python version, `rm -rf build` and retry?

**Comment by hellower** [comment]
#####
root@tnt-factory:/# python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@tnt-factory:/# python3
Python 3.9.5 (default, Jun 21 2021, 00:11:25) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
root@tnt-factory:/# 

#####
rm -rf build and retry  --> same error

**Comment by hellower** [comment]
I tried compiling on another linux distributions.  all same error

debian 10/ ubuntu 20/ centos 7 - plv8 3.0.0. compile good
***debian10/ ubuntu20/ centos 7 - all same error  on lastest plv8 source**

**####################### CENTOS 7 ########################**
PG93:5449[postgres@tnt-cen7-osc:/usr/local/src/plv8]
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
............
PG93:5449[postgres@tnt-cen7-osc:/usr/local/src/plv8]

PG93:5449[postgres@tnt-cen7-osc:/usr/local/src/plv8]
$ make EXECUTION_TIMEOUT=1 JSONB_DIRECT_CONVERSION=1;make install
mkdir -p build
cd build \
&& git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 39.50 MiB ...
remote: Counting objects: 35, done
remote: Finding sources: 100% (35/35)
remote: Total 44198 (delta 29827), reused 44196 (delta 29827)
Receiving objects: 100% (44198/44198), 39.51 MiB | 30.00 MiB/s, done.
Resolving deltas: 100% (29827/29827), done.
cd build \
&& fetch v8 \
&& cd v8 \
&& git checkout 8.8.278.14 \
&& gclient sync \
&& git apply ../../patches/*.patch \
&& tools/dev/v8gen.py x64.release -- use_custom_libcxx=false v8_monolithic=true v8_use_external_startup_data=false is_component_build=false is_debug=true v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /usr/local/src/plv8/build/_gclient_v8_jlmthzmn' in '/usr/local/src/plv8/build'
Cloning into '/usr/local/src/plv8/build/_gclient_v8_jlmthzmn'...
remote: Sending approximately 642.36 MiB ...
remote: Counting objects: 7664, done
remote: Finding sources: 100% (4/4)
remote: Total 857980 (delta 726368), reused 857977 (delta 726368)
Receiving objects: 100% (857980/857980), 642.32 MiB | 31.84 MiB/s, done.
Resolving deltas: 100% (726368/726368), done.

[0:02:00] Still working on:
[0:02:00]   v8
1>Syncing projects:   0% ( 0/ 2) 
[0:02:04] Still working on:
[0:02:04]   v8
Syncing projects: 100% (30/30), done.                                                
Hook 'vpython third_party/depot_tools/update_depot_tools_toggle.py --disable' took 11.55 secs
Running hooks:  21% ( 6/28) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' in '/usr/local/src/plv8/build/v8'
/usr/local/src/plv8/build/depot_tools/download_from_google_storage: line 8: exec: python3: not found
Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' returned non-zero exit status 127 in /usr/local/src/plv8/build/v8
/usr/local/src/plv8/build/depot_tools/download_from_google_storage: line 8: exec: python3: not found

Subprocess failed with return code 2.
make: *** [build/v8] Error 2
cd build/v8 \
&& env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release v8_monolith
ninja: Entering directory `out.gn/x64.release'
ninja: fatal: chdir to 'out.gn/x64.release' - No such file or directory
make: *** [v8] Error 1
PG93:5449[postgres@tnt-cen7-osc:/usr/local/src/plv8]

**####################### UBUNTU 20  ########################**
__STAGE__# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
..........
PG93:5432[postgres@tnt-ubu-multidb:/usr/local/src/plv8]
$ make EXECUTION_TIMEOUT=1 JSONB_DIRECT_CONVERSION=1;make install
mkdir -p build
cd build \
&& git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 39.50 MiB ...
remote: Counting objects: 35, done
remote: Finding sources: 100% (35/35)
remote: Total 44198 (delta 29827), reused 44196 (delta 29827)
Receiving objects: 100% (44198/44198), 39.51 MiB | 26.27 MiB/s, done.
Resolving deltas: 100% (29827/29827), done.
cd build \
&& fetch v8 \
&& cd v8 \
&& git checkout 8.8.278.14 \
&& gclient sync \
&& git apply ../../patches/*.patch \
&& tools/dev/v8gen.py x64.release -- use_custom_libcxx=false v8_monolithic=true v8_use_external_startup_data=false is_component_build=false is_debug=true v8_enable_i18n_support=false
Running: gclient root
WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.
Running: gclient config --spec 'solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /usr/local/src/plv8/build/_gclient_v8_za1hbs40' in '/usr/local/src/plv8/build'
Cloning into '/usr/local/src/plv8/build/_gclient_v8_za1hbs40'...
remote: Sending approximately 642.36 MiB ...
remote: Counting objects: 7664, done
remote: Finding sources: 100% (4/4)
remote: Total 857980 (delta 726368), reused 857977 (delta 726368)
Receiving objects: 100% (857980/857980), 642.32 MiB | 26.33 MiB/s, done.
Resolving deltas: 100% (726368/726368), done.

[0:02:20] Still working on:
[0:02:20]   v8
1>Syncing projects:   0% ( 0/ 2) 
[0:02:25] Still working on:
[0:02:25]   v8
Syncing projects: 100% (30/30), done.                                                
Running hooks:  21% ( 6/28) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' in '/usr/local/src/plv8/build/v8'
0> Downloading buildtools/linux64/clang-format@904e70f14e6e2681c58ca944659afe1c482fa9a9...
Downloading 1 files took 13.163437 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' took 13.27 secs
Running hooks:  32% ( 9/28) wasm_spec_tests   
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' in '/usr/local/src/plv8/build/v8'
0> Downloading test/wasm-spec-tests/tests.tar.gz@0339bc2856edf7b048ad47da426dc6622f092043...
0> Extracting 382 entries from test/wasm-spec-tests/tests.tar.gz to test/wasm-spec-tests/tests
Downloading 1 files took 13.970643 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' took 14.05 secs
Running hooks:  35% (10/28) wasm_js        
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-js/tests.tar.gz.sha1' in '/usr/local/src/plv8/build/v8'
0> Downloading test/wasm-js/tests.tar.gz@d9c96f6f2ee2f557cd19483190b9d8743783c97e...
0> Extracting 113 entries from test/wasm-js/tests.tar.gz to test/wasm-js/tests
Downloading 1 files took 11.799816 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-js/tests.tar.gz.sha1' took 11.88 secs
Running hooks:  46% (13/28) sysroot_x86  
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/usr/local/src/plv8/build/v8'
Installing Debian sid i386 root image: /usr/local/src/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/d53a049af5961f2f121ee4e149918097c193f8ed/debian_sid_i386_sysroot.tar.xz
Hook 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x86' took 11.25 secs
Running hooks:  50% (14/28) sysroot_x64
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/usr/local/src/plv8/build/v8'
Installing Debian sid amd64 root image: /usr/local/src/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/43a87bbebccad99325fdcf34166295b121ee15c7/debian_sid_amd64_sysroot.tar.xz
Hook 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 10.08 secs
Running hooks:  71% (20/28) clang               
________ running 'vpython tools/clang/scripts/update.py' in '/usr/local/src/plv8/build/v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-13-init-14086-ge1b8fde1-1.tgz .......... Done.
Running hooks: 100% (28/28), done.                        
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
Updating files: 100% (4205/4205), done.
Previous HEAD position was ff46a39e76 [heap] Fix several object related checks
HEAD is now at e71858f7a0 Version 8.8.278.14
Syncing projects: 100% (28/28), done.                                                

WARNING: 'v8/third_party/google_benchmark/src' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/logdog/logdog' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.
Running hooks:  18% ( 5/27) clang_format_linux
________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' in '/usr/local/src/plv8/build/v8'
0> Downloading buildtools/linux64/clang-format@1baf0089e895c989a311b6a38ed94d0e8be4c0a7...
Downloading 1 files took 10.416424 second(s)
Hook 'download_from_google_storage --no_resume '--platform=linux*' --no_auth --bucket chromium-clang-format -s buildtools/linux64/clang-format.sha1' took 10.50 secs
Running hooks:  29% ( 8/27) wasm_spec_tests   
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' in '/usr/local/src/plv8/build/v8'
0> Downloading test/wasm-spec-tests/tests.tar.gz@a58223f93f7c7489abd950f322f970caac3c2cad...
0> Removed test/wasm-spec-tests/tests...
0> Extracting 461 entries from test/wasm-spec-tests/tests.tar.gz to test/wasm-spec-tests/tests
Downloading 1 files took 10.983611 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-spec-tests/tests.tar.gz.sha1' took 11.07 secs
Running hooks:  33% ( 9/27) wasm_js        
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-js/tests.tar.gz.sha1' in '/usr/local/src/plv8/build/v8'
0> Downloading test/wasm-js/tests.tar.gz@331d0b45c9b1fe5872b5b27a7eff2c889cecb495...
0> Removed test/wasm-js/tests...
0> Extracting 144 entries from test/wasm-js/tests.tar.gz to test/wasm-js/tests
Downloading 1 files took 10.685324 second(s)
Hook 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s test/wasm-js/tests.tar.gz.sha1' took 10.77 secs
Running hooks:  44% (12/27) sysroot_x86  
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x86' in '/usr/local/src/plv8/build/v8'
Installing Debian sid i386 root image: /usr/local/src/plv8/build/v8/build/linux/debian_sid_i386-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/d967bcef40477dbc39acef141ff22bf73f3e7cdb/debian_sid_i386_sysroot.tar.xz
Hook 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x86' took 10.66 secs
Running hooks:  48% (13/27) sysroot_x64
________ running 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x64' in '/usr/local/src/plv8/build/v8'
Installing Debian sid amd64 root image: /usr/local/src/plv8/build/v8/build/linux/debian_sid_amd64-sysroot
Downloading https://commondatastorage.googleapis.com/chrome-linux-sysroot/toolchain/5f64b417e1018dcf8fcc81dc2714e0f264b9b911/debian_sid_amd64_sysroot.tar.xz
Hook 'vpython build/linux/sysroot_scripts/install-sysroot.py --arch=x64' took 10.22 secs
Running hooks:  66% (18/27) binutils            
________ running 'vpython third_party/binutils/download.py' in '/usr/local/src/plv8/build/v8'
Downloading /usr/local/src/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
0> Downloading /usr/local/src/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2@69bedb1192a03126687f75cb6cf1717758a1a59f...
Downloading 1 files took 10.855072 second(s)
Extracting /usr/local/src/plv8/build/v8/third_party/binutils/Linux_x64/binutils.tar.bz2
Hook 'vpython third_party/binutils/download.py' took 12.86 secs
Running hooks:  70% (19/27) clang   
________ running 'vpython tools/clang/scripts/update.py' in '/usr/local/src/plv8/build/v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz .......... Done.
Running hooks: 100% (27/27), done.                        
error: can't open patch '../../patches/*.patch': No such file or directory
make: *** [Makefile:112: build/v8] Error 128
cd build/v8 \
&& env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release v8_monolith
ninja: Entering directory `out.gn/x64.release'
ninja: fatal: chdir to 'out.gn/x64.release' - No such file or directory
make: *** [Makefile:126: v8] Error 1
PG93:5432[postgres@tnt-ubu-multidb:/usr/local/src/plv8]
