### ISSUE TITLE
Feature: esmodules

### ISSUE THREAD

**Issue by andrioid** [plv8/plv8js#446]
I’d love esmodules support for v8 functions. Thst would make it much easier to organize business logic and other utilitied.

Is it feasable to add?

**Comment by ngld** [comment]
You could compile your modules with a bundler like ESBuild, Rollup or Webpack and then insert the bundle into a `CREATE FUNCTION ...` SQL script.
Loading modules from an SQL function isn't possible since plv8 doesn't have access to the filesystem.

**Comment by divyenduz** [comment]
> You could compile your modules with a bundler like ESBuild

I wrote a quick utility to do just that, in case this is of interest to anyone https://www.npmjs.com/package/plv8ify

**Comment by JerrySievert** [comment]
I would happily accept a doc pr for the contrib doc files with a link and info about this and rebuild the Github.Io page.
