### ISSUE TITLE
Needed help with plv8 import for a postcall

### ISSUE THREAD

**Issue by althaf004** [plv8/plv8js#447]
Hi,
my curl function looks like 

_curl --location --request POST 'https://api.mailgun.net/v3/abc.com/messages' \
--header 'Authorization: basic YXBpOjQ3MDskzNjZjOsdGVmYTE2Njg3ZT' \
--form 'from="me@abc.com"' \
--form 'to="alabc@gmail.com"' \
--form 'subject="Testing some Mailgun awesomeness!"' \
--form 'text="Testing some Mailgun awesomeness!"'_

im trying to create a function with plv8 

_create or replace function test_mail()
returns text as $$
import requests 
request_url = 'https://api.mailgun.net/v3/abc.com/messages'
request = requests.post(request_url, auth=('Authorization', basic YXBpOjQ3MDskzNjZjOsdGVmYTE2Njg3ZTRhgdfNWUzZWE3NmIxZT), data={
    'from': 'me@abc.com',
    'to': 'alabc@gmail.com',
    'subject': 'Hello',
    'text': 'Hello from Mailgun'
})
return 'success';
$$ language plv8;_

i know i`m missing the requests, but how could i add it here in the post call?

**Comment by hellower** [comment]
PLV8 is a TRUSTED Javascript language extension for PostgreSQL. 
You couldn't use requests module.

**Comment by althaf004** [comment]
is there any way we could achieve this?

**Comment by JerrySievert** [comment]
to follow up with what @hellower said, in the context of Postgres, a trusted extension does not access the file system or the network directly.  it can only be used inside the sandbox of Postgres.

if you need to make calls outside of Postgres, you will need to install an untrusted extension, such as https://github.com/pramsey/pgsql-http to do as such.  please not the section on why it's not a good idea.

**Comment by althaf004** [comment]
Thanks @JerrySievert and @hellower
