### ISSUE TITLE
PR #441 broke the autov8 build script

### ISSUE THREAD

**Issue by ngld** [plv8/plv8js#448]
The mentioned PR added references to a missing `patches` directory. Specifically here:
https://github.com/plv8/plv8/blob/821f1638934e3f0ad4c979de442d6cb74f1e32e9/Makefile#L91-L97

and here:
https://github.com/plv8/plv8/blob/821f1638934e3f0ad4c979de442d6cb74f1e32e9/Makefile#L111-L118

As far as I can tell, the files from this directory should've been added as part of the PR: https://github.com/pkit/plv8/tree/pkit/v8_8.8/patches

I'm not sure whether the files should be added or the references removed but either change would fix the Makefile.

**Comment by hellower** [comment]
https://github.com/plv8/plv8/issues/445
same issue.

**Comment by Ginden** [comment]
Confirmed on my system, my workaround was to do:

```
	&& (git apply ../../patches/*.patch || true)
```

@hellower

https://github.com/Ginden/plv8/commit/c5b1ba160ad191f7da26300d001b8053e46fda22

I build with following command:

```
docker build --target artifact --output type=local,dest=. .
```

Docker 19+ is required.

Though, I would like to avoid rebuilding v8 on every change...
