### ISSUE TITLE
Certain functions return undefined on empty/invalid arguments

### ISSUE THREAD

**Issue by Ginden** [plv8/plv8js#449]
Eg.
```
plv8.subtransaction(42);
plv8.find_function();
```

It probably should throw (because it's obvious bug in user code), but it doesn't.

**Comment by JerrySievert** [comment]
this would be a breaking change, and thus would need to wait for a major (e.g. 4.0) release to be considered.

**Comment by Ginden** [comment]
@JerrySievert Putting aside versioning strategy (many projects decided to release major version every few months to preserve semantic versioning), I think it should emit at least warning.
