### ISSUE TITLE
Does MSVC 2019 Work?  Is anyone supporting Windows Builds

### ISSUE THREAD

**Issue by kirkw** [plv8/plv8js#456]
Okay, I am leveraging something that requires this, and I have a windows PG 12 installation.
xtuple does not appear to have the binaries past version 10 of PG for this.
The documentation is GREAT (*.io) but it literally says "Assuming you have this installed", Sorry, I don't.  A link to find pre-compiled binaries would be great.  Right there... LOL

All I have access to is MSVC 2019 (but I am not really an MSVC dev).  I was hoping someone else had the build files for windows 10, 64 bit, PG 12 and PG 13 (we will move there).

Willing to work with someone via TeamViewer to get the build going!
Would be nice to have a place to post these.

Would be even nicer if we had a quick/easy way to fire up an environment in the cloud to compile, post somewhere, and move on. [Eventually, right, lol].  Actually, it would be great if we could submit what we have for remote environment compilation (like the old batch/RSX days), and have it deliver the results.  Without us owning that environment... [Everything old is new again]

Thanks in advance.

**Comment by JerrySievert** [comment]
plv8 has nothing to do with xtuple.

plv8 provides instructions for building in windows, and it is supported as much as it can be at this time.

plv8 supports pg9 through pg14 beta, but that support depends on the version of plv8 (we do not back port support for newer versions of Postgres further than 2 releases back), so you must use a newer version of plv8 to support newer versions of postgres (unix, linux, macOS, or windows, they all use the same codebase).

build files for windows are available in the repo, see: https://github.com/plv8/plv8/tree/r3.1alpha/platforms/windows

as for mdvc 2019, I don't have it personally, so I do not know if their latest version builds with postgres.
