### ISSUE TITLE
Build PLV8 universal binary on Mac

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#460]
Hi Jerry

Is there any receipe on how to build PLV8 as a universal binary on Mac for PostgreSQL 14?

All PostgreSQL distributions on Mac have switched to universal binary. At the same time they abandon PLV8, so I want to build it on my own.

**Comment by JerrySievert** [comment]
unfortunately, we're at the mercy of v8, which has its own build system including downloading its own compilers.

**Comment by maparent** [comment]
I have not built it as a universal binary, but I've built it for both mac architectures (Big Sur, postgres 13 and 14) separately using Makefile.shared and the homebrew v8. It requires a few small changes (below.) Of course a universal can then be created by hand with `lipo` (even though the load path differs.)
The build command (assuming `HOMEBREW` points to either `/usr/local` or `/opt/homebrew` appropriately) is:
`env V8_SRCDIR=$HOMEBREW V8_OUTDIR=$HOMEBREW/lib make -f Makefile.shared static`

changes:
```patch
diff --git a/Makefile.shared b/Makefile.shared
index f86c1cf..81b476e 100644
--- a/Makefile.shared
+++ b/Makefile.shared
@@ -56,7 +56,7 @@ endif
 
 SHLIB_LINK += -lv8
 ifdef V8_OUTDIR
-SHLIB_LINK += -L$(V8_OUTDIR)
+SHLIB_LINK += -L$(V8_OUTDIR) -lv8_libplatform
 else
 SHLIB_LINK += -lv8_libplatform
 endif
@@ -71,7 +71,7 @@ endif
 # for older g++ (e.g. 4.6.x), which do not support c++11
 #OPTFLAGS = -O2 -std=gnu++0x -fno-rtti
 
-OPTFLAGS = -std=c++11 -fno-rtti -O2 -g
+OPTFLAGS = -std=c++14 -fno-rtti -O2 -g -DV8_COMPRESS_POINTERS=1
 
 CCFLAGS = -Wall $(OPTFLAGS) $(OPT_ENABLE_DEBUGGER_SUPPORT) -g
 
diff --git a/plv8_type.cc b/plv8_type.cc
index a172808..c9962ad 100644
--- a/plv8_type.cc
+++ b/plv8_type.cc
@@ -600,7 +600,7 @@ CreateExternalArray(void *data, plv8_external_array_type array_type,
 	array->SetInternalField(0, External::New(isolate, DatumGetPointer(datum)));
 
 	// needs to be a copy, as the data could go away
-	memcpy(buffer->GetContents().Data(), data, byte_size);
+	memcpy(buffer->GetBackingStore()->Data(), data, byte_size);
 
 	return array;
 }
@@ -710,7 +710,7 @@ ToScalarDatum(Handle<v8::Value> value, bool *isnull, plv8_type *type)
 		{
 			if (value->IsUint8Array() || value->IsInt8Array()) {
 				v8::Handle<v8::Uint8Array> array = v8::Handle<v8::Uint8Array>::Cast(value);
-				void *data = array->Buffer()->GetContents().Data();
+				void *data = array->Buffer()->GetBackingStore()->Data();
 				int		len = array->Length();
 				size_t		size = len + VARHDRSZ;
 				void	   *result = (void *) palloc(size);
@@ -722,7 +722,7 @@ ToScalarDatum(Handle<v8::Value> value, bool *isnull, plv8_type *type)
 
 			if (value->IsUint16Array() || value->IsInt16Array()) {
 				v8::Handle<v8::Uint16Array> array = v8::Handle<v8::Uint16Array>::Cast(value);
-				void *data = array->Buffer()->GetContents().Data();
+				void *data = array->Buffer()->GetBackingStore()->Data();
 				int		len = array->Length();
 				size_t		size = (len * 2) + VARHDRSZ;
 				void	   *result = (void *) palloc(size);
@@ -734,7 +734,7 @@ ToScalarDatum(Handle<v8::Value> value, bool *isnull, plv8_type *type)
 
 			if (value->IsUint32Array() || value->IsInt32Array()) {
 				v8::Handle<v8::Uint32Array> array = v8::Handle<v8::Uint32Array>::Cast(value);
-				void *data = array->Buffer()->GetContents().Data();
+				void *data = array->Buffer()->GetBackingStore()->Data();
 				int		len = array->Length();
 				size_t		size = (len * 4) + VARHDRSZ;
 				void	   *result = (void *) palloc(size);
@@ -746,7 +746,7 @@ ToScalarDatum(Handle<v8::Value> value, bool *isnull, plv8_type *type)
 
 			if (value->IsArrayBuffer()) {
 				v8::Handle<v8::ArrayBuffer> array = v8::Handle<v8::ArrayBuffer>::Cast(value);
-				void *data = array->GetContents().Data();
+				void *data = array->GetBackingStore()->Data();
 				int		len = array->ByteLength();
 				size_t		size = len + VARHDRSZ;
 				void	   *result = (void *) palloc(size);
```

**Comment by JerrySievert** [comment]
linking against a shared object version of v8 is not going to happen.

nor is changing the code so it won't compile on any other architecture.  so, I appreciate the effort, but it's a non-starter.

**Comment by maparent** [comment]
For the record: the code changes (and the change of c++ standard) have more to do with the fact that the homebrew v8 is now at version 9.4.146.21 as we speak; I agree that my changes cannot be applied as-is as long as you're on the version 8 stream, but I thought you might find it useful to know about what is needed to make it work with v9 eventually. Of course it should be wrapped in version-conditional code.
Otherwise: thank you again for the project, and I appreciate that you created the Makefile.shared for those of us for whom the risk/benefit ratio justifies shared objects. I agree totally that shared objects are too unstable to be the main channel of distribution, but the v8 build mechanism can be a nightmare, and I think the flexibility of shared objects is generally useful for experimentation. I think that making sure that the Makefile.shared handles more cases is still relevant. Again, I did not propose this as a PR because I know it is specific, but knowing specific needs helps building the generic case.

**Comment by JerrySievert** [comment]
give the v3.1 branch of https://github.com/JerrySievert/plv8 a try - it should currently build on x64 and aarch64 macOS as well as arm64 and x64 ubuntu.  still working on other targets, at which point I'll push a new release.

**Comment by JerrySievert** [comment]
I won't be able to work on it until next weekend, so I'm still at least a week away from a new release, but I will also try to solve the windows build issues in 3.1.

the good news is that an m1 max compiles v8 pretty darned fast compared to an intel MacBook Pro and all of the x64 hardware I have sitting around - makes iterating MUCH faster :)

**Comment by JerrySievert** [comment]
3.1 has been released.  while it does not solve the universal binary issue, it does work well on arm64 and amd64
