### ISSUE TITLE
CentOS 8 (static) build guidelines

### ISSUE THREAD

**Issue by luss** [plv8/plv8js#462]
Anyone successfully building on EL8?

**Comment by luss** [comment]
I'm gonna try with v3.0, I wasn't able to get it working with latest 2.3

**Comment by JerrySievert** [comment]
have you read the building requirements at https://plv8.github.io/#building ?

**Comment by JerrySievert** [comment]
also, please search any issues before opening a new one.  for instance: https://github.com/plv8/plv8/issues/421

**Comment by luss** [comment]
yes...

The challenge I have is the tinfo5 requirement on centos 8.  by default
it's tinfo6.   I should probably just try and symlink the library.  Not
sure if that will work or if other have run into this.

**Comment by luss** [comment]
I'm with ya.   I did search that issue and I was pg13 so I made sure I was
using latest 2.x

**Comment by JerrySievert** [comment]
2.3.15 is compatible with pg13 and pg14 (as well as anything above 9.6).

**Comment by cocowalla** [comment]
> have you read the building requirements at https://plv8.github.io/#building ?

I'm also interesting in doing a static build, which I have working with an old version (2.3.14). I've read the docs, but I don't see anything about static builds? Or does it always do a static build now?

**Comment by JerrySievert** [comment]
every build is a static build unless you hack up the build process and force a shared build.
