### ISSUE TITLE
Upgrading the extension

### ISSUE THREAD

**Issue by jtojnar** [plv8/plv8js#466]
Last time I interacted with my application I was running plv8 2.3.13. Now I need to use it again but in the meanwhile, the distro I use switched to 2.3.15, causing most of the app queries to fail with:

```
ERROR:  could not access file "$libdir/plv8-2.3.13": No such file or directory
```

I also tried to update the extension as specified in the docs but it failed with the same error:

```
=# ALTER EXTENSION plv8 UPDATE;
ERROR:  could not access file "$libdir/plv8-2.3.13": No such file or directory
```

I cannot just drop the extension because the rest of the database depends on it:

```
=# DROP EXTENSION plv8;
ERROR:  cannot drop extension plv8 because other objects depend on it
```

I also tried updating the plv8 package to 3.0 but that went even worse since update path does not seem to be defined:

https://github.com/plv8/plv8/blob/v3.0.0/generate_upgrade.sh#L6

```
=# ALTER EXTENSION plv8 UPDATE;
ERROR:  extension "plv8" has no update path from version "2.3.13" to version "3.0.0"
```

And if I patch the package similarly to https://github.com/plv8/plv8/pull/465, it again fails with the familiar error:

```
=# ALTER EXTENSION plv8 UPDATE;
ERROR:  could not access file "$libdir/plv8-2.3.13": No such file or directory
```

I suppose I can install the old `plv8-2.3.13.so` back but is this really required for upgrade to work?

Or I could run `UPDATE pg_proc SET probin = '$libdir/plv8-3.0.0' WHERE proname LIKE 'plv8%';` but I feel rather queasy about tweaking Postgres’s internal state.

I use PostgreSQL 11.14 on NixOS.

**Comment by patrickmichalina** [comment]
Same issue here. What is the correct procedure?

**Comment by JerrySievert** [comment]
@patrickmichalina there should be upgrade paths for everything in 3.1.6, is there something you see missing?

**Comment by patrickmichalina** [comment]
The only thing I can think of is my custom docker image is not including the previous versions?

```bash
# plv8
COPY --from=builder /usr/lib/postgresql/${PG_MAJOR}/lib/plv8* /usr/lib/postgresql/${PG_MAJOR}/lib/
COPY --from=builder /usr/lib/postgresql/${PG_MAJOR}/lib/bitcode/plv8-${PLV8_VERSION}.index.bc /usr/lib/postgresql/${PG_MAJOR}/lib/bitcode/
COPY --from=builder /usr/lib/postgresql/${PG_MAJOR}/lib/bitcode/plv8-${PLV8_VERSION}/* /usr/lib/postgresql/${PG_MAJOR}/lib/bitcode/plv8-${PLV8_VERSION}/
COPY --from=builder /usr/share/postgresql/${PG_MAJOR}/extension/plv8* /usr/share/postgresql/${PG_MAJOR}/extension/
COPY --from=builder /usr/share/postgresql/${PG_MAJOR}/extension/plls* /usr/share/postgresql/${PG_MAJOR}/extension/
COPY --from=builder /usr/share/postgresql/${PG_MAJOR}/extension/plcoffee* /usr/share/postgresql/${PG_MAJOR}/extension/\
```

**Comment by JerrySievert** [comment]
if looks like you're copying the `.sql` files, but you should check for files that look like `plv8--3.1.1--3.1.6.sql`

they are generated and part of the `upgrade` directory:

```
plv8--1.5.0--3.1.6.sql
plv8--1.5.1--3.1.6.sql
plv8--1.5.2--3.1.6.sql
plv8--1.5.3--3.1.6.sql
plv8--1.5.4--3.1.6.sql
plv8--1.5.5--3.1.6.sql
plv8--1.5.6--3.1.6.sql
plv8--1.5.7--3.1.6.sql
plv8--2.0.0--3.1.6.sql
plv8--2.0.1--3.1.6.sql
plv8--2.0.3--3.1.6.sql
plv8--2.1.0--3.1.6.sql
plv8--2.1.2--3.1.6.sql
plv8--2.3.0--3.1.6.sql
plv8--2.3.1--3.1.6.sql
plv8--2.3.10--3.1.6.sql
plv8--2.3.11--3.1.6.sql
plv8--2.3.12--3.1.6.sql
plv8--2.3.13--3.1.6.sql
plv8--2.3.14--3.1.6.sql
plv8--2.3.15--3.1.6.sql
plv8--2.3.2--3.1.6.sql
plv8--2.3.3--3.1.6.sql
plv8--2.3.4--3.1.6.sql
plv8--2.3.5--3.1.6.sql
plv8--2.3.6--3.1.6.sql
plv8--2.3.7--3.1.6.sql
plv8--2.3.8--3.1.6.sql
plv8--2.3.9--3.1.6.sql
plv8--3.0.0--3.1.6.sql
plv8--3.0.1--3.1.6.sql
plv8--3.1.0--3.1.6.sql
plv8--3.1.1--3.1.6.sql
plv8--3.1.2--3.1.6.sql
plv8--3.1.3--3.1.6.sql
plv8--3.1.4--3.1.6.sql
plv8--3.1.5--3.1.6.sql
```

**Comment by patrickmichalina** [comment]
@JerrySievert would all these files just be copied to `/usr/share/postgresql/${PG_MAJOR}/extension/`

`COPY --from=builder /usr/build/plv8/upgrade/* /usr/share/postgresql/${PG_MAJOR}/extension/`

**Comment by JerrySievert** [comment]
they should be copied to wherever your local upgrade scripts go - that's going to be dependent on how your postgres compilation is configured (it appears that you are not using the default?)

**Comment by patrickmichalina** [comment]
@JerrySievert my file is based on the one you have in this repo (except I bundler more extensions).

https://github.com/plv8/plv8/blob/r3.1/platforms/Docker/bullseye/14.5/Dockerfile

I am just not seeing where the upgrades folder is copied into the image after the build.
