### ISSUE TITLE
Problem building plv8 on Amazon Linux 2

### ISSUE THREAD

**Issue by hmarzooq** [plv8/plv8js#468]
Hello!

I'm trying to install plv8 and create an extension in Postgres 13.3 on Amazon Linux 2 machine. I've tried to set up all the pre-requisites mentioned for plv8 building here: https://plv8.github.io on Linux.

But when it comes to "make" of plv8, then it ends with the below error:

```
/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status
make: *** [plv8-3.0.0.so] Error 1
```
I assume this is the last thing plv8 make needs to complete i.e. https://github.com/plv8/plv8/blob/r3.1alpha/Makefile#L166

I have build and installed libcxx;libcxxabi using https://libcxx.llvm.org/BuildingLibcxx.html#bootstrapping-build

```
[root@ip-1-1-0-1 plv8-3.0.0]# ls /usr/local/lib/x86_64-unknown-linux/
libc++.a  libc++abi.a  libc++abi.so  libc++abi.so.1  libc++abi.so.1.0  libc++experimental.a  libc++.so  libc++.so.1  libc++.so.1.0
```
**machine info:**

```
cat /proc/version
Linux version 4.14.252-195.483.amzn2.x86_64 (mockbuild@ip-1-0-1-1) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC))
```
Some workarounds I've done so far:
1: Tried appending -L as below:
`SHLIB_LINK += -lrt -std=c++11 -lc++ -L/usr/local/lib/x86_64-unknown-linux` 
its gives same error: `/bin/ld: cannot find -lc++`

2: Tried doing plv8 make by removing -lc++ ( https://github.com/plv8/plv8/blob/r3.1alpha/Makefile#L166) assuming plv8 would use Amazon Linux default `libstdc++` but it gives error `make: /usr/bin/opt: Command not found`

3: Assuming the actual error i.e. `/bin/ld: cannot find -lc++` means that linker (ld) cannot find lc++ in the search path, I did investigate below (RPATH issue) and fixed the "not found" issue and re-run `make clean` & `make` after removing/creating `build` dir.

```
ldd /usr/local/lib/x86_64-unknown-linux/libc++.so.1.0
        linux-vdso.so.1 (0x00007ffe49d33000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fec62477000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fec620cc000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fec61d8c000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fec61b84000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fec6196e000)
        libatomic.so.1 => /lib64/libatomic.so.1 (0x00007fec61766000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fec62966000)
        libc++abi.so.1 => not found
```
**fixing it by** `export LD_LIBRARY_PATH=/usr/local/lib/x86_64-unknown-linux/`

**verifying**
```
ldd /usr/local/lib/x86_64-unknown-linux/libc++.so.1.0
        linux-vdso.so.1 (0x00007ffce078e000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fefd6ae0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fefd6735000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fefd63f5000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fefd61ed000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fefd5fd7000)
        libatomic.so.1 => /lib64/libatomic.so.1 (0x00007fefd5dcf000)
        libc++abi.so.1 => /usr/local/lib/x86_64-unknown-linux/libc++abi.so.1 (0x00007fefd5b8e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fefd6fcf000)
```
landed with same error `/bin/ld: cannot find -lc++`

I would appreciate if I can get some insights here that what is going wrong? I'm assuming I've come a long way after building and installing all the prerequisites for plv8 and at last getting stuck on the very last line of plv8 `make`.

Thank you.

**Comment by JerrySievert** [comment]
what does an `ls -l` of `/usr/local/lib/x86_64-unknown-linux/libc++.a` give you?

also, what does `file /usr/local/lib/x86_64-unknown-linux/libc++.a` give you?

can you verify that `/usr/local/lib/x86_64-unknown-linux/` is in your ld.so config somewhere?

**Comment by hmarzooq** [comment]
```
# ls -l /usr/local/lib/x86_64-unknown-linux/libc++.a
-rw-r--r-- 1 root root 1979116 Dec 13 02:47 /usr/local/lib/x86_64-unknown-linux/libc++.a
```

```
# file /usr/local/lib/x86_64-unknown-linux/libc++.a
/usr/local/lib/x86_64-unknown-linux/libc++.a: current ar archive
```

```
# cat /etc/ld.so.conf
include ld.so.conf.d/*.conf

# pwd
/etc/ld.so.conf.d

# ls
bind-export-x86_64.conf  dyninst-x86_64.conf  llvm5.0-x86_64.conf  mariadb-x86_64.conf

 grep -rnw . -e "linux"
#
```
I didn't found `/usr/local/lib/x86_64-unknown-linux/` anywhere in ld.so config.

**Comment by hmarzooq** [comment]
Some more info:
```
# pwd
/usr/local/lib/x86_64-unknown-linux
[root@ip-1-1-0-1 x86_64-unknown-linux]# ls -ltrh
total 4.0M
-rw-r--r-- 1 root root 1.9M Dec 13 02:47 libc++.a
-rwxr-xr-x 1 root root 1.1M Dec 13 02:47 libc++.so.1.0
-rw-r--r-- 1 root root   28 Dec 13 02:47 libc++.so
-rw-r--r-- 1 root root  13K Dec 13 02:47 libc++experimental.a
-rwxr-xr-x 1 root root 358K Dec 13 02:47 libc++abi.so.1.0
-rw-r--r-- 1 root root 665K Dec 13 02:47 libc++abi.a
lrwxrwxrwx 1 root root   13 Dec 13 07:00 libc++.so.1 -> libc++.so.1.0
lrwxrwxrwx 1 root root   16 Dec 13 07:00 libc++abi.so.1 -> libc++abi.so.1.0
lrwxrwxrwx 1 root root   14 Dec 13 07:00 libc++abi.so -> libc++abi.so.1
[root@ip-10-3-0-165 x86_64-unknown-linux]#
```

**Comment by JerrySievert** [comment]
you'll need the ldconfig path set regardless.

you can give my branch where I've been working on 3.1alpha a try if you want, it's in https://github.com/JerrySievert/plv8 in the `v3.1` branch, but I have not yet tried it on redhat based distros.

**Comment by hmarzooq** [comment]
Error "/bin/ld: cannot find -lc++" is fixed by using three different approaches individually.

1: Appending "-L/usr/local/lib/x86_64-unknown-linux-gnu" to <https://github.com/plv8/plv8/blob/r3.1alpha/Makefile#L166>

2: Doing "make LDFLAGS=-L/usr/local/lib/x86_64-unknown-linux-gnu"

3: Copying files from "/usr/local/lib/x86_64-unknown-linux-gnu" to "/usr/lib" as "usr/local/lib" is in ld's search.

**Comment by hmarzooq** [comment]
I'm now getting error when creating extension:

```
# sudo -u postgres psql
could not change directory to "/root/plv8-3.0.0": Permission denied
psql (13.3)
Type "help" for help.

postgres=# CREATE EXTENSION plv8;
ERROR:  **could not load library "/usr/lib64/pgsql/plv8-3.0.0.so": libc++.so.1: cannot open shared object file: No such file or directory**
postgres=# exit
```

```
s -ltrh /usr/lib64/pgsql/plv8-3.0.0.so
-rwxr-xr-x 1 root root 153M Dec 16 07:54 /usr/lib64/pgsql/plv8-3.0.0.so

ls -ltrh /usr/local/lib/libc++.so.1
-rwxr-xr-x 1 root root 1.1M Dec 15 12:16 /usr/local/lib/libc++.so.1
```

```
 ldd /usr/lib64/pgsql/plv8-3.0.0.so
        linux-vdso.so.1 (0x00007ffd03f21000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f708ec34000)
        libc++.so.1 => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f708e8b2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f708e572000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f708e35c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f708dfb1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7091178000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f708dd93000)
```
```
ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
SEARCH_DIR("=/usr/x86_64-redhat-linux/lib64")
SEARCH_DIR("=/usr/lib64")
SEARCH_DIR("=/usr/local/lib64")
SEARCH_DIR("=/lib64")
SEARCH_DIR("=/usr/x86_64-redhat-linux/lib")
SEARCH_DIR("=/usr/local/lib")
SEARCH_DIR("=/lib")
SEARCH_DIR("=/usr/lib")
```
I've tried copying `plv8-3.0.0.so` into `/usr/local/lib` as this dir is in ld's search path. But still getting same error `ould not load library "/usr/lib64/pgsql/plv8-3.0.0.so": libc++.so.1: cannot open shared object file: No such file or directory`

I've build using `make` and `make install` and apparently there was no errors. 

Any idea/guidance ? Please.

Thanks!

**Comment by JerrySievert** [comment]
as noted above:

> can you verify that `/usr/local/lib/x86_64-unknown-linux/` is in your ld.so config somewhere?

without that, your os will not know where to find `libc++.so` and its ancillary files.

don't just move it into another directory, set up the directory it configured itself for and installed to, or configure it at build time to install to another known-good directory.

**Comment by hmarzooq** [comment]
Thanks Jerry!
This problem is resolved by adding `/usr/local/lib/x86_64-unknown-linux/` into `/etc/ld.so.conf.d` and later running `ldconfig`. 

plv8 extension is created in Postgres 13.3.

**Comment by JerrySievert** [comment]
r3.1 has been released, this should fix the issue.
