### ISSUE TITLE
Plv8 - Docker - 

### ISSUE THREAD

**Issue by robGetsTheJobDone** [plv8/plv8js#473]
Hey PL8 team you rock!! 

I am using clkao/postgres-plv8:11-2

I can create functions and execute them a ok! 

I am unable to call
`SELECT plv8_info();`

I get this error, 
```
ERROR:  function plv8_info() does not exist
LINE 1: SELECT plv8_info();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
SQL state: 42883
Character: 8
```

I assigned my user the SUPERUSER role and recounted. 
`ALTER USER postgres WITH SUPERUSER;`

I feel like I am missing something simple. If anyone has any idea what I am doing wrong please let me know.

**Comment by JerrySievert** [comment]
do you know which version of plv8 ships with that?

one of these should give you the version:

```
=# select plv8_version();
```

```
=# do $$ plv8.elog(NOTICE, plv8.version) $$ language plv8;
```

**Comment by robGetsTheJobDone** [comment]
Jerry - you are a legend for the fast reply. 
v 2.3.13  ships with that img. 

I realized now that's probably too old, looking over other available imgs it seems most use old versions.

Do you have a recommendation for a prebuilt docker image?

**Comment by JerrySievert** [comment]
I'm afraid that currently we don't ship a docker image by default.  I think there are some other suggestions if you search issues for docker.

that would be why `plv8_info()` isn't there though, it got added a little later than that.

**Comment by JerrySievert** [comment]
https://github.com/plv8/plv8/issues/454 contains a docker file (broken), but has the notes on how to fix it.  that should help you out a bit, I just don't know if there are existing images on docker hub.

**Comment by robGetsTheJobDone** [comment]
Thank you I also found this snippet. 




```
ARG PG_MAJOR=10
ARG PG_IMAGE_VERSION=10.10
FROM postgres:${PG_IMAGE_VERSION}

ARG BRANCH="r3.0alpha"
ARG GIT_ORG="https://github.com/plv8"

RUN buildDependencies="build-essential \
    ca-certificates \
    curl \
    git \
    postgresql-server-dev-$PG_MAJOR \
    python \
    libc++-dev \
    pkg-config \
    openssh-client \
    libssl-dev" \
  && apt-get update \
  && apt-get install -y --no-install-recommends ${buildDependencies} \
  && mkdir -p /tmp/build \
  && cd /tmp/build \
  && git clone --branch "$BRANCH" "$GIT_ORG/plv8" plv8 \
  && cd plv8 \
  && make static \
  && make install
```


@JerrySievert  would you be open for a 15-minute chat.? 
I  am building a type inference engine and I am sure you have a lot of great views.

**Comment by JerrySievert** [comment]
I would think you'd want a little newer pg than 10.10 :)

re: chat, yeah, I can make that happen.  email me at the address in my profile, and we can figure out a time.

**Comment by JerrySievert** [comment]
https://github.com/plv8/plv8/tree/r3.1/platforms/Docker
