### ISSUE TITLE
Undefined symbol when installing plv8 on RHEL8.1 x86_64

### ISSUE THREAD

**Issue by e4sy-one** [plv8/plv8js#492]
Hi!
When I try to create extension for PG 14.4 I get this error:

postgres=# CREATE EXTENSION plv8;
ERROR:  could not load library "/usr/pgsql-14/lib/plv8-3.1.1.so": /usr/pgsql-14/lib/plv8-3.1.1.so: undefined symbol: _ZNK2v85Value14IsFloat64ArrayEv

If it could help, this string could be found in folowing files:
    grep -r 'ZNK2v85Value14IsFloat64ArrayEv'
    Binary file plv8_type.o matches
    Binary file plv8-3.1.1.so matches
    Binary file plv8_type.bc matches

I really appreciate to get any ideas, what's wrong.

**Comment by JerrySievert** [comment]
```
val->IsFloat64Array()
```

which is a `v8` function.  can you share how you built plv8?  do you have `v8` or `libv8` installed somewhere on your system?  if so, it will never work.  plv8 needs to be built specifically with the version of `v8` that it is tied to.

**Comment by e4sy-one** [comment]
Thanks, Jerry, for quick answer, I uninstalled libv8 package and now had only 1 error

g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -shared -o plv8-3.1.1.so plv8.o plv8_type.o plv8_func.o plv8_param.o plv8_allocator.o coffee-script.o livescript.o -L/usr/pgsql-14/lib  -Wl,--as-needed -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-14/lib',--enable-new-dtags  -Lbuild/v8/out.gn/obj -lv8_libplatform -lv8_libbase -Lbuild/v8/out.gn/obj -lrt -std=c++14  -lv8_libplatform -lv8_libbase **-lv8_monolith**
/usr/bin/ld: cannot find -lv8_monolith

which I bypassed before running this command manually removing last part and then continued make. And get sadly the same error creating extension. Maybe the reason is in this "monolith"?

**Comment by JerrySievert** [comment]
did you `rm -rf build` before building again?  also `make clean` inside the plv8 directory.

that should clear anything that might have been built with bad includes or libs.

also, make sure that any `-dev` packages for v8 are uninstalled as well.

**Comment by e4sy-one** [comment]
I started new compilation from scratch unpacking archive once again. Actually make stopped first time on

        /usr/bin/ld.gold: warning: ignoring --threads: /usr/bin/ld.gold was compiled without thread support
        /usr/bin/ld.gold: warning: ignoring --thread-count: /usr/bin/ld.gold was compiled without thread support
        /usr/bin/ld.gold: error: treating warnings as errors
        clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
        [189/1287] CC obj/third_party/zlib/zlib_x86_simd/crc_folding.o
        ../../clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang: /lib64/libtinfo.so.5: no version information available (required by ../../clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04/bin/clang)
        ninja: build stopped: subcommand failed.
        make[1]: *** [Makefiles/Makefile.linux:57: build/v8] Error 1

and continued after make restart.
I had only 1 package with libv8 - nodejs-libs, which I uninstalled already,

**Comment by luss** [comment]
Why not try and use the clang++LLVM 13.0.1 that comes with el8

**Comment by e4sy-one** [comment]
I guess that this one is what is being used according to the path above. Otherwise, how could I exclude systemwide clang version from usage?

**Comment by luss** [comment]
Trying to get latest PLv8 to build and run on el8 happens to be a hobby of
mine.  :-)

Below is my WIP replacement makefile.  I have commented out, with two
hashtags, five or six lines as you can see.   This isn't the final
solution.  With my Makefile changes, I get it to compile but it doesn't run
yet.  Someone, or a combination of us, needs to figure this out all the way
through and fix the makefile more elegantly so it works on various
mainstream platforms.   I should also mention that I am trying to use gcc11
with el8.  I think we need to use something newere than the default gcc 8.5
and using the gcc that comes with el9 seemed a good starting point for me
for the el8 build.

--Luss

.phony: v8

ARCH := $(shell uname -m)
##ifeq ($(ARCH),aarch64)
## LLVM :=
https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/clang+llvm-13.0.1-aarch64-linux-gnu.tar.xz
## LLVM_BINPATH := $(shell pwd)/build/clang+llvm-13.0.1-aarch64-linux-gnu
## ARCH := arm64
##endif
##ifeq ($(ARCH),x86_64)
## LLVM :=
https://github.com/llvm/llvm-project/releases/download/llvmorg-13.0.1/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04.tar.xz
## LLVM_BINPATH := $(shell
pwd)/build/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04
## ARCH := x64
##endif

##GN_ARGS = is_component_build=false v8_use_external_startup_data=false
v8_enable_i18n_support=false clang_base_path=\"$(LLVM_BINPATH)\"
clang_use_chrome_plugins=false use_custom_libcxx=false
treat_warnings_as_errors=false use_lld=false v8_monolithic=true
GN_ARGS = is_component_build=false v8_use_external_startup_data=false
v8_enable_i18n_support=false clang_use_chrome_plugins=false
use_custom_libcxx=false treat_warnings_as_errors=false use_lld=false
v8_monolithic=true use_sysroot=false is_clang=false


build/gn/out/gn:
@echo "Setting up build directory"
@mkdir -p build
***@***.*** "Downloading LLVM"
***@***.*** -q -O build/llvm.tar.xz $(LLVM)
***@***.*** build && tar -Jxf llvm.tar.xz
@echo "Downloading gn source"
@git clone -q https://gn.googlesource.com/gn.git build/gn
@echo "GN_ARGS=$(GN_ARGS)"
@cd build/gn && git checkout -q eea3906f0e2a8d3622080127d2005ff214d51383
@echo "Building gn"
##cd build/gn && export PATH=$$PATH:$(LLVM_BINPATH)/bin && python3
build/gen.py && ninja -C out/ gn
cd build/gn && python3 build/gen.py && ninja -C out/ gn

build/v8: build/gn/out/gn
@echo "Downloading v8 source"
@git clone -q https://github.com/v8/v8 build/v8
@cd build/v8 && git checkout -q 9.7.37
@echo "Patching v8"
@cd build/v8 && (git apply ../../patches/*.patch || true)
@echo "Downloading up third party sources"
@git clone -q
https://chromium.googlesource.com/chromium/src/base/trace_event/common.git
build/v8/base/trace_event/common
@cd build/v8/base/trace_event/common && git checkout -q
3da1e2fcf66acd5c7194497b4285ac163f32e239
@git clone -q https://chromium.googlesource.com/chromium/src/build.git
build/v8/build
@cd build/v8/build && git checkout -q
bbf7f0ed65548c4df862d2a2748e3a9b908a3217
@git clone -q
https://chromium.googlesource.com/external/github.com/google/googletest.git
build/v8/third_party/googletest/src
@cd build/v8/third_party/googletest/src && git checkout -q
47f819c3ca54fb602f432904443e00a0a1fe2f42
@git clone -q https://chromium.googlesource.com/chromium/deps/icu.git
build/v8/third_party/icu
@cd build/v8/third_party/icu && git checkout -q
75e34bcccea0be165c31fdb278b3712c516c5876
@git clone -q
https://chromium.googlesource.com/chromium/src/third_party/jinja2.git
build/v8/third_party/jinja2
@cd build/v8/third_party/jinja2 && git checkout -q
ee69aa00ee8536f61db6a451f3858745cf587de6
@git clone -q
https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git
build/v8/third_party/markupsafe
@cd build/v8/third_party/markupsafe && git checkout -q
1b882ef6372b58bfd55a3285f37ed801be9137cd
@git clone -q
https://chromium.googlesource.com/chromium/src/third_party/zlib.git
build/v8/third_party/zlib
@cd build/v8/third_party/zlib && git checkout -q
563140dd9c24f84bf40919196e9e7666d351cc0d
@cp Makefiles/gclient_args.gni build/v8/build/config/gclient_args.gni
***@***.*** "Setting up sysroot"
***@***.*** build/v8 && python3 build/linux/sysroot_scripts/install-sysroot.py
--arch=$(ARCH)
@echo "Generating v8 configuration"
@cd build/v8 && ../gn/out/gn gen out.gn --args="$(GN_ARGS)"
@echo "Building v8"
***@***.*** build/v8 && export PATH=$$PATH:$(LLVM_BINPATH)/bin && ninja -C ./
out.gn v8_monolith
@cd build/v8 && export && ninja -C ./out.gn v8_monolith

libv8_monolith.a: build/v8

v8: libv8_monolith.a

all: v8

**Comment by JerrySievert** [comment]
I can try to help troubleshoot, but I'm afraid I don't currently have an rhel8.1 host running in my home lab currently.

but, I can probably help with ideas or at least track through some of that arcane v8 knowledge.

if you're willing to try to build v8 with v8's native build system, I can guide you through it, but beware that it's fairly arcane but might end up with a good build.

@luss any PR's are very welcome, especially if it ends up in a more reliable build across more platforms (what this project sorely needs, and `3.1` was an attempt at).

**Comment by e4sy-one** [comment]
I understand that different environments are headache for developers, but at least I count on running binaries that compiled successfully :-) May be should be considered some  additional checks during compilation... I could provide any other info about my environment (libs version, etc) or try to build any experimental sources

**Comment by JerrySievert** [comment]
and you know, if it were just plv8 source being compiled, it would be pretty easy, but unfortunately we have to deal with v8, and its breaking changes as well.  it's a beast to compile, and a weak spot of plv8 at the moment, unfortunately.

if you want to be adventurous, here are a couple of steps you can take:

* `rm -rf build` - do this first as we're going to be starting from scratch and need a clean environment
* `mkdir build`
* `cd build`
* `git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git`
* add `depot_tools` to your path, you will need them
* `fetch v8` - fetch comes from `depot_tools`
* `cd v8`
* `git checkout 9.7.37`
* `gclient sync` - gclient comes from `depot_tools`
* `./tools/dev/v8gen.py x64.release -- is_component_build=false v8_use_external_startup_data=false v8_enable_i18n_support=false use_custom_libcxx=false treat_warnings_as_errors=false v8_monolithic=true`
* `env CXXFLAGS=-fPIC CFLAGS=-fPIC ninja -C out.gn/x64.release v8_monolith`

if that builds correctly for you, then I can guide you through some quick modifications of the core `Makefile`s to finish the plv8 build and link.

**Comment by e4sy-one** [comment]
Hi Jerry!

In the last one I got this
`./torque: /lib64/libstdc++.so.6: version "GLIBCXX_3.4.26" not found (required by ./torque)`
I have 3.4.25, it seems that I need to upgrade system to the newer version...

**Comment by JerrySievert** [comment]
you can try changing `use_custom_libcxx=false` to `true`, and redo the whole build, but I doubt it will make a difference.

**Comment by e4sy-one** [comment]
This really did a trick, everything ended up successfully

**Comment by JerrySievert** [comment]
did you manage to get plv8 itself built and tested?

**Comment by e4sy-one** [comment]
How should I do this after prev steps? I only know `make` and `make install` :)

**Comment by JerrySievert** [comment]
if you didn't finish the plv8 build itself, then I'll follow up with some build instructions as soon as I can finish my workday (a few hours).

if you managed to get plv8 built, you can test after the `make install` by doing `make installcheck`, which is Postgres's method of testing extensions.

**Comment by e4sy-one** [comment]
Sorry, should I run now `make install` or `make installcheck` from plv8-3.1.2 dir or what?

**Comment by JerrySievert** [comment]
now that you have `v8` built (in the `build` directory of plv8, correct?) you should be able to run (from the plv8 directory itself):

`make`
`make install`
`make installcheck`

let me know if there are errors from the plain `make`

**Comment by e4sy-one** [comment]
I had the same compile errors as mentioned earlier
```
1. /usr/bin/ld.gold: error: treating warnings as errors
2. /usr/bin/ld: cannot find -lv8_monolith
```
and the same error `undefined symbol` creating extension.
So as for me I don't see any effect of pre-building v8

**Comment by JerrySievert** [comment]
you can try (from the plv8 directory):

`find build | grep monolith` and post the results, but I fear it's just going to come down to not being able to build this version of v8 (and hence plv8) without an updated glibc.  which, is unfortunately outside my control, and can only be solved by a newer version of the library or operating system, or going to an older version of plv8 that has a version of v8 that can be built on your system.

**Comment by e4sy-one** [comment]
```
$ find build | grep monolith
build/depot_tools/v8/out.gn/x64.release/obj/v8_monolith.ninja
build/depot_tools/v8/out.gn/x64.release/obj/libv8_monolith.a
build/v8/out.gn/obj/v8_monolith.ninja
```

**Comment by JerrySievert** [comment]
well, that's good news at least.  when I have a few minutes, I'll try to break down the rest of the makefile for you to try to get it to link.

**Comment by JerrySievert** [comment]
I spent a good amount of time trying my damnedest to get modern v8 to build cleanly on rhel 8, but have failed so far.

the good news is that it allowed me to make significant progress with docker.  not sure if that would help in this regard, but at least worth a thought in the interim.
