### ISSUE TITLE
[Q] plv8 library file size

### ISSUE THREAD

**Issue by hellower** [plv8/plv8js#497]
I  built using this file  ("https://github.com/plv8/plv8/blob/r3.1/platforms/Docker/bullseye/14.5/Dockerfile")
and compiled succeeded.

but plv8-3.1.4.so file is too large.
................................................................................
postgres@090741cb77d8:/usr/lib/postgresql/14/lib$ ls -l plv8-3.1.4.so 
-rwxr-xr-x 1 root root **_1444874560_** Aug 30 00:19 plv8-3.1.4.so
postgres@090741cb77d8:/usr/lib/postgresql/14/lib$ ls -lh plv8-3.1.4.so 
-rwxr-xr-x 1 root root **_1.4G_** Aug 30 00:19 plv8-3.1.4.so
postgres@090741cb77d8:/usr/lib/postgresql/14/lib$ 

Is it normal?

**Comment by JerrySievert** [comment]
"too large" is just your opinion :)

but seriously, that is a little bit on the large side.  I can see if a `strip` will help.

good to see someone trying it at least!  my hope is that with a little refinement, it can be useful for others.  alpine, otoh, I spent a bit of time hitting my head with it, and ran out of allocated time.  I'll try again this weekend with some fresh ideas, unless someone else is able to beat me to the punch.

**Comment by JerrySievert** [comment]
regardless, my true hope is that someone with better alpine/docker experience can look at the v8 compilation and say, "oh, this makes sense now, I can make it better".

**Comment by JerrySievert** [comment]
stripping it takes it down to 36326376 on arm64 (~36MB).

I'll push the change up, which should help a little bit.

**Comment by hellower** [comment]
alpine plv8 dockerfile here!!

https://github.com/sibedge-llc/plv8-dockerfiles/tree/master/alpine

**Comment by JerrySievert** [comment]
wow, that's just nasty!

but this: https://github.com/sibedge-llc/plv8-dockerfiles/blob/master/alpine/Dockerfile#L92 might be a good step.
