### ISSUE TITLE
Statement level triggers not able to find relation to transition table

### ISSUE THREAD

**Issue by lbarbula** [plv8/plv8js#499]
I have a relatively simple statement level trigger set to pull records from an update action to populate a logging table, however, it seems that the relation to the transition table cannot be found within a plv8.execute statement. 

This is the table referenced in the insert statement
```
      CREATE TABLE IF NOT EXISTS schema.log_table (
        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        change_action varchar(65),
        old_value jsonb,
        new_value jsonb,
        parent_id integer,
        record_id integer,
        createdAt timestamp with time zone DEFAULT now()
      );
```

This is part of the function definition up to the offending line
```
CREATE OR REPLACE FUNCTION record_update ()
    RETURNS TRIGGER
    AS $$
    const updatedValues = plv8.execute('SELECT * FROM new_table;')
    for (let i = 0; i < updatedValues.length; i++) {
      const currentRecord = updatedValues[i]
      const parentId = currentRecord.parentId
      const recordId = currentRecord.id
        plv8.execute ("INSERT INTO schema.log_table (change_action, old_value, new_value, parent_id, record_id) VALUES ($1, $2, $3, $4, $5);", ['UPDATE_RECORD', null, currentRecord, parentId, recordId]) 
      }
    $$ LANGUAGE plv8;
```

And this is the trigger definition
``` 
CREATE TRIGGER trigger_update_record
      AFTER UPDATE ON table
      REFERENCING OLD TABLE AS old_table NEW TABLE AS new_table
      FOR EACH STATEMENT
      EXECUTE FUNCTION record_update();
```

and finally the error
`ERROR: relation "new_table" does not exist
  Where: record_update() LINE 3:         
const updatedValues = plv8.execute('SELECT * FROM new_table;')`

I have changed some of these values so as not to expose anything proprietary, but the idea should be clear. Am I missing something in the documentation that would allow this to work? Or are statement level triggers just not possible with plv8?

**Comment by JerrySievert** [comment]
can you please provide a self-contained example showing the behavior you're expecting not working?

from what little you've provided, it looks like you're trying to access an alias from inside another stored procedure from inside a second stored procedure.  if that's the case, it will never work in any language.

if that's not the case, it would be good to have a fully-reprduceable test case.

statement level triggers, along with any other Postgres feature are not "special" inside of plv8, the `plv8.execute()` is simply using Postgres's SPI interface.  see https://github.com/plv8/plv8/blob/r3.1/plv8_func.cc#L545 for a quick example of it.

**Comment by lbarbula** [comment]
I've updated the example with essentially the exact trigger, function, and new table that I'm attempting to execute. Again, I've obfuscated the real values in order to protect our schema, but, the execution pattern should be the same

**Comment by JerrySievert** [comment]
that's not going to work in any language.  let me try to break out what's happening for you:

* you have a table named `log_table`
* you have a trigger that is defining an alias of `new_table`
* that trigger does an `execute` of another function which runs in a different context

the aliasing of `new_table` does not enter that second context - you can't access it.  it simply does not exist - you're simply running `SELECT * FROM new_table` - where `new_table` is a literal that you're asking Postgres to find.  the table doesn't exist, it's simply an alias in a different function.

maybe this straight javascript example will help:

```
function foo() {
  console.log(bar('baz'));
}

function baz() {
  const bar = (value) => { return value };
  foo();
}

baz();
```

```
Uncaught ReferenceError: bar is not defined
```

which of course it isn't, they don't share the same context.

as far as I understand, this will never work in any language in Postgres.

**Comment by lbarbula** [comment]
I mean this works right? This is how the postgres documentation recommends writing statement level triggers. So I guess how can I get similar functionality with all of the wonderful tooling that plv8 provides?

```
create or replace function update_record()
   RETURNS trigger
   LANGUAGE plpgsql
AS
$$
DECLARE
    x_rec record;
BEGIN
    raise notice '=operation: % =', TG_OP;
    for x_rec in select * from new_table n left join old_table o on o.id = n.id LOOP
            raise notice 'changed: %', x_rec;
        END loop;
    RETURN NULL;
END;
$$;

CREATE TRIGGER update_trigger
   AFTER UPDATE ON table
   REFERENCING OLD TABLE AS old_table NEW TABLE as new_table
   FOR EACH STATEMENT
   EXECUTE PROCEDURE update_record();
```

**Comment by JerrySievert** [comment]
and you should notice very quickly in their example, that `old_table` and `new_table` are not string literals.  they are in your javascript example.  there's no "magic" in plv8 that converts a string literal that you send to SPI into some other magical value.

also, the example that you posted is executing a `PROCEDURE` which is much different than executing a `FUNCTION` - they are very different things in Postgres.

in postgres parlance, and `PROCEDURE` uses the `CALL` mechanism, which is very different than how a `FUNCTION` is activated, with a `SELECT`.

you can learn more about procedures vs functions in Postgres here: https://www.enterprisedb.com/postgres-tutorials/everything-you-need-know-about-postgres-stored-procedures-and-functions

for more information on how to use triggers and procedures in plv8, see: https://plv8.github.io/#trigger-function-calls

**Comment by JerrySievert** [comment]
your Postgres example:

```
CREATE TRIGGER update_trigger
   AFTER UPDATE ON table
   REFERENCING OLD TABLE AS old_table NEW TABLE as new_table
   FOR EACH STATEMENT
   EXECUTE PROCEDURE update_record();
```

your code:

```
CREATE TRIGGER trigger_update_record
      AFTER UPDATE ON table
      REFERENCING OLD TABLE AS old_table NEW TABLE AS new_table
      FOR EACH STATEMENT
      EXECUTE FUNCTION record_update();
```

notice the invocation difference?

**Comment by lbarbula** [comment]
I do, and it doesn't work executing as procedure either

**Comment by JerrySievert** [comment]
could it be because you're using a string literal?

in your example:

```
const updatedValues = plv8.execute('SELECT * FROM new_table;')
```

this is the same as running `psql` and executing:

```
SELECT * FROM new_table;
```

`new_table` does not exist!  if you want to use a magic value from a trigger, use one of the values provided as per the documentation:

```
const updatedValues = plv8.execute(`SELECT * FROM ${TG_TABLE_NAME};')
```

remember, the examples provided in the Postgres documentation that are specific to the syntax of PL/PGSQL and need to be adapted to the syntax of other languages to work.  you can try to convert this to perl, php, tcl, Lua, any other language that has a different syntax than PL/PGSQL and it will not work using a string literal.  they're different languages, and thus have different rules.  just because it is "javascript inside Postgres" does not mean that all of the javascript syntax is now thrown out the window.
