### ISSUE TITLE
[Q] unrecognized configuration parameter

### ISSUE THREAD

**Issue by FoxyBadger** [plv8/plv8js#500]
Can't find any source code, examples, etc for the following parameters:

1) plv8.boot_proc
2) plv8.context
3) plv8.context_cache_size
4) plv8.max_eval_size

When I try to set any of these parameters I get an unrecognized configuration parameter "plv8.xxxx" error. 
Is the documentation invalid or out of date?
How to use it? Any suggestions?

**Comment by JerrySievert** [comment]
@FoxyBadger can you please provide the version number of plv8 that you are using?

**Comment by JerrySievert** [comment]
also, did you look at the documentation for these?

https://plv8.github.io/#runtime-configuration

**Comment by FoxyBadger** [comment]
@JerrySievert - Yes. I had this question because I saw these parameters in the documentation (at your link) but I could find how to use them.

Version 3.0.0.

I built PLV8 using the following commands:
wget https://github.com/plv8/plv8/archive/v3.0.0.tar.gz
tar -xvzf v3.0.0.tar.gz
cd plv8-3.0.0
make

Is it valid?

**Comment by JerrySievert** [comment]
3.1.4 is the current release, and there were quite a few changes between the 3.0 branch and the 3.1 branch.

I would advise 3.1.

**Comment by robertjpayne** [comment]
This is an old issue but I as well cannot find any reference to these variables in the current release, in v3.1.4 or what AWS currently supports on PG 17 which is 3.1.10.

Not that I necessarily need them I was just trawling the source code to understand how they may impact the runtime performance and notably a search doesn't reveal them either.
