### ISSUE TITLE
[FYI] added plv8 (sandbox) types to DefinetelyTyped

### ISSUE THREAD

**Issue by pkit** [plv8/plv8js#502]
See https://www.npmjs.com/package/@types/plv8-internal

**Comment by JerrySievert** [comment]
nice!

**Comment by JerrySievert** [comment]
I'll try to update docs to point to it, but if I'm too slow or you get a chance, I'd happily accept a PR to them :)

**Comment by pkit** [comment]
Dunno where to add it though. Lol

**Comment by JerrySievert** [comment]
I was thinking maybe here: https://github.com/plv8/plv8/blob/v3.1.4/docs/EXTERNAL.md
