### ISSUE TITLE
V8 version?

### ISSUE THREAD

**Issue by ellisium** [plv8/plv8js#508]
Hello, 

Which V8 version is used? I tried to use string.replaceAll without success (https://v8.dev/features/string-replaceall) so I guess it's an older version.
In addition it should be nice to have setTimeout / setInerval / ect support via V8-juice maybe?

**Comment by JerrySievert** [comment]
current plv8 (3.1.*) is built with v8 9.7.37:

https://github.com/plv8/plv8/blob/r3.1/Makefiles/Makefile.linux#L33

```
postgres=# do $$ a = "foo"; b = a.replaceAll('o', 'p'); plv8.elog(NOTICE, b); $$ language plv8;
NOTICE:  fpp
DO
postgres=# select plv8_version();
 plv8_version
--------------
 3.1.4
(1 row)
```

as for `setTimeout` etc, no, that is not going to happen.  there are some things that do not make sense in what is supposed to be a non-blocking language inside a database, and those are good examples.

**Comment by ellisium** [comment]
Ok thx plv8 version on AWS Aurora is very late 2.3.15 so

**Comment by JerrySievert** [comment]
`6.4.388.40` - it's in the Makefile associated with the tag.
