### ISSUE TITLE
make install errors - MacOS Ventura

### ISSUE THREAD

**Issue by citizenfish** [plv8/plv8js#510]
I am able to build successfully with:-

`make -f Makefiles/Makefile.macos`

**make_install** then fails with:-

`[191/1293] LINK ./bytecode_builtins_list_generator
FAILED: bytecode_builtins_list_generator 
TOOL_VERSION=1668784757 ../build/toolchain/apple/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip --deterministic ../../../../../../../opt/homebrew/opt/llvm/bin/clang++ -B /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/  -Wl,-fatal_warnings -stdlib=libc++ -arch arm64 -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -mmacosx-version-min=10.11.0 -Wl,-ObjC -Wl,-dead_strip -o "./bytecode_builtins_list_generator" -Wl,-filelist,"./bytecode_builtins_list_generator.rsp"    
env: python: No such file or directory
[193/1293] CXX obj/torque_base/implementation-visitor.o
ninja: build stopped: subcommand failed.
make[1]: *** [build/v8] Error 1
make: *** [v8] Error 2`

The error suggests python is not reachable but it runs fine from the command line?

**Comment by JerrySievert** [comment]
you should not be using `make -f Makefiles/Makefile.macos`, there is additional setup and work for plv8 itself in the actual `Makefile`.

you might check that `python3` exists

**Comment by citizenfish** [comment]
Same error when running make from root directory

python3 does exist

**Comment by JerrySievert** [comment]
What does ‘which Python’ give you? Not able to enter backticks on mobile I guess. 

While plv8 is primarily developed on macOS, I have not updated to Ventura yet (I tend to consider .0 releases of macOS to be beta, there have been a huge amount of problems with brew)

**Comment by citizenfish** [comment]
This may be the issue as on Ventura you have to alias it:-

`
which python
`

`python: aliased to python3`

**Comment by JerrySievert** [comment]
Yeah, an alias in a build system isn’t going to work. I’m surprised brew didn’t symlink it instead. I’ll try to start up a Ventura vm later this afternoon, but might not have an answer until later this weekend. In the mean time you might try a symlink and attempting with that instead of an alias.

**Comment by JerrySievert** [comment]
Did you run the step:

brew link python3

?

**Comment by citizenfish** [comment]
It's already linked

Adding a symbolic link causes weirdness:

`sudo ln -s /usr/bin/python3 /usr/local/bin/python`

Follwed by "python" runs an Xcode prompt to install command line tools.

I'll figure out another way

**Comment by JerrySievert** [comment]
Try with brew’s python3.  I’m guessing this was an os update and not a fresh install?

brew install python3
brew link python3

and make sure that the brew version is the first in your path.

**Comment by citizenfish** [comment]
It seems a lot of the plv8 build scripts have:-

`#! /usr/bin/python` or the path to python hard coded

Will this not be the issue?  as /usr/bin is locked down and python being deprecated

**Comment by JerrySievert** [comment]
er, none of the plv8 build scripts should have `#! /usr/bin/python`.  some `v8` scripts, which are not used for the build at all, do.  `v8` downloads pretty much its own whole world to build.

for instance, on my (installed fresh) monterey, there is no system python (`/usr/bin/python`) as apple deprecated including python as part of monterey (and thus ventura) - which is why i asked if this was an os update and not a fresh install.

my `python3` lives in `/opt/homebrew/bin/python3` and the symlink that was created by running `brew link python3` lives in `/usr/local/bin/python` as a symlink to `/opt/homebrew/bin/python3`.

**Comment by citizenfish** [comment]
Thanks for your help Jerry manually creating that symlink for homebrew python has done the trick. I'm not sure why brew refuses to create it on my system.

**Comment by JerrySievert** [comment]
great! glad to hear it.

i’ll still interested in installing ventura in a vm, if there needs to be a documentation change, i’ll go ahead and make it.
