### ISSUE TITLE
Info Request: tzData resource origin for PLV8

### ISSUE THREAD

**Issue by jmedellinc** [plv8/plv8js#511]
Just to confirm:

PLV8 uses the same tzData database that was compiled into postgres?

Or does it compile its own?

Thanks..

PS. Couldn't find reference to the implementation browsing the source

**Comment by JerrySievert** [comment]
Depends.

which specific part are you referring to?  Data conversion, internal JavaScript dates, etc.

**Comment by jmedellinc** [comment]
We're working with timestamp (bigInt epoch timestamps) conversion to dates (local date, hours, minutes, day of week) based on timezone names using the toLocaleString() javascript method with options: {timeZone:${timezone}} and doing string manipulation for extracting the data..

Wondering if doing this on Date objects on plv8 could diverge from using the extract method of postgres' SQL..

Regarding of course Daylight Savings Times and their constant changes..

**Comment by JerrySievert** [comment]
I can get you a _better_ answer tomorrow (it's getting late here, and I need to look more closely at how both v8 and pg deal with _presentation_ of timezones), but when doing any date/time conversions, plv8 itself uses the epoch and uses methods on each side to convert to/from dates via the epoch.

if memory serves, v8 will use system timezone libraries.  for postgres, it depends on how it was configured (see `--with-system-tzdata=`)

so, you should be good, but you can test empirically by finding a divergence between the os timezone libraries and whenever v8 was compiled for plv8, and set your clock to it, but I'm 97% confident that they'll be using the same source of truth: the os.

**Comment by jmedellinc** [comment]
Thanks..  You gave me some ideas and I have now some more info to further the context of my question..

I couldn't find guidance on how v8 implements it, but I could find for instance that NodeJS builds its own tzData at buildTime
https://stackoverflow.com/a/55478608
https://github.com/nodejs/node/issues/44333

Also, I know for a fact that chrome also doesn't use the system tzData information.
Here in mexico, the DST law just changed, osx received the new tzData, but chrome still uses the previous DST settings..

That makes me think that maybe the way V8 consumes tzData depends on the implementation (thinking of NodeJS, chrome..)

PS. Thanks for the heads up on postgres.. Will have to figure out how my (third party cloud based) postgres version was built..

**Comment by JerrySievert** [comment]
hm.  the addition of a database hosting provider raises more questions for me - is it AWS (RDS/Aurora)?  if so, I'll need to look at much older versions of plv8, which are using much older versions of v8.

**Comment by JerrySievert** [comment]
also, plv8 gives the ability for you to build with v8's third party icu library via enabling i18n, but that is generally disabled for all build unless specifically enabled at compile-time.  without it, v8 disables i18n and should use the system icu.

see: https://github.com/plv8/plv8/blob/r3.1/Makefiles/Makefile.linux for modern, and https://github.com/plv8/plv8/blob/v2.3.14/Makefile#L21-L23 for older versions.

**Comment by jmedellinc** [comment]
Great

With that guidance I will verify on my provider (supabase) how they are compiling postgres and the plv8 extension.. or which versions they’re using. 

Now that I think about it.. Is there a way to query the plv8 extension to check its build config?

**Comment by JerrySievert** [comment]
for version, it _depends_ (gotta love the power of that word).

for older versions:

```
DO $$ plv8.elog(INFO, plv8.version); $$ LANGUAGE plv8;
```

for newer version:

```
SELECT plv8_version();
```

but, there is no methodology currently for determining build configuration - maybe something to add in the future.

unfortunately, I have no insight into how supabase builds and hosts extensions, so I can't give much more insight, but if you get a version I can likely help you a little more in your quest.

**Comment by jmedellinc** [comment]
The oh so (in?)famous _depends_ 
hehe

Thanks. Will report back with findings and/or if I need help

**Comment by JerrySievert** [comment]
awesome, I'd love some closure - would be great to know what their versions/builds are.

besides, it's a great question that I'd like have a good answer to.

**Comment by JerrySievert** [comment]
btw, when you get a version I'm happy to continue looking into this.

**Comment by jmedellinc** [comment]
You’ll get it for sure 👍🏼👍🏼👍🏼

**Comment by JerrySievert** [comment]
just one more thing to note.

if you're planning on staying in an unknown environment for timezone source of truth, it might be worthwhile importing your own copy into your database and keep it updated, then use that as the source of truth via a sql query.  at that point, you have full control.  you could memoize it in plv8, or access it in pl/pgsql, or even via a fairly complicated sql statement.

it would give you a whole lot more control without relying on an opaque upstream provider.

**Comment by jmedellinc** [comment]
Closure! (kind of hehe)..
@JerrySievert 

THE THING: The "source of truth" rang a bell.. Set me in the right track:
  This is a big deal for me (it's an appointments app).  So better take control of it.  Relying on third party/upstream methods is going to be unreliable to say the least..

The solution? Just as you said: implement a quasi-library in plv8 and avoid all extract methods in postgres.  **Do everyting Timezone related in plv8**

The quasi-library is based on [https://github.com/kshetline/tubular_time](url) and uses tzData directly.

It's partially implemented now, but once I'm more into it, what I'll do is:
 * save the minified "library" in a "js_libraries" table
 * implement a "require" method in plv8_init() which will query such table and returns the proper libraries..
 * ..?
 * profit! (hehe)

I'm using this same quasi-library in our NodeJS implementation and with such control I'll even be able to eventually make comparisons between the users' fronteds and this implementation (which basically will always be more current)..

Must add that the quasi-library has actually been way more helpful than the built-in methods.. For instance: I now know exactly when DST transitions happen.. beautiful.. No more searching..

I'm developing the function on a local javascript nodeJS project calling the remote procedures as needed so there's no real urgency in implementing the "js_libraries"..  Let me know if you see another way forward..

Way way cleaner.. (At least it feels that way)

José..

**Comment by JerrySievert** [comment]
fantastic!  glad you were able to come to a good solution, and thank you very much for updating with what you went with.

for a require library, it might be worth looking into https://plv8.github.io/#plv8ify or  https://github.com/JerrySievert/plv8-modules, if for nothing else, inspiration.  might save you some time and effort.
