### ISSUE TITLE
postgres 14 make fail

### ISSUE THREAD

**Issue by zouchengli** [plv8/plv8js#518]
root@2ce93524d63b:/plv8# make
make -f Makefiles/Makefile.linux v8
make[1]: Entering directory '/plv8'
Setting up build directory
Downloading LLVM
Downloading gn source
fatal: destination path 'build/gn' already exists and is not an empty directory.
make[1]: *** [Makefiles/Makefile.linux:25: build/gn/out/gn] Error 128
make[1]: Leaving directory '/plv8'
make: *** [Makefile:58: v8] Error 2

**Comment by JerrySievert** [comment]
looks like your build was killed/stopped during the v8 portion of the build.  v8 really doesn't like that happening.  try `rm -rf build` and then start make - unfortunately it will have to download v8 sources again, but should get you on track.
