### ISSUE TITLE
BigInt serialisation error

### ISSUE THREAD

**Issue by JulienLecoq** [plv8/plv8js#521]
BigInt cannot be serialized (tested with v3.1.5). I'm using this extension with Supabase and every time I try to select an id which is of type int8 (BigInt), I get: "TypeError: Do not know how to serialize a BigInt"

**Comment by JerrySievert** [comment]
thanks for the report!  I was able to replicate with the following:

```
DO $$ id = plv8.execute('SELECT 23::int8'); plv8.elog(NOTICE, JSON.stringify(id)); $$ LANGUAGE plv8;
ERROR:  TypeError: Do not know how to serialize a BigInt
```

in the short term, you can cast the field to type `NUMERIC`:

```
 DO $$ id = plv8.execute('SELECT 23::int8::NUMERIC'); plv8.elog(NOTICE, JSON.stringify(id)); $$ LANGUAGE plv8;
NOTICE:  [{"numeric":23}]
```

it's not a perfect fix, but when dealing with type `NUMERIC` plv8 tries its best and should get you up to `Number.MAX_SAFE_INTEGER`, which should be `9007199254740991`.

I'll try to get it fixed this weekend.  not sure how long it will take supabase to update after a release, but I'll leave this issue open until they're able to update.

**Comment by JulienLecoq** [comment]
Thanks for the very quick response, and for the temporary quick fix!

Can't we update the extension ourself with something like ``ALTER EXTENSION plv8 UPDATE TO `3.1.6`;`` (I don't know anything about extension versioning) after you fix the issue?

**Comment by JerrySievert** [comment]
> Can't we update the extension ourself with something like ALTER EXTENSION plv8 UPDATE TO `3.1.6`; (I don't know anything about extension versioning) after you fix the issue?

likely yes, as long as supabase updates the plv8 version available (sorry, I don't know the specifics of how supabase deploys postgres, so am taking a guess here).  how, when, and how often it gets updated is opaque to me.

**Comment by JulienLecoq** [comment]
Ok no problem 👌🏻
I just checked, the fix is working perfectly! 😊

**Comment by JerrySievert** [comment]
like I said, should be ok up until `9007199254740991`, but I don't know your data so that could mean decades or hours 😂 

hopefully you will be using a new version before that happens.

**Comment by JerrySievert** [comment]
hm, my reproduction attempt was incorrect - the issue is that `BigInt` cannot be serialized, and that is indeed correct.

are you able to create a reproduction real quick so that I can point you in a better direction?

**Comment by pkit** [comment]
BigInt is not serializable to JSON in the generic sense. So I'm not sure what's this about. :)

**Comment by pkit** [comment]
On the side note, I'm happy that Supabase finally started using plv8. As my idea was always to create a Firebase competitor using plv8.

**Comment by JerrySievert** [comment]
@pkit nice!  and yeah, took me a little bit to remember it was `BigInt`.

I only know supabase peripherally, haven't spent any time in their stack.  too busy with my own work :)
