### ISSUE TITLE
Please clarify status of Windows build

### ISSUE THREAD

**Issue by serefarikan** [plv8/plv8js#526]
First of all: I appreciate plv8 is an open source project with a few people heroically doing all the work. 
Acknowledging that, I spent about two days trying to get the windows build working before asking for help, but I got properly stuck. 

This [comment](https://github.com/plv8/plv8/issues/444#issuecomment-966802813) by @JerrySievert makes me think 3.1 should build under Windows. 

I went as far as installing a new Windows 10 build machine for this, installed vs 2017, then the dependencies. 
I checked out v3.1 branch, specifically the tag `v3.1.1` Building v8 was a pain, because it requires a specific version of windows sdk (10.0.19041.0) but I managed to get that working.  

I patched the header in postgres 14 as per the readme, but plv8 code itself won't build, which is where I began to have problems.  I had to modify paths in `CMakeLists.txt` because the current location of files referred to in that file do not match the expected location.  (see https://github.com/plv8/plv8/issues/443) After that, I had to modify `plv8.h` and move `#include "postgres.h"` to the top of the file because otherwise there's a duplicate definition, [also breaking another extension](https://trac.osgeo.org/postgis/ticket/4877).

But this is not enough, because I was getting `expression did not evaluate to a constant` which made me think I should give this a try with vs 2019. Which I did, but then I am still left with: `plv8.cc(626,12): error C3863: array type 'char *[size]' is not assignable` (multiple occurances). 

So my understanding is, at some point plv8's window build became obsolete, but I am confused because the issue I referred to above has a comment that indicates 3.1 should work even with postgres 14. 

I am keen to use plv8 for a new project which will be deployed on prem, and the customer is strongly invested in Windows. I'd love to be able to offer postgres 14 but I am really stuck at this point given my very rusty C++ skills. 

I'd understand if Windows support is deprecated, so may I please ask for some clarification?

**Comment by JerrySievert** [comment]
> I checked out v3.1 branch, specifically the tag v3.1.1

you should be trying this against `3.1.5`, not `3.1.1`, there have been code changes in the year between those versions.  but, I still cannot guarantee that it will compile under windows.

I make an effort to make sure that it compiles under all platforms, but the windows build was a contributed build and I do not have a Microsoft based device to built it.

> After that, I had to modify plv8.h and move #include "postgres.h" to the top of the file because otherwise there's a duplicate definition, [also breaking another extension](https://trac.osgeo.org/postgis/ticket/4877).

different compiler, unrelated issue.

> I am keen to use plv8 for a new project which will be deployed on prem, and the customer is strongly invested in Windows. 

then plv8 might not be the extension for them.  if you must, I suggest trying under WSL if attempting to compile with a more modern version of plv8 fails.

**Comment by serefarikan** [comment]
Thanks @JerrySievert . I think I get the picture, and I completely understand, especially the windows build being a contributed build. I will give `3.1.5` a try just out of curiosity, but I think it's best if I assume plv8 supported under Linux going forward. I think I'll have a conversation with the potential customer and see how it goes. 

Just to clarify, when I referred to issue with `postgres.h` include, I was having the exact same error with msvc, I added the link to that issue since it contained the details. Probably does not matter though given your clarifications. 

If I had more familiarity with C++ I'd gladly keep an eye on the Windows build but it is beyond my skill set to be of help with issues related to differences between  linux and windows c++ toolchains 😞 

Once again, thanks for taking the time to respond.

**Comment by JerrySievert** [comment]
> differences between linux and windows c++ toolchains

unfortunately, one of the big differences is that g++ and clang++ work really hard to keep up with the standards.  msvc does not seem implement the standards it claims to support.  which is specifically what that error is.

**Comment by JerrySievert** [comment]
I have update the docs and https://plv8.github.io/ to hopefully clarify the current status on windows.

**Comment by serefarikan** [comment]
My late but genuine thanks @JerrySievert
