### ISSUE TITLE
Statements cancelled under some conditions result in process hanging at 100% CPU until database restart

### ISSUE THREAD

**Issue by alessbelli** [plv8/plv8js#528]
This seems to be a regression introduced in 2.3 -> 3.1 but it's not yet clear what causes it - it could have to do with signal propagation and proper termination of processes - in practice some complex situations which I'm still in the process of simplifying for investigation, have a critical bug where either a function call hangs forever by itself, or hangs forever upon when sending a SIGINT to it.

The simplest repro case is this:

```sql
CREATE OR REPLACE FUNCTION inner() RETURNS VOID AS $$ plv8.execute('SELECT pg_sleep(10)') $$ LANGUAGE plv8
CREATE OR REPLACE FUNCTION outer() RETURNS VOID AS $$ plv8.execute('SELECT inner()') $$ LANGUAGE plv8
SELECT outer()
```

this will complete within 10 seconds if uninterrupted, but will hang with high CPU if interrupted with a sigint.

**Comment by JerrySievert** [comment]
thanks! I'll take a look at this as soon as I can.

**Comment by alessbelli** [comment]
repro on blank docker `sibedge/postgres-plv8:15.2-3.1.5` if it helps, thank you for looking into this!

**Comment by alessbelli** [comment]
I am still trying to isolate a third problem which looks similar to this, but happens on its own with some complex sequence of nested plv8 calls, errors thrown from inside execute calls, and subtransactions, as well as a fourth problem that causes a crash under similar loads - I think it all has to do with signal propagation (but no strong evidence yet).

Hopefully I can get some decent test cases for the other 2 failure modes!

**Comment by JerrySievert** [comment]
thanks again for the great repro, I was able to reproduce it locally, and it was indeed related to signal propagation, in that the signal handlers were being set multiple times on serial calls (plv8 functions being called by select from plv8 functions).

hopefully, this fix will end the interrupt handling issues that have been popping up, and I'd love to hear if this fixes your other two failure modes.  if not, if you do manage to get a reproducible case you can share, it should be a quick fix.

**Comment by JerrySievert** [comment]
as noted in your other issue, v3.1.6 should address this.

**Comment by alessbelli** [comment]
This is great stuff, thank you! We'll be trying this out as soon as we can (basically as soon as we can get the new version installed locally).

**Comment by alessbelli** [comment]
OK I am currently play-testing this, and it seems like this works for sigint propagation, but now fails to halt long-running plv8 commands like
```sql
DO $$
const start = Date.now()
let i = 0
while (Date.now() - start < 10000) {
    i+= 1
}
plv8.elog(NOTICE, i)
$$ language plv8;
```
(I think that this is a thing that was present in plv8 2.3 and which fix started this whole regression chain around interrupt signals)

Will look for other problems if they arise in my testing
