### ISSUE TITLE
Document or add backwards-compatible execute functions with plv8 3+ BigInt breaking change

### ISSUE THREAD

**Issue by alessbelli** [plv8/plv8js#529]
Crawled through the various commits/release notes around v3, and it seems like the introduction of BigInt support is a highly breaking change, which I believe should be bypassable or at least documented a bit more - normal JS numbers are much more flexible and interoperable (namely, they serialize to JSON as numbers, can be mixed with other non-bigints... ) than postgres bigint.

Therefore, I think it's a very common case to have bigint columns used as normal numbers in plv8 pre-v3 (within known javascript normal number constraints).

Converting all plv8 calls to bigints is extremely tedious, and sometimes not possible, so as a migration path it would be very helpful to offer backwards-compatible function pairs (cursor.fetch and plv8.execute) that parse bigint columns/structured fields as numbers, not BigInt.
This could be `cursor.fetch({ noBigInt: true })` parameter-based and a `plv8.execute_legacy` (unless there's a better way to support the mixed signature with `plv8.execute(query, ...params)` /  `plv8.execute(query, paramsArray, { noBigInt: true })` )

Short of this, documenting the breaking change more explicitly in the README with patch suggestions (replacing all BigInts found in the response to plv8.execute) would make it much easier to discover when upgrading.

**Comment by JerrySievert** [comment]
there was a large amount of discussion a few years ago when the change was made.

if you prefer a more broken approach, which will fail once `9007199254740991` or `-9007199254740991` are hit, you can compile with:

`make BIGINT_GRACEFUL=1` (see https://github.com/plv8/plv8/blob/r3.1/plv8_type.cc#L947-L953)

but, there will not be a way to bypass it completely, especially 2 years after the change was made.  that would return incorrect results, and was a *MUCH* bigger issue.

**Comment by JerrySievert** [comment]
I will note that plv8 stayed in alpha state with the BigInt changes for almost 2 years before it was released 2 years ago, so this change has existed for 4 years, with 2 of those years open to feedback and change.

**Comment by alessbelli** [comment]
I understand, which is why my main suggestion is about documenting the breaking change at this point.
Unfortunately we are subject to AWS RDS migration cycles, and as such cannot compile with different flags, nor upgrade at will, which is why we were this late to the upgrade (RDS just introduced plv8 v3 2 weeks ago!)
