### ISSUE TITLE
Array literal rejected for array parameter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [plv8/plv8js#53]
```
What steps will reproduce the problem?

do language plv8 $$ plv8.execute("select $1::int[]",['{1,2,3}']); $$;


What is the expected output? What do you see instead?


get:

ERROR:  Error: value is not an Array

should get no error


Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `AMDuns...@gmail.com` on 19 Feb 2013 at 1:43

**Comment by svendpeter** [comment]
Hi ,
Is plv8 accepting complex types as parameter in functions ?

create or replace function sortAndOrder(start int, page int, filter_By filter_By[], sort_By order_By[]) returns catalog as
$$
plv8.elog(NOTICE, sort_By);
if (typeof filter_By == "undefined") {
var sort = [{field: "naam"}];
    if (typeof sort_By != "undefined") {

        var query = "select * from abc.relations ORDER BY  ' + sortBy[0].field +"  DESC limit  " + start + "OFFSET "+ page ;
        var a = plv8.execute(query);


    return a;}
}
$$
language plv8 stable



"message": "ReferenceError: sort_By is not defined",
Can you tell me what  I am doing wrong ?

**Comment by JerrySievert** [comment]
yes, the issue is that you cannot access the variable by a case-sensitive name.

see https://github.com/plv8/plv8/issues/252 for more explanation.

**Comment by svendpeter** [comment]
thanks !!
