### ISSUE TITLE
Consider https://database.dev/ for package distribution

### ISSUE THREAD

**Issue by claytongulick** [plv8/plv8js#532]
Just saw on HN that Supabase has created a npm-like package manager for PG, database.dev.

Seems like this might be a great way to ease the pain of distros dropping support for prebuilt packages?

**Comment by JerrySievert** [comment]
I can definitely look into it, I saw the HN announcement as well.

I just started adding it back to PGXN, so hopefully they and @theory can get something that works well in both places!

**Comment by theory** [comment]
Some Supabase people have reached out to me in the last few weeks, and I sent them some info, but so far I don't know much about it. Doesn't seem like it supports extensions that need to be compiled, though, only pure SQL extensions. At least for now. Looking forward to learning more at PGCon next month.
