### ISSUE TITLE
How to raise a notice using options

### ISSUE THREAD

**Issue by psirenny** [plv8/plv8js#534]
I'm trying to raise a notice using options like in the following SQL example:

```sql
RAISE NOTICE 'message'
USING
  ERRCODE = 'OPMSG',
  DETAIL = json_build_object('foo', 'bar')::text;
```

Is there a way to achieve something like the above in PLV8? Perhaps something like this:

```js
plv8.elog(NOTICE, "message", {
  ERRCODE: "OPMSG",
  DETAIL: { foo: "bar" },
});
```

**Comment by JerrySievert** [comment]
you can only output strings via `elog`, but essentially `RAISE` just gives you a template.  you can create your own templates and call them.  for example, in your startup proc:

```
plv8.raise = function(level, message) {
  let error_message = '';
  if (message.detail) {
    error_message += `DETAIL: ${message.detail}`;
 }

 [...]

  plv8.elog(level, message);
}
```

this would duplicate some of the work that `RAISE` does, but plv8 explicitly does not give access to `ereport()`, just `elog()` (see https://www.postgresql.org/docs/current/error-message-reporting.html)

**Comment by psirenny** [comment]
Sorry for being dense 😅. How does the `error_message` variable end up getting used in that example? Just in case it's helpful, I should have mentioned that I'm trying to follow instructions for this [PostGraphile plugin](https://github.com/graphile/operation-hooks#sql-notices). The plugin checks a (Node.js) Postgres client's parsed error message to see if its `code` property equals **OPMSG**.

I started looking at how the Postgres client parses messages to see if I could construct a string that would be interpreted as having details and a code. But so far no luck. I'm probably overthinking this. It's worth pointing out that the term **message** takes on two meanings so it gets confusing. There is the short message description set by `elog(level, messageDescription)`. Then there is also a larger message that includes the description as well as metadata like the `code` and `detail` properties that I'm trying to set.

**Comment by JerrySievert** [comment]
> How does the error_message variable end up getting used in that example? 

sorry, I mean `plv8.elog(level, error_message);` but typed too quickly.

> The plugin checks a (Node.js) Postgres client's parsed error message to see if its code property equals OPMSG.

what you're looking for is [ereport()](https://www.postgresql.org/docs/current/error-message-reporting.html) which as I noted plv8 explicitly does not support.  you might be able to raise by calling out to a plpgsql function via `plv8.execute()` but I can't help you with how to do that.

otherwise, you have `plv8.elog`

**Comment by psirenny** [comment]
> what you're looking for is [ereport()](https://www.postgresql.org/docs/current/error-message-reporting.html) which as I noted plv8 explicitly does not support. you might be able to raise by calling out to a plpgsql function via plv8.execute()

Ahh, that makes sense. I managed to achieve what I was looking for by enclosing the code in a plpgsql function that performs the `RAISE` instead. So all is now working. Thanks again for your help!
