### ISSUE TITLE
Undefined symbol Ubuntu 22.04 PLV8 2.3.15

### ISSUE THREAD

**Issue by balbaev** [plv8/plv8js#535]
Hi!
I've built PLV8 2.3.15 with ICU support in Ubuntu 22.04, but unfortunately extension refuses to be created with the following error:
```
ERROR:  could not load library "/usr/lib/postgresql/14/lib/plv8-2.3.15.so": /usr/lib/postgresql/14/lib/plv8-2.3.15.so: undefined symbol: _ZN6icu_608ByteSinkD2Ev
```
PLV8 was built with the following command:
```
make EXECUTION_TIMEOUT=1 USE_ICU=1
```

I've got no errors building PLV8 2.3.15 without ICU support.

Appreciate for any help.

**Comment by JerrySievert** [comment]
the symbol translated is: `icu_60::ByteSink::~ByteSink()`

I'll try to take a look this evening and see what is currently missing in the link step.

**Comment by JerrySievert** [comment]
I'm not sure what the issue is, but I'm happy to help you try to debug it.

I just built a fresh ubuntu 22.04 vm (amd64), installed the `build-essential`, and added the pgxn postgres 15 package.

I did the same
```
make EXECUTION_TIMEOUT=1 USE_ICU=1 
```

```
postgres@build-test:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
postgres=# create extension plv8;
CREATE EXTENSION
postgres=# select plv8_version();
 plv8_version
--------------
 3.1.6
(1 row)

postgres=# do $$
const name1 = '\u0041\u006d\u00e9\u006c\u0069\u0065';
const name2 = '\u0041\u006d\u0065\u0301\u006c\u0069\u0065';
plv8.elog(NOTICE, `${name1}, ${name2}`);
$$ language plv8;
NOTICE:  Amélie, Amélie
DO
```

this is what I have installed as far as ICU:

```
i A icu-devtools - Development utilities for International Components for Unicode
i A libicu-dev - Development files for International Components for Unicode
i A libicu70 - International Components for Unicode
```

is there a test case that maybe I'm missing?

are you on arm64?  I can build a vm for that as well and give it a try.

**Comment by JerrySievert** [comment]
it looks like the version of icu that ubuntu 22.04 supports (70.1) has removed the deconstruction for `ByteSink` in favor of a `virtual ~ByteSink()`.  so,  it's just not going to work with that version of icu.

is there a reason you're not on a more modern version of plv8 (and thus v8)?  we're currently up to `3.1.6`, which I was able to compile with`make EXECUTION_TIMEOUT=1 USE_ICU=1` and appeared to work as intended.


https://github.com/unicode-org/icu/blob/release-70-rc/icu4c/source/common/unicode/bytestream.h#L64
