### ISSUE TITLE
Any best practice for using plv8 ?

### ISSUE THREAD

**Issue by wenerme** [plv8/plv8js#538]
Build some large js into plv8 function, the first problem I meet is re-execute whole code, I solved by

```sql
create or replace function my_function(name text,options jsonb default jsonb_build_object()) returns jsonb immutable strict as $JS$

if(globalThis.my_function)return globalThis.my_function(name,options);

// Real code

globalThis.my_function = my_function;
return globalThis.my_function(name,options);

$JS$ language plv8;
```

- 4500 loc, alot json (import './data.json')
  -  300ms/exec ->  3ms/exec

---

My another practice is how to build the function

```makefile
my_function:
	pnpm esbuild --format=cjs --charset=utf8 --legal-comments=external --bundle --define:process.env.NODE_ENV=\"production\" --define:__DEV__=false \
		--minify-syntax \
		--minify-whitespace \
		--outfile=dist/my_function.cjs \
		--banner:js='const module = { exports: {} }' \
		./src/functions/my_function.ts
	echo 'create or replace function my_function(name text,options jsonb default jsonb_build_object()) returns jsonb immutable strict as $$JS$$' > dist/my_function.sql
	pnpm prettier --write dist/my_function.cjs
	echo 'if(globalThis.my_function)return globalThis.my_function(name,options);' >> dist/my_function.sql
	cat dist/my_function.cjs >> dist/my_function.sql
	echo 'globalThis.my_function = my_function' >> dist/my_function.sql
	echo 'return globalThis.my_function(name,options);' >> dist/my_function.sql
	echo '$$JS$$ language plv8;' >> dist/my_function.sql
	cp dist/my_function.sql ./db/migrations/100001_my_function.sql
```

I wonder, is there any best practice for using plv8 more effectively?

**Comment by JerrySievert** [comment]
have you considered using [the startup procedure](https://plv8.github.io/#start-up-procedure)?

you can store on the `plv8` global object, and it will be available.

also, there is https://plv8.github.io/#-code-plv8-find_function-code-

**Comment by wenerme** [comment]
@JerrySievert Thanks, have considered start_proc before.

But start_proc is hard to maintain, depends on global var,  it's error prone when using the function. start_proc can avoid re-execute, but I really don't want to use a global var for this.

I think find_function is just invoke another function, I wish I could have some laze loading `find_function`, like `globalThis.my_function ??= eval('find_script')`. Maybe I can use `find_function` to avoid shared code between multi function, but I don't thinks `find_function` can avoid re-execute the code.

---

Code like this

```
if(globalThis.my_function)return globalThis.my_function(name,options);
```

also depends on global var `plv8.context`, but this is transparent to user, as long as the code don't mess with global state, it's ok to use previous function instance.

**Comment by JerrySievert** [comment]
just beware the scope of the global instance:

* empty on first connection
* destroyed on connection close

you can also use sql itself, and store everything in the database.  that methodology was used for https://github.com/JerrySievert/plv8-modules

**Comment by wenerme** [comment]
Thanks, I'll adopt the plv8-modules for my current usage.

I can accept the initial slowness, but is there any way to truly make it global and survey the connection closure?

You can close this issue or keep it open for further practices.

**Comment by JerrySievert** [comment]
not possible, postgres uses a forking model, so each connection is its own process.

going to close, there are multiple copies of this type of question already in the archives.
