### ISSUE TITLE
plv8 function that returns a bytea is incorrectly returning previous invocations results 

### ISSUE THREAD

**Issue by husseinhere** [plv8/plv8js#539]
plv8 `3.1.4`on `PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by Debian clang version 12.0.1, 64-bit`

This is quite a weird issue, and I've tried hard to make more minimal examples -- but I've struggled to narrow it down.

1. Define the `init_plv8()` function that loads some functions into plv8 context: https://gist.github.com/husseinhere/66f9039d5b28a07197ee15ef7ad27698
2. Run `SELECT init_plv8();`  to load the functions required into `plv8` object

Now define this function, which will show the bug:
```
CREATE OR REPLACE FUNCTION test(arg json)
RETURNS BYTEA AS
$$

   plv8.elog(NOTICE, 'arg', JSON.stringify(arg)); 
   const bytes = plv8.verifier.Wager.encode(arg).finish();
   plv8.elog(NOTICE, 'bytes: ' + bytes);
   return bytes;
$$ LANGUAGE plv8;
```

So let's call the function:
`SELECT encode(test('{ "vhempCrash": { "gameId": 25 } }'::json), 'hex') ;`

`2a020819` which is correct. If you see plv8 will also log: 
```
NOTICE:  arg {"vhempCrash":{"gameId":25}}
NOTICE:  bytes: 42,2,8,25
```

Again, this is correct. Perfect. 

Now, lets try with a different `gameId`:

`SELECT encode(test('{ "vhempCrash": { "gameId": 26 } }'::json), 'hex') ;`

which returns `2a020819`  which is **wrong** that is a cached value from the last time!  So lets see see the log:

```
NOTICE:  arg {"vhempCrash":{"gameId":26}}
NOTICE:  bytes: 42,2,8,26
```

Which is **correct*. So in javascript, it's actually doing the correct thing. But it's at the interface between plv8 and postgres that it's caching the incorrect value.

This bug also completely goes away if you replace `return bytes` with `return new Uint8Array(bytes)` if that helps.

**Comment by JerrySievert** [comment]
thanks for the report!

a thought about narrowing it down - you said that on the javascript side the bytes appear to be correct, but that they aren't getting translated correctly?  you should just be able to set the bytes as a byte array and return them.

you should be able to get a byte sequence directly from postgres like we do in the tests: https://github.com/plv8/plv8/blob/r3.1/sql/bytea.sql#L26-L27 and return that, or create a static `ArrayBuffer` and return that.

**Comment by husseinhere** [comment]
> a thought about narrowing it down - you said that on the javascript side the bytes appear to be correct, but that they aren't getting translated correctly? 

That's right, it's correct on the javascript side. But then its incorrectly cached. i.e.The first time,  no matter what arguments you give `test`, it will always work correctly. But then from then on, it'll always (incorrectly) return the same value. 

> or create a static ArrayBuffer and return that

Yeah, I mean, it's very easy to work around. But I think there's a bug somewhere in plv8 that should be addressed

**Comment by JerrySievert** [comment]
while it is entirely possible that a bug exists somewhere in plv8, unless you can come up with an actual test-case, there is nothing I can do.  an 8000+ line function is not a test-case.  I can again try to help you come up with one, but not with what you've provided.

**Comment by husseinhere** [comment]
It can be reproduced pretty easily. The `test()` function is only a couple lines of code. 

```
   plv8.elog(NOTICE, 'bytes: ' + bytes);
   return bytes;
```

You can see it'll log the correct value. You can check that bytes is a Uint8Array. Yet when it gets to postgres, it'll return an incorrectly memoized version. 

I'll try narrow it down more, but I feel it's pretty strong evidence of a bug in plv8.

**Comment by JerrySievert** [comment]
as I noted, 8000+ lines is not a test-case.  I am happy to look at a small, reproducible test-case, though.

I pointed to the actual tests as an example of what would be a test-case.

**Comment by husseinhere** [comment]
Ok. I've narrowed it down. I'll create a new issue
