### ISSUE TITLE
simple variables in template literals

### ISSUE THREAD

**Issue by markymarrow** [plv8/plv8js#542]
variables do not seem to resolve correctly in template strings.

Take, for instance:
```
CREATE OR REPLACE PROCEDURE public.testfn(a int) AS $$
  var b = 'foo';
  var c = {x: 'bar'};
  var s = `some things ${a} and ${b} and ${c} and ${c.x}`;
  plv8.elog(NOTICE, s, a, b, c.x);
$$
LANGUAGE plv8;

call testfn(7322);
```
I get the following output:
`some things NULL and NULL and NULL and bar 7322 foo bar`

rather than the expected
`some things 7322 and foo and [object Object] and bar 7322 foo bar`

I'm running on aurora serverless v2 postgres v15.2
plv8 version is 3.1.4

**Comment by JerrySievert** [comment]
this works as expected on real plv8 running on real postgres:

```
postgres=# CREATE OR REPLACE PROCEDURE public.testfn(a int) AS $$
  var b = 'foo';
  var c = {x: 'bar'};
  var s = `some things ${a} and ${b} and ${c} and ${c.x}`;
  plv8.elog(NOTICE, s, a, b, c.x);
$$
LANGUAGE plv8;
CREATE PROCEDURE
postgres=# call testfn(1234);
NOTICE:  some things 1234 and foo and [object Object] and bar 1234 foo bar
CALL
```

unfortunately, amazon did not contribute back any changes they made for aurora, so given that it works on actual plv8 you will need to contact them for support.

**Comment by markymarrow** [comment]
Ah, it never crossed my mind that Amazon may have dabbled and broken things.
Thanks.
