### ISSUE TITLE
Compatibility with Postgres 16

### ISSUE THREAD

**Issue by Deltaus** [plv8/plv8js#543]
Tried building it with latest postgres 16 but saw some errors like
```
plv8.cc: In function ‘plv8_context* GetPlv8Context()’:
plv8.cc:2015:53: error: cannot convert ‘text* {aka varlena*}’ to ‘const char*’ for argument ‘1’ to ‘Datum CStringGetDatum(const char*)’
     fake_fcinfo->args[1].value = CStringGetDatum(arg);
                                                     ^
plv8.cc: In function ‘v8::Local<v8::Value> DoCall(v8::Local<v8::Context>, v8::Handle<v8::Function>, v8::Handle<v8::Object>, int, v8::Handle<v8::Value>*, bool)’:
plv8.cc:863:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [plv8.o] Error 1
```
May I know when we can expect a PG16 compatible version to be released? Thank you!

**Comment by JerrySievert** [comment]
> May I know when we can expect a PG16 compatible version to be released? Thank you!

I should have some time available next week.  how long it will take will be based on how many changes were made in pg16.

**Comment by JerrySievert** [comment]
turned out it was easier than I expected.  3.1.7 is released, and works with pg16beta1
