### ISSUE TITLE
Upgrade from 2.3.12 to 2.3.15 failed in Postgresql v11.18

### ISSUE THREAD

**Issue by zthhhhh** [plv8/plv8js#547]
I have installed 2.3.12 and 2.3.15 in the library directory, and I want to upgrade plv8 from 2.3.12 to 2.3.15,this error occurs.
![image](https://github.com/plv8/plv8/assets/35291135/b177ab18-0ece-470a-a450-19d7aed258bb)

![image](https://github.com/plv8/plv8/assets/35291135/793a1bbc-f31c-4b20-9cc1-d7e2820b61f5)

**Comment by JerrySievert** [comment]
it's a known bug, but should not affect the upgrade.  when you connect next to postgres, you should see that it is the new version.
