### ISSUE TITLE
Excited to Start working with 3.2alpha Branch

### ISSUE THREAD

**Issue by luss** [plv8/plv8js#549]
Hi Jerry,

I'm gonna try out the 3.2Alpha branch for pgEdge binaries.  I'll be building it on Rocky Linux 9 in both the AMD64 and Arm64 flavors.  I'll submit a pull request with my (hopefully) succesfull additions on how to build on EL9.

**Comment by JerrySievert** [comment]
awesome!  there's still a little bit more stuff that needs to be done before release, hopefully most can be accomplished this weekend.

**Comment by JerrySievert** [comment]
3.2 released!
