### ISSUE TITLE
Invalid Discord link?

### ISSUE THREAD

**Issue by andreas** [plv8/plv8js#550]
The Discord link added in d7628dfbee0e56a73fe63a308a1de39cf003333f (`https://discord.gg/5fJN52Se`) appears to be invalid 🤔 

I get the screen below when visiting the link:

<img width="1791" alt="Discord" src="https://github.com/plv8/plv8/assets/2518/4dafcc6a-dc5f-4e31-b0fc-6d64b8f67e00">

**Comment by JerrySievert** [comment]
oof.   I'll try to get a permanent link up soon, but for now: https://discord.gg/NBCdtsrz

**Comment by JerrySievert** [comment]
updated.  the new link that is in the readme should not expire.

thanks for the report!
