### ISSUE TITLE
Many warnings when building v3.2.0

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#554]
When building V3.2.0 on Linux I get many messages like that:

<img width="1424" alt="image" src="https://github.com/plv8/plv8/assets/38714600/472093f2-8dc5-4c3c-8689-0e6aeada035b">

Any idea, or can I just ignore?

James

**Comment by JerrySievert** [comment]
safe to ignore.  it's a compiler warning for a feature that v8 makes use of, but the compiler warnings are turned up fairly high.  it should be addressed upstream to upstream, but for now nothing for us to worry about.

**Comment by JamesInform** [comment]
Perfect! 
Thanks!
