### ISSUE TITLE
/usr/bin/ld: cannot find -lv8_base_with_compiler: No such file or directory

### ISSUE THREAD

**Issue by bradstimpson** [plv8/plv8js#555]
Hello,

I'm trying to install plv8 3.2.0 onto debian 12 and there is a linker error in the make stage.  Any help to get this resolved would be appreciated.

debian-12:/tmp/plv8$ sudo make
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "3.2.0"/' plv8_config.h.in > plv8_config.h
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE  -fPIC -c -o plv8.o plv8.cc
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE  -fPIC -c -o plv8_type.o plv8_type.cc
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE  -fPIC -c -o plv8_func.o plv8_func.cc
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE  -fPIC -c -o plv8_param.o plv8_param.cc
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE  -fPIC -c -o plv8_allocator.o plv8_allocator.cc
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE  -fPIC -c -o plv8_guc.o plv8_guc.cc
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -moutline-atomics -mtune=neoverse-n1 -fsigned-char -fPIC -shared -o plv8-3.2.0.so plv8.o plv8_type.o plv8_func.o plv8_param.o plv8_allocator.o plv8_guc.o -std=c++17 -xc++ -L/usr/lib/postgresql/lib  -L/usr/lib/llvm-11/lib  -Wl,--as-needed -Wl,-rpath,'/usr/lib/postgresql/lib',--enable-new-dtags  -std=c++17 -xc++ -Ldeps/v8-cmake/build -lrt -std=c++17 -Ldeps/v8-cmake/build -g -lv8_base_without_compiler -lv8_compiler -lv8_snapshot -lv8_inspector -lv8_libplatform -lv8_base_without_compiler -lv8_libsampler -lv8_torque_generated -lv8_libbase
/usr/bin/ld: cannot find -lv8_base_without_compiler: No such file or directory
/usr/bin/ld: cannot find -lv8_compiler: No such file or directory
/usr/bin/ld: cannot find -lv8_snapshot: No such file or directory
/usr/bin/ld: cannot find -lv8_base_without_compiler: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/usr/lib/postgresql/lib/pgxs/src/makefiles/../../src/Makefile.shlib:293: plv8-3.2.0.so] Error 1

**Comment by JerrySievert** [comment]
hm.  are you sure that the `git submodule update --init --recursive` ran and v8 itself got built?  there should be a `deps/v8-cmake` there.

https://github.com/plv8/plv8/blob/r3.2/Makefile#L44 is where it would run.

**Comment by bradstimpson** [comment]
That fixed it - thanks!

**Comment by JerrySievert** [comment]
did you run it manually, or ?

if there is something stopping the automatic checkout and build, I'd like to get it fixed :)

**Comment by bradstimpson** [comment]
I added it to my ansible script to update and recursive checkout:

```
- name: plv8 - download latest release
  git:
    repo: https://github.com/plv8/plv8.git
    dest: /tmp/plv8
    recursive: yes
    update: yes
    version: "{{ plv8_commit_version }}"
  become: yes
  ```
