### ISSUE TITLE
Support for pg16

### ISSUE THREAD

**Issue by luss** [plv8/plv8js#556]
Will pg16 support be in soon upcoming 3.2.1 point release?     Hopefully your required changes are minimal. :-)

Viva plV8!!
--Luss

**Comment by luss** [comment]
if it's helpful,  I can have one of my guys whos built/re-built several different extensions to pg16 do a first pass thru the plv8 code making #ifdef changes for supporting pg16 compiles and then submitting a clean pull request.

**Comment by JerrySievert** [comment]
there was initial 16 support pre 3.2, but that was against a much earlier 16.  I can take a look to see what has changed this weekend, it should be fairly minimal at this point.

**Comment by JerrySievert** [comment]
```
psql (16rc1)
Type "help" for help.

postgres=# create extension plv8;
CREATE EXTENSION
postgres=# select plv8_version();
 plv8_version
--------------
 3.2.0
(1 row)
```

is there a pg16 version you are seeing it not compile and work on?

**Comment by luss** [comment]
my mistake.  Jerry is correct.    plv8 3.2.0 is now available in the pgEdge diastro.  Thanks Jerry.
