### ISSUE TITLE
plv8_info() causes segmentation fault

### ISSUE THREAD

**Issue by martin98m** [plv8/plv8js#557]
plv8 version: `3.2.0`
Running `SELECT plv8_info();` causes Segmentaion fault. Query `SELECT plv8_version();` however worked as well as other functions using the extension.

The error happened in docker container using image `sibedge/postgres-plv8:15.4-3.2.0` as well as `postgres:latest` and manually installing the extension.

**Comment by JerrySievert** [comment]
thanks for the report - I'll try to reproduce and create a test/fix for it.

**Comment by JerrySievert** [comment]
this has been addressed in 3.2.1, and will be back ported to the 3.1 branch.
