### ISSUE TITLE
add functions setTimeout and setInterval

### ISSUE THREAD

**Issue by Leon-Alexey** [plv8/plv8js#560]
or integration with node.js

**Comment by Leon-Alexey** [comment]
or integration with node.js

**Comment by JerrySievert** [comment]
can you explain what you would gain from `setTimeout` and `setInterval` being added, and what you mean "integration with node.js"?

**Comment by Leon-Alexey** [comment]
example:
  let sleep = function(ms){
    return new Promise((resolve, reject)=>{setTimeout(()=>{resolve()}, ms)});
  }
periodical run procedure

**Comment by Leon-Alexey** [comment]
run javascript with runtime on node.js

**Comment by JerrySievert** [comment]
I'm struggling to understand what this would add - plv8 is not a long-running process, it is running inside of a database, and runs as stored procedures, not as general code.

**Comment by Leon-Alexey** [comment]
this is necessary for real-time data synchronization

**Comment by JerrySievert** [comment]
> run javascript with runtime on node.js

if you want to run code in node.js, then run your code in node.js, plv8 is a trusted language extension for postgres, and is not node.js.  plv8, by design, cannot make external connections via the network, or read/write disk.

**Comment by Leon-Alexey** [comment]
close the network, and read/write disk.

**Comment by JerrySievert** [comment]
maybe if you explain what specifically you're trying to do, and I can point you in an appropriate direction.

**Comment by Leon-Alexey** [comment]
necessary periodical run procedure for real-time data synchronization between oracle and postgres

**Comment by JerrySievert** [comment]
there are multiple extensions specifically built to deal with this, such as:

* https://github.com/citusdata/pg_cron
* https://github.com/cybertec-postgresql/pg_timetable

you cannot run a general program in plv8, but it can be called by one of these extensions to periodically do something.

although, this should be done outside of your database using an ETL tool.

**Comment by Leon-Alexey** [comment]
thanks, i to see
