### ISSUE TITLE
Use of Promise 

### ISSUE THREAD

**Issue by jaulz** [plv8/plv8js#565]
Basically, I am trying the very same as described in this issue: https://github.com/plv8/plv8/issues/564

I would like to emulate the `fetch` function using `pgsql-http` (which runs HTTP request synchronously). In order to make development easier and test functions locally as well I would like to have the same function signature and return a Promise. However, in contrast to what @mattiarossi wrote and also what I read in https://github.com/plv8/plv8/issues/360 it seems that my asynchronous test function does not work the same way as I would expect it to work:
```sql
CREATE OR REPLACE FUNCTION plv8_test() RETURNS text AS $$
    plv8.elog(NOTICE, "1");

    const getFoo = async function () {
      plv8.elog(NOTICE, "2");

      const foo = await new Promise((resolve) => {
        plv8.elog(NOTICE, "3");
        resolve('bar')
      })
      
      plv8.elog(NOTICE, "4");

      return foo
    }
    
    let foo = null
    getFoo().then((resolvedFoo) => {
      plv8.elog(NOTICE, "5");

      foo = resolvedFoo
    })
          
    plv8.elog(NOTICE, "6");
    
    return foo;
$$ LANGUAGE plv8 IMMUTABLE STRICT;
```

This is the result I get:
```
NOTICE:  1
NOTICE:  2
NOTICE:  3
NOTICE:  6
NOTICE:  4
NOTICE:  5

NULL
```

I understood that promises are resolved immediately and there is no asynchronous execution so I would have expected this result: 
```
NOTICE:  1
NOTICE:  2
NOTICE:  3
NOTICE:  4
NOTICE:  5
NOTICE:  6

"bar"
```

Right now I use version 3.1.5. Do you have any idea what I am doing wrong?

**Comment by JerrySievert** [comment]
no, I do not know what exactly is going on, but I would recommend to not even use promises or async code if you can avoid it.

**Comment by jaulz** [comment]
@JerrySievert okay, thanks anyway for your prompt answer 😊
