### ISSUE TITLE
Build guide mistakes

### ISSUE THREAD

**Issue by ArjixWasTaken** [plv8/plv8js#576]
The build guide gives wrong instructions.

https://plv8.github.io/#linux

the Makefile tries to init a git submodule, downloading the archive of a tag does not include the `.git` directory, because it is not a clone
so it fails to init the git submodules because no git repository exists

**Comment by ArjixWasTaken** [comment]
Correct instructions would be:

```bash
git clone https://github.com/plv8/plv8
cd plv8
git checkout tags/v3.2.2
make
```

**Comment by ArjixWasTaken** [comment]
Maybe this should also be in the documentation

https://stackoverflow.com/a/61877103

**Comment by leolird** [comment]
> Correct instructions would be:
> 
> ```shell
> git clone https://github.com/plv8/plv8
> cd plv8
> git checkout tags/v3.2.2
> make
> ```

yep, you real help me, thanks

**Comment by mdconaway** [comment]
Why not just:
`git clone -b v3.2.2 --recurse-submodules --depth 1 https://github.com/plv8/plv8.git`

This would clone the repo without downloading the whole history (smaller pull size), and should still recursively download submodules?

**Comment by tomw1964** [comment]
If you are using postgresql 17 then the command is this
git clone https://github.com/plv8/plv8
cd plv8
git checkout tags/v3.2.3
make

**Comment by JerrySievert** [comment]
default tag is _always_ the most recent on the branch.  also, this post is outdated as the correct build method was updated in the documentation quite a while ago, so closing this issue as it is causing confusion.
