### ISSUE TITLE
Versioned SO file creates inconviniences without any benefits

### ISSUE THREAD

**Issue by CyberDem0n** [plv8/plv8js#579]
Since [some time](plv8-$(PLV8_VERSION)) `plv8.so` is compiled and installed as `plv8-$(PLV8_VERSION).so`.
It creates a lot of inconvenience if plv8 is baked into a docker container, where it is not very common practice to keep multiple versions of the same extension. That is, if the upgraded container got a new version of plv8, all exiting plv8 functions will be broken until `ALTER EXTENSION plv8 UPDATE` is executed (because old SO file is simply not there).

I did some research of changes in the `plv8.sql.common` and found out that there were no changes in the API of functions provided by the extension. Only new functions were added, existing ones were remaining unchanged. In other words, `plv8.so` is very well backward compatible.

Now I am trying to understand the reasoning behind the current approach and figure out if I am missing something important, what prevents from just installing it as `plv8.so`.

**Comment by th3r0b0t** [comment]
I like to second that: When upgrading from an old postgresql version (prior to 13) to new one, you cannot install new versions of plv8 on the old cluster, therefore pg_upgradecluster complains about non-existent .so file; and things get worse when you find out older versions of plv8 cannot be installed on new postgresql versions (at least this was my case)!
I currently had to drop all functions, drop plv8, and restore everything on the new cluster

**Comment by JerrySievert** [comment]
plv8 uses versioned library files, as does the de-facto postgres extension postgis.  if postgis changes, then plv8 will consider it.

regardless, a change of this magnitude would not happen in a patch release.

**Comment by CyberDem0n** [comment]
@JerrySievert when did you checked last time what and how Postgis is doing?
JFYI, all SO files installed by Postgis have **only major version** as a suffux:
```bash
-rwxr-xr-x 1 root root  458816 Oct 11 19:33 /usr/local/pgsql/lib/address_standardizer-3.so
-rwxr-xr-x 1 root root 2596272 Oct 11 19:33 /usr/local/pgsql/lib/postgis-3.so
-rwxr-xr-x 1 root root  983936 Oct 11 19:33 /usr/local/pgsql/lib/postgis_raster-3.so
-rwxr-xr-x 1 root root  568752 Oct 11 19:33 /usr/local/pgsql/lib/postgis_sfcgal-3.so
-rwxr-xr-x 1 root root  704888 Oct 11 19:33 /usr/local/pgsql/lib/postgis_topology-3.so
```
That automatically means, that there is no problem when upgrading from Postgis 3.X to Postgis 3.5.
I am also quite confident that they make some special effort keeping SO files backward compatible with older versions.

Besides that, I am sorry so say it, but scale and complexity of Postgis is order of magnitude bigger than plv8, and if they can do it, I don't see any single reason why the same can't be done here.

**Comment by th3r0b0t** [comment]
@CyberDem0n  @JerrySievert , Sir, you both are ofc right about PostGIS, however if this is possible to change the behavior, solving an issue and not lose a value, why not (is it is so)?
