### ISSUE TITLE
Can't compile against PG17rc1

### ISSUE THREAD

**Issue by JamesInform** [plv8/plv8js#582]
Hej Jerry

I am trying to compile plv8 for the upcoming PostgreSQL 17 release.
Currently the first realease candidate is available.

But wether r3.2 nor v3.2.2 can compile.

With r3.2 I get:
![image](https://github.com/user-attachments/assets/a44b8577-e1dc-4639-a024-241a79d77be7)

Any idea?

**Comment by JerrySievert** [comment]
plv8 had not been updated to work with Postgres 17 (each major release of Postgres is typically a breaking change due to Postgres API changes).

it is now, as of 3.2.3

**Comment by JamesInform** [comment]
Thank you so much for your prompt support.
