### ISSUE TITLE
About using c++ in a postgres environment

### ISSUE THREAD

**Issue by undy11203** [plv8/plv8js#584]
Can you dispel my doubts about the correctness of the extension? I've seen on the code how you mix c++ class calls and postgreSQL functions calls, and I've also seen the global static variable
`static std::unique_ptr<v8::Platform> v8_platform = NULL;
`
Doesn't this violate the postgreSQL requirement?
`If calling backend functions from C++ code, be sure that the C++ call stack contains only plain old data structures (POD). This is necessary because backend errors generate a distant longjmp() that does not properly unroll a C++ call stack with non-POD objects.
`
If there is any discussion about this, you can give a link, because I didn't find it?
Or explain

P.S. Also sorry for my English

**Comment by JerrySievert** [comment]
> Can you dispel my doubts about the correctness of the extension?

I doubt it.  you're asking to prove a negative.

tne question you asked is specifically about calls _from_ c++ _to_ Postgres, of which there are very few.  most calls stay inside of v8, but when calls are made out to postgres use Postgres' `PG_TRY` whenever an error can be thrown and caught.

you are welcome to do your own audit, but plv8 has been in heavy use for over 12 years and is used at every major hosting company (and most minor ones).

closing this - these types of discussions should be asked on the discord, as noted in the readme, not as an issue.
