### ISSUE TITLE
Build fails with 'tuplestore_donestoring' was not declared in this scope

### ISSUE THREAD

**Issue by tomw1964** [plv8/plv8js#586]
I have followed the build instructions including the revised version posted in issues.
I am getting the following error

sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "3.2.2"/' plv8_config.h.in > plv8_config.h
g++ -DJSONB_DIRECT_CONVERSION -Ideps/v8-cmake/v8/include -std=c++17 -Wall -std=c++17 -fno-rtti -O2 -fPIC -Wall -Wno-register -xc++ -I. -I./ -I/usr/include/postgresql/17/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
plv8.cc: In function ‘Datum CallSRFunction(FunctionCallInfo, plv8_exec_env*, int, plv8_type*, plv8_type*)’:
plv8.cc:1077:2: **error**: ‘tuplestore_donestoring’ was not declared in this scope; did you mean ‘tuplestore_rescan’?
 1077 |  tuplestore_donestoring(tupstore);
      |  ^~~~~~~~~~~~~~~~~~~~~~
      |  tuplestore_rescan
make: *** [Makefile:91: plv8.o] Error 1

Any got any suggestions as to what is wrong?
I am compiling for postgresql version 17 on Ubuntu 20.04.6 LTS

Tom

**Comment by JerrySievert** [comment]
postgres major releases often times include breaking changes that extensions need to be modified to work with.

plv8 was updated a month ago to [3.2.3](https://github.com/plv8/plv8/blob/r3.2/Changes#L3-L5) which added postgres 17 support.

**Comment by tomw1964** [comment]
That worked thanks Jerry - I have updated the other post the references how to build this
