### ISSUE TITLE
BigInt seems to overflow

### ISSUE THREAD

**Issue by th3r0b0t** [plv8/plv8js#587]
Greetings.
Simply returning a `BigInt('997854384368767')` or any other odd numbers will always return that number changed to an even number! E.g: `997854384368766`

P.S: for reproduction sake, my test func parses a text from a json field and creates a BigInt; function's return type is of `numeric` type and argument is a `text` which has a Json string in it.
Postgresql 16, plv8 3.2.3, Debian 10

Good day.

**Comment by JerrySievert** [comment]
can you provide a test case against plv8 3.2.3 that shows this behavior?

```
jerry=# create function t() returns numeric as $$
return BigInt('997854384368767');
$$ language plv8;
CREATE FUNCTION
jerry=# select t();
        t
-----------------
 997854384368767
(1 row)

jerry=# select plv8_version();
 plv8_version
--------------
 3.2.3
(1 row)
```

note that as per the ecmascript standard, a `BigInt` is not serializable to `JSON` by default.

**Comment by th3r0b0t** [comment]
Please note that, I was trying `return BigInt(997854384368767);`  (mind the quote marks)!  
Although, looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) it should've been harmless to pass a number to the ctor instead of string!  
Also, [here](https://stackoverflow.com/questions/53335545/whats-the-biggest-bigint-value-in-js-as-per-spec) about `BigInt` max value.  
Heres the result:  
![image](https://github.com/user-attachments/assets/a6ab3acb-dcc9-41df-a198-6c99e35b29ac)
Heres the difference:  
9978543843687674`34`67`52`

**Comment by th3r0b0t** [comment]
@JerrySievert regarding previous comment, changing the ctor arg to string apparently fixes the issue, I.e: `BigInt('99785438436876743467')`!  
Node.Js result:  
![image](https://github.com/user-attachments/assets/71c34c6b-9544-439d-af1c-b2b4be91ad8f)
I'm guessing it has nothing to do with plv8, but v8 itself or perhaps I'm doing something wrong.

**Comment by JerrySievert** [comment]
a number to the constructor should be appended with an `n`.

and I think it's not necessarily a v8 thing (it's not plv8), but that v8 is adhering to the standard correctly.  `BigInt` is a bolt-on to javascript, and given the language construction is difficult to get working how you would expect it to.

that said, are you _sure_ you don't have a `libv8`, or `libnode`, or any `node.js` or `v8` packages installed on the same host?  if you do, it is guaranteed to screw up plv8, as node.js does not correctly embed v8, and pollutes the library space with a broken version, thus screwing up any other `v8` based software that is installed on the same host.  v8 is not meant to be built as a shared object, and any software that is doing as such is broken.

**Comment by JerrySievert** [comment]
also, please post text, not images, as images make it difficult to copy/reproduce.


(also, on a correctly built/deployed plv8):

```
jerry=# create or replace function t() returns numeric as $$
return BigInt(997854384368767);
$$ language plv8;
CREATE FUNCTION
jerry=# select t();
        t
-----------------
 997854384368767
(1 row)

jerry=# create or replace function t() returns numeric as $$
return BigInt(997854384368767n);
$$ language plv8;
CREATE FUNCTION
jerry=# select t();
        t
-----------------
 997854384368767
(1 row)
```

**Comment by th3r0b0t** [comment]
@JerrySievert Oh ofc, sorry for the images.  
I should look into that and see if any v8 of any kind is installed through anything else than plv8 and get back to you if necessary.  
Although, as I posted above, I tested the same thing in node.js and you can see that the result was still broken; But it's not the case with your test (even without `n` at the end), I'll be sure to test that; Even so based on this observation it might be that some other v8 lib installed on the host...  

My humblest regards for your time and the great work.
